#!/bin/sh
#___INFO__MARK_BEGIN__
#########################################################################
# 
#  The Contents of this file are made available subject to the terms of
#  the Sun Industry Standards Source License Version 1.2
# 
#  Sun Microsystems Inc., March, 2001
# 
# 
#  Sun Industry Standards Source License Version 1.2
#  =================================================
#  The contents of this file are subject to the Sun Industry Standards
#  Source License Version 1.2 (the "License"); You may not use this file
#  except in compliance with the License. You may obtain a copy of the
#  License at http://gridengine.sunsource.net/Gridengine_SISSL_license.html
# 
#  Software provided under this License is provided on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
#  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
#  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
#  See the License for the specific provisions governing your rights and
#  obligations concerning the Software.
# 
#   The Initial Developer of the Original Code is: Sun Microsystems, Inc.
#   and/or Swiss Center for Scientific Computing
# 
#   Copyright: 2002 by Sun Microsystems, Inc.
#   Copyright: 2002 by Swiss Center for Scientific Computing
# 
#   All Rights Reserved.
# 
########################################################################
#___INFO__MARK_END__
case $1 in
-debug)
	DEBUG_FLAGS="-Xdebug -Djava.compiler=NONE -Xbootclasspath:${JAVA_BIN}/../jre/lib/rt.jar:${JAVA_BIN}/../lib/tools.jar"
	shift
	;;
*)
	DEBUG_FLAGS=
	;;
esac

${JAVA_BIN}/java $DEBUG_FLAGS -classpath $RMSCLP -Dcom.sun.jini.discovery.debug=true -Dcom.sun.jini.join.debug=true -Dnet.jini.join.debug=true -Dnet.jini.lookup.debug=true -Djava.security.policy=policy.all -Djava.rmi.server.codebase=$1/jam-rms-dl.jar -Dcom.sun.grid.jam.gridengine.cwd=${SGE_ROOT}/${SGE_CELL:-default}/cwd com.sun.grid.jam.rms.RMServer $2 $3 $4 $5 $6

