#!/bin/sh

BASEDIR=`dirname $0`
BASEDIR=`cd $BASEDIR; pwd`

. $BASEDIR/run_util.sh

#java -Djava.security.debug=access,failure -cp $SGE_ROOT/lib/juti.jar:$SGE_ROOT/lib/jgdi.jar com.sun.grid.jgdi.examples.jmxeventmonitor.Main
#java -Djava.util.logging.config.file=util/shell_logging.properties -cp $SGE_ROOT/lib/juti.jar:$SGE_ROOT/lib/jgdi.jar com.sun.grid.jgdi.examples.jmxeventmonitor.Main
# -Djava.awt.headless=true
java -Dcom.sun.grid.jgdi.keyStore=/var/sgeCA/port$SGE_QMASTER_PORT/$SGE_CELL/private/keystore \
     -Dcom.sun.grid.jgdi.caTop="$SGE_ROOT/$SGE_CELL/common/sgeCA" \
     -Djava.util.logging.config.file=util/shell_logging.properties \
     -cp $SGE_ROOT/lib/juti.jar:$SGE_ROOT/lib/jgdi.jar \
     com.sun.grid.jgdi.examples.jmxeventmonitor.Main

