#!/bin/sh

BASEDIR=`dirname $0`
BASEDIR=`cd $BASEDIR; pwd`

. $BASEDIR/run_util.sh

JVM_ARGS=""
JVM_ARGS="$JVM_ARGS -cp build/classes"
#JVM_ARGS="$JVM_ARGS -Djava.util.logging.config.file=util/logging.properties"

url="bootstrap://${SGE_ROOT}@${SGE_CELL}:${SGE_QMASTER_PORT}"

run $JVM_ARGS com.sun.grid.jgdi.configuration.xml.XMLDump $url $*





