#___INFO__MARK_BEGIN__
##########################################################################
#
#  The Contents of this file are made available subject to the terms of
#  the Sun Industry Standards Source License Version 1.2
#
#  Sun Microsystems Inc., March, 2001
#
#
#  Sun Industry Standards Source License Version 1.2
#  =================================================
#  The contents of this file are subject to the Sun Industry Standards
#  Source License Version 1.2 (the "License"); You may not use this file
#  except in compliance with the License. You may obtain a copy of the
#  License at http://gridengine.sunsource.net/Gridengine_SISSL_license.html
#
#  Software provided under this License is provided on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
#  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
#  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
#  See the License for the specific provisions governing your rights and
#  obligations concerning the Software.
#
#  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
#
#  Copyright: 2001 by Sun Microsystems, Inc.
#
#  All Rights Reserved.
#
##########################################################################
#___INFO__MARK_END__

global check_functions
lappend check_functions "qalter_qs_args"

#                                                             max. column:     |
#****** qalter/qalter_qs_args() ******
# 
#  NAME
#     qalter_qs_args -- ??? 
#
#  SYNOPSIS
#     qalter_qs_args { } 
#
#  FUNCTION
#     ??? 
#
#  INPUTS
#
#  RESULT
#     ??? 
#
#  EXAMPLE
#     ??? 
#
#  NOTES
#     ??? 
#
#  BUGS
#     ??? 
#
#  SEE ALSO
#     ???/???
#*******************************
proc qalter_qs_args {} {
   global ts_config
   global CHECK_OUTPUT CHECK_USER

   set option "-qs_args arg1 arg2 arg3 -qs_end"
   set arch [resolve_arch $ts_config(master_host)]

   set job_id [submit_job "-N QS_ARGS -o /dev/null -j y -h $ts_config(product_root)/examples/jobs/sleeper.sh 10"]

   # start qalter
   set qalteroutput [start_remote_prog $ts_config(master_host) $CHECK_USER $ts_config(product_root)/bin/$arch/qalter "$option $job_id" qalterresult]

   puts $CHECK_OUTPUT $qalteroutput

   delete_job $job_id

   # evaluate result
   if {$qalterresult != 0} {
      set_error -1 "qalter $option $job_id failed:\n$qalteroutput"
   } else {
      set_error 0 "qalter $option $job_id succeeded:\n$qalteroutput"
   }
}

