#!/vol2/TCL_TK/glinux/bin/expect
#___INFO__MARK_BEGIN__
##########################################################################
#
#  The Contents of this file are made available subject to the terms of
#  the Sun Industry Standards Source License Version 1.2
#
#  Sun Microsystems Inc., March, 2001
#
#
#  Sun Industry Standards Source License Version 1.2
#  =================================================
#  The contents of this file are subject to the Sun Industry Standards
#  Source License Version 1.2 (the "License"); You may not use this file
#  except in compliance with the License. You may obtain a copy of the
#  License at http://gridengine.sunsource.net/Gridengine_SISSL_license.html
#
#  Software provided under this License is provided on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
#  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
#  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
#  See the License for the specific provisions governing your rights and
#  obligations concerning the Software.
#
#  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
#
#  Copyright: 2001 by Sun Microsystems, Inc.
#
#  All Rights Reserved.
#
##########################################################################
#___INFO__MARK_END__

global check_functions

lappend check_functions "qacct_issue1720"
lappend check_functions "qacct_issue1686"

proc qacct_issue1686 {} {
   global ts_config

   set acct_file "$ts_config(checktree_root_dir)/system_tests/clients/qacct/accounting_issue1686"

   set result [start_sge_bin "qacct" "-o -D -f $acct_file"]
   if {[string first "testuser1defaultdepartment" $result] > 0} {
      add_proc_error "qacct_issue1686" -1 "detected issue 1686:\n$output" 
   } 

   set_error 0 "ok"
}

proc qacct_issue1720 {} {
   set output [start_sge_bin qacct "-h unresolvable_host_xyz"]
   if {$prg_exit_state != 0} {
      add_proc_error "qacct_issue1720" -1 "qacct tried to resolve unknown hostname:\n$output"
   }

   set_error 0 "ok"
}
