#!/vol2/TCL_TK/glinux/bin/expect
#___INFO__MARK_BEGIN__
##########################################################################
#
#  The Contents of this file are made available subject to the terms of
#  the Sun Industry Standards Source License Version 1.2
#
#  Sun Microsystems Inc., March, 2001
#
#
#  Sun Industry Standards Source License Version 1.2
#  =================================================
#  The contents of this file are subject to the Sun Industry Standards
#  Source License Version 1.2 (the "License"); You may not use this file
#  except in compliance with the License. You may obtain a copy of the
#  License at http://gridengine.sunsource.net/Gridengine_SISSL_license.html
#
#  Software provided under this License is provided on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
#  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
#  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
#  See the License for the specific provisions governing your rights and
#  obligations concerning the Software.
#
#  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
#
#  Copyright: 2001 by Sun Microsystems, Inc.
#
#  All Rights Reserved.
#
##########################################################################
#___INFO__MARK_END__

# define global variable in this namespace
global check_name
global check_category 
global check_description 
global check_needs
global check_functions 
global check_errno 
global check_errstr 
global check_highest_level
global check_init_level_procedure
global check_root_access_needs
global env

set check_root_access_needs "no"

# define a level initialization procedure:
set check_init_level_procedure "qhost_init_level"

# define test's name and run level descriptions
set check_name            "qhost"
set check_category        "COMPATIBILITY SYSTEM VERIFIED"
set check_highest_level   0
set check_description(0)  "test qhost functionality"

# define test's dependencies
set check_needs           "init_core_system" 

# setup and cleanup functions
set check_setup_function qhost_setup
set check_cleanup_function qhost_cleanup


# define test's procedure order
set check_functions ""
lappend check_functions "qhost_issue1306"


proc qhost_init_level {} {
   global CHECK_ACT_LEVEL

   switch -- $CHECK_ACT_LEVEL {
      "0" {
         return 0
      }
   }

   return -1  ;# no other level 
}




# -------- local test procedures: initialization------------------------------


proc qhost_setup  {} {
   global CHECK_OUTPUT ts_config

   set_error 0 "ok"
}

proc qhost_cleanup  {} {
   global CHECK_OUTPUT ts_config

   set_error 0 "ok"
}


proc qhost_issue1306 {} {
   global ts_config CHECK_OUTPUT
   global CHECK_USER

   set arch [resolve_arch $ts_config(master_host)]
   set output [start_remote_prog $ts_config(master_host) $CHECK_USER "$ts_config(product_root)/bin/$arch/qhost" "-l bla"]
   puts $CHECK_OUTPUT $output

   set expected_output [translate $ts_config(master_host) 1 0 0 [sge_macro MSG_SGETEXT_UNKNOWN_RESOURCE_S] "bla"]

   if { [string match "*$expected_output" [string trim $output]] == 0 } {
      add_proc_error "-1" "qhost_issue1306" "qhost does not recognize unknown complex: $output"
   }

   set_error 0 "ok"
}


