#!/bin/sh
#
# (c) 2000 Sun Microsystems, Inc.
#

#
# Usage: sleeper.sh [time]]
#        default for time is 60 seconds

# -- our name ---
#$ -N Sleeper
#$ -S /bin/sh

/bin/echo Here I am. Sleeping now at: `date`

time=60
if [ $# -ge 1 ]; then
   time=$1
fi
sleep $time

echo Now it is: `date`
