#!/vol2/TCL_TK/glinux/bin/expect
#___INFO__MARK_BEGIN__
##########################################################################
#
#  The Contents of this file are made available subject to the terms of
#  the Sun Industry Standards Source License Version 1.2
#
#  Sun Microsystems Inc., March, 2001
#
#
#  Sun Industry Standards Source License Version 1.2
#  =================================================
#  The contents of this file are subject to the Sun Industry Standards
#  Source License Version 1.2 (the "License"); You may not use this file
#  except in compliance with the License. You may obtain a copy of the
#  License at http://gridengine.sunsource.net/Gridengine_SISSL_license.html
#
#  Software provided under this License is provided on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
#  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
#  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
#  See the License for the specific provisions governing your rights and
#  obligations concerning the Software.
#
#  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
#
#  Copyright: 2001 by Sun Microsystems, Inc.
#
#  All Rights Reserved.
#
##########################################################################
#___INFO__MARK_END__

global check_functions 
lappend check_functions "qdel_verify"                ;# just print what would be done
lappend check_functions "qdel_cleanup"

global qdel_help_lines
set qdel_help_lines 14

#                                                             max. column:     |
#****** qdel/qdel_verify() ******
# 
#  NAME
#     qdel_verify -- ??? 
#
#  SYNOPSIS
#     qdel_verify { } 
#
#  FUNCTION
#     ??? 
#
#  INPUTS
#
#  RESULT
#     ??? 
#
#  EXAMPLE
#     ??? 
#
#  NOTES
#     ??? 
#
#  BUGS
#     ??? 
#
#  SEE ALSO
#     ???/???
#*******************************
proc qdel_verify {} {
  global CHECK_OUTPUT CHECK_PRODUCT_ROOT CHECK_ARCH env CHECK_HOST


  # submit jobs to delete
  set job_list [submit_testjobs]

  set result [ catch { eval exec "$CHECK_PRODUCT_ROOT/bin/$CHECK_ARCH/qdel -verify $job_list" } qdel_output ] 

  puts $CHECK_OUTPUT "qdel_result = $result"
  puts $CHECK_OUTPUT "qdel_output = $qdel_output"

  if { $result != 0 } {
     set_error -1 "exit state is not 0"
  } 

  set nr_of_jobs [llength $job_list]
  set qd_out [split $qdel_output "\n"]
  set nr_of_output_lines [llength $qd_out]

  puts $CHECK_OUTPUT "nr_of_jobs = $nr_of_jobs"
  puts $CHECK_OUTPUT "nr_of_output_lines = $nr_of_output_lines"

  if { $nr_of_jobs != $nr_of_output_lines } {
     set_error -1 "nr of jobs doesn't match output lines"
  }

  catch { eval exec "$CHECK_PRODUCT_ROOT/bin/$CHECK_ARCH/qdel $job_list" }  

  set_error 0 "ok"
}



