#!/bin/sh

chmod 755 vnc_sun4_sosV_5.5/vncserver
chmod 644 vnc_sun4_sosV_5.5/vnc_javasrc/vncviewer.java
chmod 644 vnc_sun4_sosV_5.5/vnc_javasrc/makefile
patch -b < vnc_patches/vncserver.patch vnc_sun4_sosV_5.5/vncserver
patch -b < vnc_patches/vncviewer.patch vnc_sun4_sosV_5.5/vnc_javasrc/vncviewer.java
patch -b < vnc_patches/makefile.patch vnc_sun4_sosV_5.5/vnc_javasrc/makefile
cp vnc_patches/portal.vnc vnc_sun4_sosV_5.5/classes 
chmod 644 vnc_sun4_sosV_5.5/classes/portal.vnc
(cd vnc_sun4_sosV_5.5/vnc_javasrc; make clean; make)

