/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_grid_util_SGEUtil */

#ifndef _Included_com_sun_grid_util_SGEUtil
#define _Included_com_sun_grid_util_SGEUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_grid_util_SGEUtil
 * Method:    getPID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sun_grid_util_SGEUtil_getPID
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
