#!/bin/sh

# Dependencies on sge_sub_object.c which is created on the compile direcotry
# are not created during the dependency creation.
# Therefore we manually add in
#
#  source/libs/sgeobj/sgeobj_dependencies
#
# for "sge_sub_object.c" thesame dependencires as for its source file
# sge_sub_object_cpp.c
#
#
# This script is called from aimk after the core dependencies have been
# created

SRCDEP=../libs/sgeobj/sgeobj_dependencies
SRCDST=../libs/sgeobj/sgeobj_dependencies.1

sed -n '/^sge_sub_object_cpp.o/s/sge_sub_object_cpp.o/sge_sub_object.o/p' \
      $SRCDEP > $SRCDST

cat $SRCDST >> $SRCDEP

rm -f $SRCDST
