#!/bin/sh
exec 2>&1

if [ $# -lt 2 ]; then
   echo "Usage: gelint <gridengine dir> file(s)"
   exit 1
fi

GE=$1

if [ ! -d "$GE/source" -a ! -f "$GE/Changelog" ]; then
   echo "$GE is not a gridengine source directory!"
   echo "$GE/Changelog and $GE/source are missing!"
   exit 1
fi

shift
cd $GE/source

INC_FLAGS=`cd $GE/source; ./aimk -flags | grep INCLUDES | cut -d: -f2 | sed -e s§"\.\."§"$GE/source"§g`
C_FLAGS=`cd $GE/source; ./aimk -flags | grep CFLAGS | cut -d: -f2`

ADDITIONAL_INCLUDES=" -I/usr/include/rpc/ -I/vol2/SW/db-4.4.20/sol-sparc64/include/"

SPLINT_FLAG_LIST="+showsummary +stats -warnposixheaders +unixlib +skipsysheaders -predboolint -incondefs -retvalother -retvalint -exitarg +matchanyintegral -noeffect -unrecog -exportlocal -nullpass -type -nullassign -nullret -statictrans -formatconst -observertrans -boolops"
 

if [ -f /usr/pkg/bin/splint ]; then
   exec splint \
       $SPLINT_FLAG_LIST \
       $INC_FLAGS \
       $ADDITIONAL_INCLUDES \
       "$@"
   exit 0
else
   echo "splint binary not found, for this architecture!"
   exit 1
fi
