#!/bin/sh
#
# replaces the product mode strings in qmon_help.ad
#
#___INFO__MARK_BEGIN__
##########################################################################
#
#  The Contents of this file are made available subject to the terms of
#  the Sun Industry Standards Source License Version 1.2
#
#  Sun Microsystems Inc., March, 2001
#
#
#  Sun Industry Standards Source License Version 1.2
#  =================================================
#  The contents of this file are subject to the Sun Industry Standards
#  Source License Version 1.2 (the "License"); You may not use this file
#  except in compliance with the License. You may obtain a copy of the
#  License at http://www.gridengine.sunsource.net/license.html
#
#  Software provided under this License is provided on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
#  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
#  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
#  See the License for the specific provisions governing your rights and
#  obligations concerning the Software.
#
#  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
#
#  Copyright: 2001 by Sun Microsystems, Inc.
#
#  All Rights Reserved.
#
##########################################################################
#___INFO__MARK_END__

if [ ! -f '../dist/qmon/qmon_help.ad' ]; then
   echo "Error: '../dist/qmon/qmon_help.ad' does not exist"
   exit 1
fi

horig='../dist/qmon/qmon_help.ad'
hgrd='../dist/qmon/qmon_help.ad.grd'
hcod='../dist/qmon/qmon_help.ad.codine'

# ------------------------------
        
echo Processing $horig to $hgrd

QS_NAME=SGEEE
qs_name=sgeee
QS_NAME_S=SGEEE
qs_name_s=sgeee

rm -f $hgrd
sed -e "s/xxQS_NAMExx/$QS_NAME/g" \
    -e "s/xxqs_namexx/$qs_name/g" \
    -e "s/xxQS_NAME_Sxx/$QS_NAME_S/g" \
    -e "s/xxqs_name_sxx/$qs_name_s/g" $horig > $hgrd 

# ------------------------------

echo Processing $horig to $hcod

QS_NAME=SGE
qs_name=sge
QS_NAME_S=SGE
qs_name_s=sge

rm -f $hcod
sed -e "s/xxQS_NAMExx/$QS_NAME/g" \
    -e "s/xxqs_namexx/$qs_name/g" \
    -e "s/xxQS_NAME_Sxx/$QS_NAME_S/g" \
    -e "s/xxqs_name_sxx/$qs_name_s/g" $horig > $hcod
