#!/bin/sh
#
# replaces the product mode strings in qmon_help.ad
#

if [ ! -f '../dist/qmon/qmon_help.ad' ]; then
   echo "Error: '../dist/qmon/qmon_help.ad' does not exist"
   exit 1
fi

horig='../dist/qmon/qmon_help.ad'
hgrd='../dist/qmon/qmon_help.ad.grd'
hcod='../dist/qmon/qmon_help.ad.codine'

# ------------------------------
        
echo Processing $horig to $hgrd

QS_NAME=SGEEE
qs_name=sgeee
QS_NAME_S=SGEEE
qs_name_s=sgeee

rm -f $hgrd
sed -e "s/xxQS_NAMExx/$QS_NAME/g" \
    -e "s/xxqs_namexx/$qs_name/g" \
    -e "s/xxQS_NAME_Sxx/$QS_NAME_S/g" \
    -e "s/xxqs_name_sxx/$qs_name_s/g" $horig > $hgrd 

# ------------------------------

echo Processing $horig to $hcod

QS_NAME=SGE
qs_name=sge
QS_NAME_S=SGE
qs_name_s=sge

rm -f $hcod
sed -e "s/xxQS_NAMExx/$QS_NAME/g" \
    -e "s/xxqs_namexx/$qs_name/g" \
    -e "s/xxQS_NAME_Sxx/$QS_NAME_S/g" \
    -e "s/xxqs_name_sxx/$qs_name_s/g" $horig > $hcod
