#!/bin/sh

files=" \
       clients/common/common_dependencies \
       clients/qacct/qacct_dependencies  \
       clients/qalter/qalter_dependencies  \
       clients/qconf/qconf_dependencies  \
       clients/qdel/qdel_dependencies  \
       clients/qhost/qhost_dependencies  \
       clients/qmod/qmod_dependencies  \
       clients/qmon/qmon_dependencies  \
       clients/qsh/qsh_dependencies  \
       clients/qrsh/qrsh_dependencies  \
       clients/qstat/qstat_dependencies  \
       clients/qsub/qsub_dependencies  \
       common/common_dependencies  \
       daemons/commd/commd_dependencies  \
       daemons/common/common_dependencies  \
       daemons/execd/execd_dependencies  \
       daemons/qmaster/qmaster_dependencies  \
       daemons/schedd/schedd_dependencies  \
       daemons/shadowd/shadowd_dependencies  \
       daemons/shepherd/shepherd_dependencies  \
       libs/gdi/gdi_dependencies  \
       libs/comm/comm_dependencies  \
       libs/cull/cull_dependencies  \
       libs/sched/sched_dependencies  \
       libs/uti/uti_dependencies  \
       libs/rmon/rmon_dependencies  \
       utilbin/utilbin_dependencies \
       security/coshepherd/coshepherd_dependencies \
       security/sec/sec_dependencies \
       security/krb/krb_dependencies \
       security/gss/gss_dependencies
"
echo deleting and truncating: $files
rm -f $files
touch $files
