/**
 * Copyright 2003-2004 Sun Microsystems, Inc. All rights reserved.
 * Use is subject to license terms.
 * -----------------------------------------------------------------------------
 *  Generated from java_simpletestsuite.template
 *  !!! DO NOT EDIT THIS FILE !!!
 */
<%
  com.sun.grid.cull.JavaHelper jh = (com.sun.grid.cull.JavaHelper)params.get("javaHelper");
  com.sun.grid.cull.CullDefinition cullDef = (com.sun.grid.cull.CullDefinition)params.get("cullDef");
  com.sun.grid.cull.CullObject cullObj = null;
%>
package com.sun.grid.jgdi;
import junit.framework.*;

/**
 *
 * @author  cullconv
 */
public class JGDISimpleTestsuite extends TestCase {
   
   public static Test suite() throws Exception {
      
      TestSuite suite = new TestSuite();
<%
    java.util.Iterator iter = cullDef.getObjectNames().iterator();
    while(iter.hasNext()) {
       String name = (String)iter.next();
       cullObj = cullDef.getCullObject(name); 
       if( !cullObj.isRootObject() ) {
           continue;
       } %>
      suite.addTestSuite( <%=jh.getFullClassName(cullObj)%>TestCase.class );<%
    } // end of while
%>      
      return suite;
   }
}
