/**
 *  Generated from javamodel.template
 *  !!! DO NOT EDIT THIS FILE !!!
 */
<%
  com.sun.grid.cull.JavaHelper jh = (com.sun.grid.cull.JavaHelper)params.get("javaHelper");
  com.sun.grid.cull.CullObject cullObj = (com.sun.grid.cull.CullObject)params.get("cullObj");
  com.sun.grid.cull.CullAttr   attr = null;
  
  String name = jh.getNonPrimitiveClassname(cullObj);
  
%>
package <%=jh.getPackageName()%>;

import com.sun.grid.jgdi.event.ModEvent;
<% if(cullObj.getType() != cullObj.TYPE_PRIMITIVE) { %>
import <%=jh.getFullClassName(cullObj)%>;
<% } %>

/**
 */
public class <%=name%>ModEvent extends ModEvent {

<% // Default constructor ----------------------------------------- %>
  public <%=name%>ModEvent(long timestamp, int eventID) {
     super(timestamp, eventID, <%=jh.getClassName(cullObj)%>.class );
  } // end of default constructor

  public void add(<%=jh.getClassName(cullObj)%> obj) {
     super.add(obj);
  }
  
}
