/**
 * Copyright 2003-2004 Sun Microsystems, Inc. All rights reserved.
 * Use is subject to license terms.
 * -----------------------------------------------------------------------------
 *  Generated from java_config_factory.jsp
 *  !!! DO NOT EDIT THIS FILE !!!
 */
<%
  com.sun.grid.cull.JavaHelper jh = (com.sun.grid.cull.JavaHelper)params.get("javaHelper");
  com.sun.grid.cull.CullDefinition cullDef = (com.sun.grid.cull.CullDefinition)params.get("cullDef");
%>
package com.sun.grid.jgdi.configuration;


import java.util.*;

/**
 *  Factory class for all List/Del/Add/Mod Configuration objects
 *  @author richard.hierlmeier@sun.com
 */
public class ConfigurationFactory {

<%
    java.util.Iterator iter = cullDef.getObjectNames().iterator();
    while( iter.hasNext() ) {
      String name = (String)iter.next();
      com.sun.grid.cull.CullObject cullObj = cullDef.getCullObject(name); 
      String classname = jh.getClassName(cullObj);
%>
        
      public static <%=classname%> create<%=classname%>() {
         return new <%=classname%>Impl();
      }

      public static <%=classname%> create<%=classname%>WithDefaults() {
         return new <%=classname%>Impl(true);
      }
      
<%
    } // end of while
%>  

}
