// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package dant.test;

public final class AnnotationTestImpl_Stub
    extends java.rmi.server.RemoteStub
    implements dant.test.AnnotationTest, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_test_0;
    
    static {
	try {
	    $method_test_0 = dant.test.AnnotationTest.class.getMethod("test", new java.lang.Class[] {java.lang.Object.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public AnnotationTestImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of test(Object)
    public void test(java.lang.Object $param_Object_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_test_0, new java.lang.Object[] {$param_Object_1}, 2143551212271501933L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
