
package dant.test;

import javax.ejb.*;

/**
 * Created Oct 31, 2003 2:53:17 PM
 * Code generated by the Sun ONE Studio EJB Builder
 * @author dant
 */

public interface GridEJB extends javax.ejb.EJBObject {
	
	public java.io.Serializable compute (com.sun.grid.jgrid.Computable job) throws java.rmi.RemoteException, com.sun.grid.jgrid.ComputeException;
	
}

