/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_sge_drmaa_SGESession */

#ifndef _Included_sun_sge_drmaa_SGESession
#define _Included_sun_sge_drmaa_SGESession
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_sge_drmaa_SGESession_SUSPEND
#define sun_sge_drmaa_SGESession_SUSPEND 0L
#undef sun_sge_drmaa_SGESession_RESUME
#define sun_sge_drmaa_SGESession_RESUME 1L
#undef sun_sge_drmaa_SGESession_HOLD
#define sun_sge_drmaa_SGESession_HOLD 2L
#undef sun_sge_drmaa_SGESession_RELEASE
#define sun_sge_drmaa_SGESession_RELEASE 3L
#undef sun_sge_drmaa_SGESession_TERMINATE
#define sun_sge_drmaa_SGESession_TERMINATE 4L
/* Inaccessible static: JOB_IDS_SESSION_ALL */
#undef sun_sge_drmaa_SGESession_TIMEOUT_WAIT_FOREVER
#define sun_sge_drmaa_SGESession_TIMEOUT_WAIT_FOREVER -1i64
#undef sun_sge_drmaa_SGESession_TIMEOUT_NO_WAIT
#define sun_sge_drmaa_SGESession_TIMEOUT_NO_WAIT 0i64
#undef sun_sge_drmaa_SGESession_UNDETERMINED
#define sun_sge_drmaa_SGESession_UNDETERMINED 0L
#undef sun_sge_drmaa_SGESession_QUEUED_ACTIVE
#define sun_sge_drmaa_SGESession_QUEUED_ACTIVE 16L
#undef sun_sge_drmaa_SGESession_SYSTEM_ON_HOLD
#define sun_sge_drmaa_SGESession_SYSTEM_ON_HOLD 17L
#undef sun_sge_drmaa_SGESession_USER_ON_HOLD
#define sun_sge_drmaa_SGESession_USER_ON_HOLD 18L
#undef sun_sge_drmaa_SGESession_USER_SYSTEM_ON_HOLD
#define sun_sge_drmaa_SGESession_USER_SYSTEM_ON_HOLD 19L
#undef sun_sge_drmaa_SGESession_RUNNING
#define sun_sge_drmaa_SGESession_RUNNING 32L
#undef sun_sge_drmaa_SGESession_SYSTEM_SUSPENDED
#define sun_sge_drmaa_SGESession_SYSTEM_SUSPENDED 33L
#undef sun_sge_drmaa_SGESession_USER_SUSPENDED
#define sun_sge_drmaa_SGESession_USER_SUSPENDED 34L
#undef sun_sge_drmaa_SGESession_DONE
#define sun_sge_drmaa_SGESession_DONE 48L
#undef sun_sge_drmaa_SGESession_FAILED
#define sun_sge_drmaa_SGESession_FAILED 64L
/*
 * Class:     sun_sge_drmaa_SGESession
 * Method:    nativeGetContact
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_sge_drmaa_SGESession_nativeGetContact
  (JNIEnv *, jobject);

/*
 * Class:     sun_sge_drmaa_SGESession
 * Method:    nativeGetDRMSInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_sge_drmaa_SGESession_nativeGetDRMSInfo
  (JNIEnv *, jobject);

/*
 * Class:     sun_sge_drmaa_SGESession
 * Method:    nativeGetJobProgramStatus
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_sun_sge_drmaa_SGESession_nativeGetJobProgramStatus
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sun_sge_drmaa_SGESession
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sun_sge_drmaa_SGESession_nativeInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sun_sge_drmaa_SGESession
 * Method:    nativeRunBulkJobs
 * Signature: (IIII)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_sun_sge_drmaa_SGESession_nativeRunBulkJobs
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     sun_sge_drmaa_SGESession
 * Method:    nativeRunJob
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_sge_drmaa_SGESession_nativeRunJob
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_sge_drmaa_SGESession
 * Method:    nativeSynchronize
 * Signature: ([Ljava/lang/String;JZ)V
 */
JNIEXPORT void JNICALL Java_sun_sge_drmaa_SGESession_nativeSynchronize
  (JNIEnv *, jobject, jobjectArray, jlong, jboolean);

/*
 * Class:     sun_sge_drmaa_SGESession
 * Method:    nativeWait
 * Signature: (Ljava/lang/String;J)Lsun/sge/drmaa/SGEJobInfo;
 */
JNIEXPORT jobject JNICALL Java_sun_sge_drmaa_SGESession_nativeWait
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     sun_sge_drmaa_SGESession
 * Method:    nativeGetSignalName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_sge_drmaa_SGESession_nativeGetSignalName
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
