#!/vol2/TCL_TK/glinux/bin/expect
#___INFO__MARK_BEGIN__
##########################################################################
#
#  The Contents of this file are made available subject to the terms of
#  the Sun Industry Standards Source License Version 1.2
#
#  Sun Microsystems Inc., March, 2001
#
#
#  Sun Industry Standards Source License Version 1.2
#  =================================================
#  The contents of this file are subject to the Sun Industry Standards
#  Source License Version 1.2 (the "License"); You may not use this file
#  except in compliance with the License. You may obtain a copy of the
#  License at http://gridengine.sunsource.net/Gridengine_SISSL_license.html
#
#  Software provided under this License is provided on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
#  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
#  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
#  See the License for the specific provisions governing your rights and
#  obligations concerning the Software.
#
#  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
#
#  Copyright: 2001 by Sun Microsystems, Inc.
#
#  All Rights Reserved.
#
##########################################################################
#___INFO__MARK_END__

# define global variable in this namespace
global check_name 
global check_category
global check_description 
global check_needs
global check_functions 
global check_errno 
global check_errstr 
global check_highest_level
global check_init_level_procedure
global check_root_access_needs
global env

set check_root_access_needs "yes"

# JG: TODO: we have to create an own queue for this test!

# define a level initialization procedure:
set check_init_level_procedure "error_states_init_level"

# define test's name and run level descriptions
set check_name            "error_states"
set check_category        "COMPATIBILITY SYSTEM"
set check_highest_level   0
set check_description(0)  "Test job error behaviour"

# define test's dependencies
set check_needs           "init_core_system" 


# define test's procedure order
set check_functions ""
lappend check_functions "error_states_setup"
lappend check_functions "error_states_prolog"
lappend check_functions "error_states_epilog"
lappend check_functions "error_states_no_job_shell"
lappend check_functions "error_states_no_default_queue_shell"
lappend check_functions "error_states_no_unix_shell_script"
lappend check_functions "error_states_wrong_pe"
lappend check_functions "error_states_submit_error_script"
lappend check_functions "error_states_job_output"
lappend check_functions "error_states_cleanup"

proc error_states_init_level {} {
   global CHECK_ACT_LEVEL
   global CHECK_PRODUCT_TYPE
   global test_array_jobs 

  switch -- $CHECK_ACT_LEVEL {
     "0" { 
           return 0    
     } 
     "1" {
           return -1
     }
  } 
  return -1  ;# no other level else
}

# -------- local test procedures -----------------------------------------------

global error_states_qconfig
global error_states_check_queue

proc error_states_setup  {} {
   global CHECK_OUTPUT
   global CHECK_CORE_EXECD
   global error_states_qconfig
   global error_states_check_queue

   set error_states_check_queue "[lindex $CHECK_CORE_EXECD 0 ].q"
   puts $CHECK_OUTPUT "saving configuration for queue $error_states_check_queue"
   get_queue $error_states_check_queue error_states_qconfig

   set_error 0 "ok"
}


proc error_states_prolog {} {
   global CHECK_OUTPUT CHECK_PRODUCT_ROOT CHECK_SCRIPT_FILE_DIR
   global error_states_check_queue CHECK_TESTSUITE_ROOT CHECK_ARCH

   set jobargs "-o /dev/null -e /dev/null $CHECK_PRODUCT_ROOT/examples/jobs/sleeper.sh" 


   set my_conf(prolog) "/tmp/no_such_file.23"
   set_queue $error_states_check_queue my_conf 

   set job_id [submit_job "-q $error_states_check_queue $jobargs 5" ]
   trigger_scheduling
   wait_for_jobpending $job_id "leeper" 60 1
   set q_state [wait_for_queue_state $error_states_check_queue "E" 60]
   
   set my_conf(prolog) "$CHECK_TESTSUITE_ROOT/$CHECK_SCRIPT_FILE_DIR/exit_01.sh"
   set_queue $error_states_check_queue my_conf 

   puts $CHECK_OUTPUT "clearing error state $q_state of queue $error_states_check_queue"
   catch {  eval exec "$CHECK_PRODUCT_ROOT/bin/$CHECK_ARCH/qmod" "-c $error_states_check_queue" } catch_result
   puts $CHECK_OUTPUT $catch_result

   trigger_scheduling
   wait_for_jobpending $job_id "leeper" 60 1
   set q_state [wait_for_queue_state $error_states_check_queue "E" 60]

   set my_conf(prolog) "$CHECK_TESTSUITE_ROOT/$CHECK_SCRIPT_FILE_DIR/exit_99.sh"
   set_queue $error_states_check_queue my_conf 

   puts $CHECK_OUTPUT "clearing error state $q_state of queue $error_states_check_queue"
   catch {  eval exec "$CHECK_PRODUCT_ROOT/bin/$CHECK_ARCH/qmod" "-c $error_states_check_queue" } catch_result
   puts $CHECK_OUTPUT $catch_result

   trigger_scheduling
   wait_for_jobpending $job_id "leeper" 60 1

   wait_for_job_state $job_id "R" 60

   set my_conf(prolog) "$CHECK_TESTSUITE_ROOT/$CHECK_SCRIPT_FILE_DIR/exit_00.sh"
   set_queue $error_states_check_queue my_conf 

   trigger_scheduling
   wait_for_jobpending $job_id "leeper" 60 1
   wait_for_jobstart $job_id "leeper" 60
   wait_for_jobend $job_id "leeper" 60

   set my_conf(prolog) "NONE"
   set_queue $error_states_check_queue my_conf 

   set_error 0 "ok"
}

proc error_states_epilog {} {
   global CHECK_OUTPUT CHECK_PRODUCT_ROOT CHECK_SCRIPT_FILE_DIR
   global error_states_check_queue CHECK_TESTSUITE_ROOT 

   set jobargs "-o /dev/null -e /dev/null $CHECK_PRODUCT_ROOT/examples/jobs/sleeper.sh" 


   set my_conf(epilog) "/tmp/no_such_file.23"
   set_queue $error_states_check_queue my_conf 


   set job_id [submit_job "-q $error_states_check_queue $jobargs 5" ]
   wait_for_jobpending $job_id "leeper" 60 1
   wait_for_jobstart $job_id "leeper" 60
   wait_for_jobend $job_id "leeper" 60
   # JG: TODO: this get_qacct will fail in 6.0 due to delayed writing of accounting information
   # set reporting_params, accounting_flush_time to 00:00:00, or poll one minute until
   # accounting info is available. Consider writing a function get_qacct_poll in sge_procedures
   # There are multiple calls to qacct in this check!
   get_qacct $job_id
   puts $CHECK_OUTPUT "qacct output for job $job_id:"
   puts $CHECK_OUTPUT "failed: $qacct_info(failed)"
   puts $CHECK_OUTPUT "exit_status:  $qacct_info(exit_status)"
   set qacct_error [lindex $qacct_info(failed) 0]
   set exit_state  [lindex $qacct_info(exit_status) 0]
   if { $exit_state != 0 } {
      add_proc_error "error_states_epilog" -1 "exit state not 0: $exit_state"
   }
   if { $qacct_error != 14 } {
      add_proc_error "error_states_epilog" -1 "failed not 14 (before epilog): $qacct_error"
   }

   set my_conf(epilog) "$CHECK_TESTSUITE_ROOT/$CHECK_SCRIPT_FILE_DIR/exit_01.sh"
   set_queue $error_states_check_queue my_conf 

   set job_id [submit_job "-q $error_states_check_queue $jobargs 15" ]
   wait_for_jobstart $job_id "leeper" 60
   wait_for_jobend $job_id "leeper" 60
   get_qacct $job_id
   puts $CHECK_OUTPUT "qacct output for job $job_id:"
   puts $CHECK_OUTPUT "failed: $qacct_info(failed)"
   puts $CHECK_OUTPUT "exit_status:  $qacct_info(exit_status)"

   set exit_state  [lindex $qacct_info(exit_status) 0]
   if { $exit_state != 0 } {
      add_proc_error "error_states_epilog" -1 "exit state not 0: $exit_state"
   }
  
   if { [ string first "15" $qacct_info(failed)] < 0 || 
        [ string first "in epilog" $qacct_info(failed)] < 0   } {
        add_proc_error "error_states_epilog" -1 "no in epilog error: $qacct_info(failed)"
   }

   set my_conf(epilog) "NONE"
   set_queue $error_states_check_queue my_conf 


   set_error 0 "ok"
}


proc error_states_no_job_shell {} {
   global CHECK_OUTPUT error_states_check_queue
   global CHECK_PRODUCT_ROOT

   set jobargs "-o /dev/null -e /dev/null $CHECK_PRODUCT_ROOT/examples/jobs/sleeper.sh" 
      
   set job_id [submit_job "-S /tmp/no_such_file.23 -q $error_states_check_queue $jobargs 10" ]
   wait_for_jobpending $job_id "leeper" 60 1
   wait_for_job_state $job_id "E" 60

   delete_job $job_id

   set_error 0 "ok"
}

proc error_states_no_default_queue_shell {} {
   global CHECK_OUTPUT error_states_check_queue
   global CHECK_PRODUCT_ROOT CHECK_ARCH CHECK_TESTSUITE_ROOT CHECK_SCRIPT_FILE_DIR

   set jobargs "-o /dev/null -e /dev/null $CHECK_TESTSUITE_ROOT/$CHECK_SCRIPT_FILE_DIR/exit_00.sh" 

   
   get_queue $error_states_check_queue org_conf

   puts $CHECK_OUTPUT "queue shell_start_mode is $org_conf(shell_start_mode)"

   set my_conf(shell) "/tmp/no_such_file.23"
   set my_conf(shell_start_mode) "posix_compliant"  
   set_queue $error_states_check_queue my_conf

   
   set job_id [submit_job "-q $error_states_check_queue $jobargs" ]
   wait_for_jobpending $job_id "exit" 60 1
   set q_state [wait_for_queue_state $error_states_check_queue "E" 60]
   
   set my_conf(shell) $org_conf(shell) 
   set_queue $error_states_check_queue my_conf 

   puts $CHECK_OUTPUT "clearing error state $q_state of queue $error_states_check_queue"
   catch {  eval exec "$CHECK_PRODUCT_ROOT/bin/$CHECK_ARCH/qmod" "-c $error_states_check_queue" } catch_result
   puts $CHECK_OUTPUT $catch_result


   wait_for_jobstart $job_id "exit" 60
   wait_for_jobend $job_id "exit" 60


   set my_conf(shell_start_mode) "unix_behavior"
   set_queue $error_states_check_queue my_conf
   set job_id [submit_job "-q $error_states_check_queue $jobargs" ]
   wait_for_jobpending $job_id "exit" 60 1
   wait_for_jobstart $job_id "exit" 60
   wait_for_jobend $job_id "exit" 60 
   set my_conf(shell_start_mode) $org_conf(shell_start_mode)
   set_queue $error_states_check_queue my_conf


   set_error 0 "ok"
}

proc error_states_no_unix_shell_script {} {
   global CHECK_OUTPUT error_states_check_queue
   global CHECK_PRODUCT_ROOT CHECK_ARCH CHECK_TESTSUITE_ROOT CHECK_SCRIPT_FILE_DIR


   get_queue $error_states_check_queue org_conf
   puts $CHECK_OUTPUT "queue shell_start_mode is $org_conf(shell_start_mode)"
   
   set my_conf(shell_start_mode) "unix_behavior"  
   set_queue $error_states_check_queue my_conf

   set jobargs "-o /dev/null -e /dev/null $CHECK_TESTSUITE_ROOT/$CHECK_SCRIPT_FILE_DIR/exit_00.sh"  
   set job_id [submit_job "-q $error_states_check_queue $jobargs" ]
   wait_for_jobpending $job_id "exit" 60 1
   wait_for_jobstart $job_id "exit" 60 
   wait_for_jobend $job_id "exit" 60 
   
   set jobargs "-o /dev/null -e /dev/null $CHECK_TESTSUITE_ROOT/$CHECK_SCRIPT_FILE_DIR/no_unix_shell.sh"  
   set job_id [submit_job "-q $error_states_check_queue $jobargs" ]
   wait_for_jobpending $job_id "no_unix" 60 1
   wait_for_job_state $job_id "E" 60 

   delete_job $job_id

   set my_conf(shell_start_mode) $org_conf(shell_start_mode)
   set_queue $error_states_check_queue my_conf

   set_error 0 "ok"
}

proc error_states_wrong_pe {} {
   global CHECK_PRODUCT_TYPE CHECK_CORE_EXECD CHECK_OUTPUT
   global error_states_check_queue CHECK_PRODUCT_ROOT CHECK_ARCH
   global CHECK_TESTSUITE_ROOT CHECK_SCRIPT_FILE_DIR

   set wrong_start_pe(pe_name)    "wrong_start_pe"
#   set wrong_start_pe(queue_list) $error_states_check_queue
   set wrong_start_pe(slots)      5
   set wrong_start_pe(start_proc_args) "/tmp/no_such_file.23"
   add_pe wrong_start_pe
   assign_queues_with_pe_object $error_states_check_queue wrong_start_pe


   set wrong_stop_pe(pe_name)    "wrong_stop_pe"
#   set wrong_stop_pe(queue_list) $error_states_check_queue
   set wrong_stop_pe(slots)      5
   set wrong_stop_pe(stop_proc_args) "/tmp/no_such_file.23"
   add_pe wrong_stop_pe
   assign_queues_with_pe_object $error_states_check_queue wrong_stop_pe

   set error_start_pe(pe_name)    "error_start_pe"
#   set error_start_pe(queue_list) $error_states_check_queue
   set error_start_pe(slots)      5
   set error_start_pe(start_proc_args) "$CHECK_TESTSUITE_ROOT/$CHECK_SCRIPT_FILE_DIR/exit_01.sh"
   add_pe error_start_pe
   assign_queues_with_pe_object $error_states_check_queue error_start_pe

   set error_stop_pe(pe_name)    "error_stop_pe"
#   set error_stop_pe(queue_list) $error_states_check_queue
   set error_stop_pe(slots)      5
   set error_stop_pe(stop_proc_args) "$CHECK_TESTSUITE_ROOT/$CHECK_SCRIPT_FILE_DIR/exit_01.sh"
   add_pe error_stop_pe
   assign_queues_with_pe_object $error_states_check_queue error_stop_pe



   set jobargs "-o /dev/null -e /dev/null $CHECK_PRODUCT_ROOT/examples/jobs/sleeper.sh" 
   set job_id [submit_job "-pe wrong_start_pe 1-4 $jobargs 5" ]
   wait_for_jobpending $job_id "leeper" 60 1
   set q_state [ wait_for_queue_state $error_states_check_queue "E" 60 ]
   
   puts $CHECK_OUTPUT "clearing error state $q_state of queue $error_states_check_queue"
   catch {  eval exec "$CHECK_PRODUCT_ROOT/bin/$CHECK_ARCH/qmod" "-c $error_states_check_queue" } catch_result
   puts $CHECK_OUTPUT $catch_result
   delete_job $job_id
   set q_state [get_queue_state $error_states_check_queue]
   if { $q_state != "" } {
      add_proc_error "error_states_wrong_pe" -1 "queue $error_states_check_queue has wrong state" 
   }


   set job_id [submit_job "-pe wrong_stop_pe 1-4 $jobargs 5" ]
   wait_for_jobpending $job_id "leeper" 60 1
   wait_for_jobstart $job_id "leeper" 60
   wait_for_jobend $job_id "leeper" 60
   get_qacct $job_id
   puts $CHECK_OUTPUT "qacct output for job $job_id:"
   puts $CHECK_OUTPUT "failed: $qacct_info(failed)"
   puts $CHECK_OUTPUT "exit_status:  $qacct_info(exit_status)"
   set qacct_error [lindex $qacct_info(failed) 0]
   set exit_state  [lindex $qacct_info(exit_status) 0]
   if { $exit_state != 0 } {
      add_proc_error "error_states_wrong_pe" -1 "exit state not 0: $exit_state"
   }
   if { $qacct_error != 12 } {
      add_proc_error "error_states_wrong_pe" -1 "failed not 12 (before pestop): $qacct_error"
   }
   
 
   set jobargs "-o /dev/null -e /dev/null $CHECK_PRODUCT_ROOT/examples/jobs/sleeper.sh" 
   set job_id [submit_job "-pe error_start_pe 1-4 $jobargs 5" ]
   wait_for_jobpending $job_id "leeper" 60 1
   set q_state [ wait_for_queue_state $error_states_check_queue "E" 60 ]
   
   puts $CHECK_OUTPUT "clearing error state $q_state of queue $error_states_check_queue"
   catch {  eval exec "$CHECK_PRODUCT_ROOT/bin/$CHECK_ARCH/qmod" "-c $error_states_check_queue" } catch_result
   puts $CHECK_OUTPUT $catch_result
   delete_job $job_id
   set q_state [get_queue_state $error_states_check_queue]
   if { $q_state != "" } {
      add_proc_error "error_states_wrong_pe" -1 "queue $error_states_check_queue has wrong state" 
   }


   set job_id [submit_job "-pe error_stop_pe 1-4 $jobargs 5" ]
   wait_for_jobpending $job_id "leeper" 60 1
   wait_for_jobstart $job_id "leeper" 60
   wait_for_jobend $job_id "leeper" 60
   get_qacct $job_id
   puts $CHECK_OUTPUT "qacct output for job $job_id:"
   puts $CHECK_OUTPUT "failed: $qacct_info(failed)"
   puts $CHECK_OUTPUT "exit_status:  $qacct_info(exit_status)"
   set qacct_error [lindex $qacct_info(failed) 0]
   set exit_state  [lindex $qacct_info(exit_status) 0]
   if { $exit_state != 0 } {
      add_proc_error "error_states_wrong_pe" -1 "exit state not 0: $exit_state"
   }
   if { $qacct_error != 12 } {
      add_proc_error "error_states_wrong_pe" -1 "failed not 12 (before pestop): $qacct_error"
   }
   if { [ string first "13" $qacct_info(failed) ] < 0 ||
        [ string first "in pestop" $qacct_info(failed) ] < 0   } {
      add_proc_error "error_states_wrong_pe" -1 "no in pestop error: $qacct_info(failed)"
   }


   # workaround: in sgeee a job still exists in qmaster after it exited for some time
   #             therefore the pe cannot be deleted
   if {$CHECK_PRODUCT_TYPE == "sgeee"} {
      puts $CHECK_OUTPUT "waiting for qmaster to remove jobs from it's internal job list"
      do_wait 60
   }

   del_pe "wrong_start_pe"
   del_pe "wrong_stop_pe"
   del_pe "error_start_pe"
   del_pe "error_stop_pe"


   set_error 0 "ok"
}

proc error_states_submit_error_script {} {
   global CHECK_OUTPUT CHECK_TESTSUITE_ROOT CHECK_SCRIPT_FILE_DIR
   global error_states_check_queue

   set jobargs "-o /dev/null -e /dev/null $CHECK_TESTSUITE_ROOT/$CHECK_SCRIPT_FILE_DIR/error.sh" 
   set job_id [submit_job "-q $error_states_check_queue $jobargs" ]
   wait_for_jobpending $job_id "leeper" 60 1
   wait_for_jobstart $job_id "leeper" 60
   wait_for_jobend $job_id "leeper" 60
   get_qacct $job_id
   puts $CHECK_OUTPUT "qacct output for job $job_id:"
   puts $CHECK_OUTPUT "failed: $qacct_info(failed)"
   puts $CHECK_OUTPUT "exit_status:  $qacct_info(exit_status)"
   if { $qacct_info(exit_status) == 0 } {
      add_proc_error "error_states_submit_error_script" -1 "job should have not 0 as exit_status"
   } 
   set_error 0 "ok"
}

proc error_states_job_output {} {
   global CHECK_OUTPUT CHECK_HOST CHECK_FIRST_FOREIGN_SYSTEM_USER CHECK_USER
   global error_states_check_queue CHECK_TESTSUITE_ROOT CHECK_SCRIPT_FILE_DIR
   global CHECK_CORE_EXECD


   set test_dir  [get_tmp_directory_name "" temp "dir" 1]
   set test_file [get_tmp_file_name "" temp tmp 1]
   set test_local_dir [get_tmp_directory_name "" local "dir" 1]
 
   puts $CHECK_OUTPUT "test_dir:       $test_dir"
   puts $CHECK_OUTPUT "test_file:      $test_file"
   puts $CHECK_OUTPUT "test_local_dir: $test_local_dir"

   set result [ start_remote_prog $CHECK_HOST $CHECK_FIRST_FOREIGN_SYSTEM_USER "mkdir" $test_dir ]
   puts $CHECK_OUTPUT $result
   if { $prg_exit_state != 0 } {
      add_proc_error "error_states_job_output" -1 "error creating directory $test_dir"
   }

   set result [ start_remote_prog $CHECK_HOST $CHECK_FIRST_FOREIGN_SYSTEM_USER "touch" $test_file ]
   puts $CHECK_OUTPUT $result
   if { $prg_exit_state != 0 } {
      add_proc_error "error_states_job_output" -1 "error creating file $test_file"
   }

   set result [ start_remote_prog $CHECK_HOST $CHECK_FIRST_FOREIGN_SYSTEM_USER "chmod" "700 $test_dir" ]
   puts $CHECK_OUTPUT $result
   if { $prg_exit_state != 0 } {
      add_proc_error "error_states_job_output" -1 "error chmod $test_dir"
   }

   set result [ start_remote_prog $CHECK_HOST $CHECK_FIRST_FOREIGN_SYSTEM_USER "chmod" "600 $test_file" ]
   puts $CHECK_OUTPUT $result
   if { $prg_exit_state != 0 } {
      add_proc_error "error_states_job_output" -1 "error chmod $test_file"
   }

   set result [ start_remote_prog $CHECK_HOST $CHECK_USER "mkdir" $test_local_dir ]
   puts $CHECK_OUTPUT $result
   if { $prg_exit_state != 0 } {
      add_proc_error "error_states_job_output" -1 "error creating directory $test_local_dir"
   }



   set jobargs "-o $test_dir -e /dev/null $CHECK_TESTSUITE_ROOT/$CHECK_SCRIPT_FILE_DIR/error.sh" 
   set job_id [submit_job "-q $error_states_check_queue $jobargs" ]
   wait_for_jobpending $job_id "leeper" 60 1
   wait_for_job_state $job_id "E" 60  
   delete_job $job_id

   set jobargs "-o $test_file -e /dev/null $CHECK_TESTSUITE_ROOT/$CHECK_SCRIPT_FILE_DIR/error.sh" 
   set job_id [submit_job "-q $error_states_check_queue $jobargs" ]
   wait_for_jobpending $job_id "leeper" 60 1
   wait_for_job_state $job_id "E" 60  
   delete_job $job_id


   set jobargs "-o /dev/null -e $test_dir $CHECK_TESTSUITE_ROOT/$CHECK_SCRIPT_FILE_DIR/error.sh" 
   set job_id [submit_job "-q $error_states_check_queue $jobargs" ]
   wait_for_jobpending $job_id "leeper" 60 1
   wait_for_job_state $job_id "E" 60  
   delete_job $job_id
   

   set jobargs "-o /dev/null -e $test_file $CHECK_TESTSUITE_ROOT/$CHECK_SCRIPT_FILE_DIR/error.sh" 
   set job_id [submit_job "-q $error_states_check_queue $jobargs" ]
   wait_for_jobpending $job_id "leeper" 60 1
   wait_for_job_state $job_id "E" 60  
   delete_job $job_id


   if { [ llength $CHECK_CORE_EXECD ] < 2 } {
      add_proc_error "error_states_job_output" -3 "need min. 2 execd hosts for this check" 
   } else {
      # error queue
      set error_run_queue "[lindex $CHECK_CORE_EXECD 1].q"
      set result [ start_remote_prog $CHECK_HOST $CHECK_USER "cd" "$test_local_dir ; qsub -cwd -q $error_run_queue $CHECK_TESTSUITE_ROOT/$CHECK_SCRIPT_FILE_DIR/error.sh" ]
      puts $CHECK_OUTPUT $result
      set job_id [lindex $result 2]
      wait_for_jobpending $job_id "leeper" 60 1
      wait_for_job_state $job_id "E" 60  
      delete_job $job_id

      #no error queue
      set result [ start_remote_prog $CHECK_HOST $CHECK_USER "cd" "$test_local_dir ; qsub -cwd -q $error_states_check_queue $CHECK_TESTSUITE_ROOT/$CHECK_SCRIPT_FILE_DIR/error.sh" ]
      puts $CHECK_OUTPUT $result
      set job_id [lindex $result 2]
      wait_for_jobpending $job_id "leeper" 60 1
      wait_for_jobstart $job_id "leeper" 60
      wait_for_jobend $job_id "leeper" 60
      
      set result [ start_remote_prog $CHECK_HOST $CHECK_USER "cat" $test_local_dir/Sleeper.o${job_id} ]
      puts $CHECK_OUTPUT "job output file: $result"
      if { [string first "here is the error" $result] < 0 } {
         add_proc_error "error_states_job_output" -1 "wrong or no job output"
      }
      set result [ start_remote_prog $CHECK_HOST $CHECK_USER "cat" $test_local_dir/Sleeper.e${job_id} ]
      puts $CHECK_OUTPUT "job error file: $result"
      if { [string first "biNnN" $result] < 0 } {
         add_proc_error "error_states_job_output" -1 "wrong or no job error output"
      }
   }

   set result [ start_remote_prog $CHECK_HOST $CHECK_FIRST_FOREIGN_SYSTEM_USER "rmdir" $test_dir ]
   puts $CHECK_OUTPUT $result
   if { $prg_exit_state != 0 } {
      add_proc_error "error_states_job_output" -1 "error deleting directory $test_dir"
   }

   set result [ start_remote_prog $CHECK_HOST $CHECK_FIRST_FOREIGN_SYSTEM_USER "rm" $test_file ]
   puts $CHECK_OUTPUT $result
   if { $prg_exit_state != 0 } {
      add_proc_error "error_states_job_output" -1 "error deleting file $test_file"
   }

   delete_directory $test_local_dir
 
   set_error 0 "ok"
}

proc error_states_cleanup  {} {
   global CHECK_OUTPUT CHECK_PRODUCT_ROOT CHECK_ARCH
   global error_states_qconfig error_states_check_queue


   puts $CHECK_OUTPUT "do qdel -uall"
   set catch_result [delete_all_jobs]
   puts $CHECK_OUTPUT $catch_result

 
   puts $CHECK_OUTPUT "clearing pos. error state of queue $error_states_check_queue"
   catch {  eval exec "$CHECK_PRODUCT_ROOT/bin/$CHECK_ARCH/qmod" "-c $error_states_check_queue" } catch_result
   puts $CHECK_OUTPUT $catch_result


   puts $CHECK_OUTPUT "restoring configuration for queue $error_states_check_queue"
   set_queue $error_states_check_queue error_states_qconfig

   set_error 0 "ok"
}



