/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_grid_util_SGEUtil */

#ifndef _Included_com_sun_grid_util_SGEUtil
#define _Included_com_sun_grid_util_SGEUtil
#ifdef __cplusplus
extern "C" {
#endif

void setEcho(int flag);

/* Inaccessible static: theInstance */
/*
 * Class:     com_sun_grid_util_SGEUtil
 * Method:    getPID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sun_grid_util_SGEUtil_getPID
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_grid_util_SGEUtil
 * Method:    getNativePassword
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sun_grid_util_SGEUtil_getNativePassword
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
