'\" t
.\"___INFO__MARK_BEGIN__
.\"
.\" Copyright: 2001 by Sun Microsystems, Inc.
.\"
.\"___INFO__MARK_END__
.\" $RCSfile: access_list.5,v $     Last Update: $Date: 2001/07/20 08:19:15 $     Revision: $Revision: 1.3 $
.\"
.\"
.\" Some handy macro definitions [from Tom Christensen's man(1) manual page].
.\"
.de SB		\" small and bold
.if !"\\$1"" \\s-2\\fB\&\\$1\\s0\\fR\\$2 \\$3 \\$4 \\$5
..
.\"
.de T		\" switch to typewriter font
.ft CW		\" probably want CW if you don't have TA font
..
.\"
.de TY		\" put $1 in typewriter font
.if t .T
.if n ``\c
\\$1\c
.if t .ft P
.if n \&''\c
\\$2
..
.\"
.de M		\" man page reference
\\fI\\$1\\fR\\|(\\$2)\\$3
..
.TH ACCESS_LIST 5 "$Date: 2001/07/20 08:19:15 $" "xxRELxx" "xxQS_NAMExx File Formats"
.\"
.SH NAME
access_list \- xxQS_NAMExx access list file format
.\"
.SH DESCRIPTION
Access lists are used in xxQS_NAMExx to define access permissions of users
to queues (see
.M queue_conf 5 )
or parallel environments (see
.M xxqs_name_sxx_pe 5 ).
A list of currently configured access lists can be displayed via the
.M qconf 1
\fB\-sul\fP option. The contents of each enlisted access list can
shown via the \fB\-su\fP switch. The output follows the
.I access_list
format description. New access lists can be created and existing can be
modified via the \fB\-au\fP and \fB\-du\fP options to
.M qconf 1 .
.\"
.\"
.SH FORMAT
Each user or UNIX user group appears in a single lines. Only symbolic names
are allowed. A group is differentiated from a user name by prefixing the
group name with a '@' sign.
.\"
.\"
.SH "SEE ALSO"
.M xxqs_name_sxx_intro 1 ,
.M qconf 1 ,
.M xxqs_name_sxx_pe 5 ,
.M queue_conf 5 .
.\"
.SH "COPYRIGHT"
See
.M xxqs_name_sxx_intro 1
for a full statement of rights and permissions.
