'\" t
.\"___INFO__MARK_BEGIN__
.\"
.\" Copyright: 2001 by Sun Microsystems, Inc.
.\"
.\"___INFO__MARK_END__
.\" $RCSfile: complex.5,v $     Last Update: $Date: 2001/11/23 15:20:38 $     Revision: $Revision: 1.4 $
.\"
.\"
.\" Some handy macro definitions [from Tom Christensen's man(1) manual page].
.\"
.de SB		\" small and bold
.if !"\\$1"" \\s-2\\fB\&\\$1\\s0\\fR\\$2 \\$3 \\$4 \\$5
..
.\"
.de T		\" switch to typewriter font
.ft CW		\" probably want CW if you don't have TA font
..
.\"
.de TY		\" put $1 in typewriter font
.if t .T
.if n ``\c
\\$1\c
.if t .ft P
.if n \&''\c
\\$2
..
.\"
.de M		\" man page reference
\\fI\\$1\\fR\\|(\\$2)\\$3
..
.TH COMPLEX 5 "$Date: 2001/11/23 15:20:38 $" "xxRELxx" "xxQS_NAMExx File Formats"
.\"
.SH NAME
complex \- xxQS_NAMExx complexes configuration file format
.\"
.\"
.SH DESCRIPTION
.I Complex
reflects the format of the xxQS_NAMExx complexes configuration.  The
definition of complexes provides all pertinent information
concerning the resource attributes a user may request for a xxQS_NAMExx
job via the
.M qsub 1
\fB\-l\fP option
and for the interpretation of these parameters within the xxQS_NAMExx
system.
.PP
The complexes configuration files should not be accessed directly.
In order to add or modify complexes,
the
.M qconf 1
options \-Ac, \-ac, \-Mc and \-mc should be used instead.
While the \-Ac and \-Mc options take a
.I complex
configuration file as an argument, the \-ac and \-mc options
bring up an editor filled in with a template
.I complex
configuration or the configuration of an existing complex.
.PP
The xxQS_NAMExx complexes object integrates 4 different types of complexes:
.\"
.SS "\fBThe Queue Complex\fP"
It is referenced by the special name "queue".
.sp 1
In its default form it contains a selection of parameters in the
queue configuration as defined in
.M queue_conf 5 .
The queue configuration parameters being requestable for a job
by the user in principal are:
.sp 1
.nf
.RS
qname
hostname
notify
calendar
min_cpu_interval 
tmpdir
seq_no
s_rt
h_rt
s_cpu
h_cpu
s_data
h_data
s_stack
h_stack
s_core
h_core
s_rss
h_rss
.RE
.fi
The queue complex can be extended if further attributes are intended to be 
available for each queue. The queue complex defines the characteristics
(such 
as the data type) of the attributes it contains. A value setting for the
queue 
complex attributes is defined by the queue configuration for each queue in 
case of the standard parameters enlisted above, or by the
.B complex_values 
entry in the queue configuration (see
.M queue_conf 5
for details) if a parameter has been added to the default queue
complex. If no definition for the value in the
.B complex_values
entry of the queue configuration is given in the latter 
case, the value is set as defined by the
.B value
field described below.
.\"
.SS "\fBThe Host Complex\fP"
It is referenced by the special name "host" and
contains the characteristics definition of all attributes which are
intended to 
be managed on a host basis. The standard set of host related attributes
consists 
of two categories, but it may be enhanced like the queue complex as
described 
above. The first category is built by several queue configuration
attributes 
which are particularly suitable to be managed on a host basis. These
attributes 
are:
.sp 1
.nf
.RS
slots
s_vmem
h_vmem
s_fsize
h_fsize
.RE
.fi
(please refer to
.M queue_conf 5
for details).
.sp 1
.B Note:
Defining these attributes in the
host complex is no contradiction to having them also in the queue
configuration. It allows maintaining the corresponding resources on a
host level and at the same time on a queue level. Total virtual free
memory (h_vmem) can be managed for a host, for example, and a subset
of the total amount can be associated with a queue on that host.
.sp 1
The second attribute category in the standard host complex are the default 
load values Every
.M xxqs_name_sxx_execd 8
periodically reports load to
.M xxqs_name_sxx_qmaster 8 .
The reported load values are either the standard xxQS_NAMExx load values
such as the CPU load average (see
.M uptime 1 )
or load values defined by the xxQS_NAMExx administration (see the
.B load_sensor
parameter in the cluster configuration
.M xxqs_name_sxx_conf 5
and the
.I xxQS_NAMExx Installation and Administration Guide
for details).
The characteristics definition for the standard load values is part of
the default host complex, while administrator defined load values
require extension of the host complex. Please refer to the file
<xxqs_name_sxx_root>/doc/load_parameters.asc for detailed information on the
standard set of load values.
.sp 1
The host complex commonly is not only extended to include non-standard
load parameters, but also to manage host related resources such as the
number of software licenses being assigned to a host or the available
disk space on a host local filesystem.
.sp 1
A concrete value for a particular host complex attribute is determined
by either an associated queue configuration in the case of the queue
configuration derived attributes, a reported load value or the explicit
definition of a value in the
.B complex_values
entry of the corresponding host configuration (see 
.M host_conf 5 ).
If none of the above is available (e.g. the value is supposed to 
be a load parameter, but
.M xxqs_name_sxx_execd 8
does not report a load value for it), the 
.B value
field described below is used.
.\"
.SS "\fBThe Global Complex\fP"
It is referenced by the special name "global".
.sp 1
The entries configured in the global complex refer to cluster wide resource 
attributes, such as the number of available "floating" licenses of a 
particular software or the free disk space on a network wide available 
filesystem. Global resource attributes can also be associated with load 
reports, if the corresponding load report contains the "GLOBAL" 
identifier (see the corresponding section in the xxQS_NAMExx Installation 
and Administration Guide for details). Global load values can be reported 
from any host in the cluster. There are no global load values reported by 
xxQS_NAMExx by default and hence there is no default global complex 
configuration.
.sp 1
Concrete values for global complex attributes are either determined by 
global load reports or by explicit definition in the
.B complex_values 
parameter of the "global" host configuration (see
.M host_conf 5 ).
If none of both is present (e.g. a load value has not yet been reported) the
.B value
field described below is used.
.SS "\fBUser Defined Complexes\fP"
By setting up user defined complexes the xxQS_NAMExx administration has 
the ability to extend the set of attributes managed by xxQS_NAMExx while 
restricting the influence of those attributes to particular queues and/or
hosts. A 
user complex is just a named collection of attributes and the corresponding 
definition as to how these attributes are to be handled by xxQS_NAMExx. 
One or more of these user defined complexes can be attached to a queue and/
or host via the
.B complex_list
queue and host configuration parameter (see 
.M queue_conf 5
and
.M host_conf 5 ).
The attributes defined in all assigned 
complexes become available to the queue and the host respectively in
addition to the default complex attributes.
.sp 1
Concrete values for user defined complexes have to be set by the 
.B complex_values
parameter in the queue and host configuration or otherwise the
.B value
field described below is used.
.\"
.\"
.SH FORMAT
The principal format of a 
.I complex
configuration is that of a tabulated list. Each line starting with
a '#' character is a comment line. Each line despite comment lines
define one element of the complex. A element definition line
consists of the following 6 column entries per line (in the order
of appearance):
.SS "\fBname\fP"
The name of the complex element to be used to request this attribute
for a job in the
.M qsub 1
\fB\-l\fP option. An attribute
.B name
may appear only once across all 
complexes, i.e. the complex attribute definition is unique.
.SS "\fBshortcut\fP"
A shortcut for \fBname\fP which may also be used to request this
attribute for a job in the
.M qsub 1
\fB\-l\fP option. An attribute
.B shortcut
may appear only once across 
all complexes, so as to avoid the possibility of ambiguous complex attribute 
references.
.\"
.SS "\fBtype\fP"
This setting determines how the corresponding values are to be treated 
xxQS_NAMExx internally in case of comparisons or in case of load scaling for 
the load complex entries:
.IP "\(bu" 3n
With \fBINT\fP only raw integers are allowed.
.IP "\(bu" 3n
With \fBDOUBLE\fP floating point numbers in double precision (decimal and
scientific notation) can be specified.
.IP "\(bu" 3n
With \fBTIME\fP time specifiers are allowed. Refer to 
.M queue_conf 5  
for a format description.
.IP "\(bu" 3n
With \fBMEMORY\fP memory size specifiers are allowed. Refer to 
.M queue_conf 5 
for a format description.
.IP "\(bu" 3n
With \fBBOOL\fP the strings TRUE and FALSE are allowed. When used in a 
load formula (refer to 
.M sched_conf 5
)
TRUE and FALSE get mapped into '1' and '0'.
.IP "\(bu" 3n
With \fBSTRING\fP all strings are allowed and
.M strcmp 3
is used for comparisons.
.IP "\(bu" 3n
\fBCSTRING\fP is like \fBSTRING\fP except comparisons are case insensitive. 
.IP "\(bu" 3n
\fBHOST\fP is like \fBCSTRING\fP but the string must be a valid hostname.   
.\"
.SS "\fBvalue\fP"
The
.B value
field is a pre-defined value setting for an attribute, which only has 
an effect if it is not overwritten while attempting to determine a concrete 
value for the attribute with respect to a queue, a host or the xxQS_NAMExx 
cluster. The value field can be overwritten by
.IP "\(bu" 3n
the queue configuration values of a referenced queue.
.IP "\(bu" 3n
host specific and cluster related load values.
.IP "\(bu" 3n
explicit specification of a value via the complex_values parameter in the 
queue or host configuration (see
.M queue_conf 5
and
.M host_conf 5
for details.
.PP
If none of above is applicable, value is set for the attribute.
.\"
.SS "\fBrelop\fP"
The
.B relation operator.
The relation operator is used when the value requested by the user for
this parameter is compared against the corresponding value configured for
the considered queues. If the result of the comparison is false, the
job cannot run in this queue. Possible relation operators are "==", "<",
">", "<=" and ">=". The only valid operator for string type attributes
is "==".
.SS "\fBrequestable\fP"
The entry can be used in a
.M qsub 1
resource request if this field is set to 'y' or 'yes'.
If set to 'n' or 'no' this entry cannot be used by a
user in order to request a queue or a class of queues.
If the entry is set to 'forced' or 'f' the 
attribute has to be requested by a job or it is rejected.
.SS "\fBconsumable\fP"
The
.B consumable
parameter can be set to either 'yes' ('y' abbreviated) or 'no' 
('n'). It can be set to 'yes' only for numeric attributes (INT, MEMORY,
TIME - see
.B type
above). If set to 'yes' the 
consumption of the corresponding resource can be managed by 
xxQS_NAMExx internal bookkeeping. In this case xxQS_NAMExx accounts 
for the consumption of this resource for all running jobs and ensures that jobs 
are only dispatched if the xxQS_NAMExx internal bookkeeping indicates 
enough available consumable resources. Consumables are an efficient means to 
manage limited resources such a available memory, free space on a file 
system, network bandwidth or floating software licenses.
.sp 1
Consumables can be combined with default or user defined load parameters 
(see
.M xxqs_name_sxx_conf 5
and
.M host_conf 5 ),
i.e. load values can be reported 
for consumable attributes or the consumable flag can be set for load 
attributes. The xxQS_NAMExx consumable resource management takes both 
the load (measuring availability of the resource) and the internal bookkeeping 
into account in this case, and makes sure that neither of both exceeds a given 
limit.
.sp 1
To enable consumable resource management the basic availability of a 
resource has to be defined. This can be done on a cluster global, per host and 
per queue basis while these categories may supersede each other in the given 
order (i.e. a host can restrict availability of a cluster resource and a
queue can restrict host and cluster resources). The definition of resource
availability is performed with the
.B complex_values
entry in
.M host_conf 5
and
.M queue_conf 5 . 
The
.B complex_values
definition of the "global" host specifies cluster global 
consumable settings. To each consumable complex attribute in a 
.B complex_values
list a value is assigned which denotes the maximum 
available amount for that resource. The internal bookkeeping will subtract 
from this total the assumed resource consumption by all running jobs as 
expressed through the jobs' resource requests.
.sp 1
.B Note:
Jobs can be forced to request a resource and thus to specify their 
assumed consumption via the 'force' value of the
.B requestable 
parameter (see above).
.sp 1
.B Note also:
A default resource consumption value can be pre-defined by the 
administrator for consumable attributes not explicitly requested by 
the job (see the
.B default
parameter below). This is meaningful only if 
requesting the attribute is not enforced as explained above.
.sp 1
See the
.I xxQS_NAMExx Installation and Administration Guide
for examples 
on the usage of the consumable resources facility.
.SS "\fBdefault\fP"
Meaningful only for consumable complex attributes (see
.B consumable
parameter above). xxQS_NAMExx assumes the resource amount denoted in the 
.B default
parameter implicitly to be consumed by jobs being dispatched to a 
host or queue managing the consumable attribute. Jobs explicitly requesting 
the attribute via the \fI\-l\fP option to
.M qsub 1
override this default value.
.\"
.\"
.SH "SEE ALSO"
.M xxqs_name_sxx_intro 1 ,
.M qconf 1 ,
.M qsub 1 ,
.M uptime 1 ,
.M host_conf 5 ,
.M queue_conf 5 ,
.M xxqs_name_sxx_execd 8 ,
.M xxqs_name_sxx_qmaster 8 ,
.M xxqs_name_sxx_schedd 8 ,
.br
.I xxQS_NAMExx Installation and Administration Guide.
.\"
.SH "COPYRIGHT"
See
.M xxqs_name_sxx_intro 1
for a full statement of rights and permissions.
