'\" t
.\"___INFO__MARK_BEGIN__
.\"
.\" Copyright: 2001 by Sun Microsystems, Inc.
.\"
.\"___INFO__MARK_END__
.\" $RCSfile: project.5,v $     Last Update: $Date: 2001/07/20 08:19:15 $     Revision: $Revision: 1.3 $
.\"
.\"
.\" Some handy macro definitions [from Tom Christensen's man(1) manual page].
.\"
.de SB		\" small and bold
.if !"\\$1"" \\s-2\\fB\&\\$1\\s0\\fR\\$2 \\$3 \\$4 \\$5
..
.\"
.de T		\" switch to typewriter font
.ft CW		\" probably want CW if you don't have TA font
..
.\"
.de TY		\" put $1 in typewriter font
.if t .T
.if n ``\c
\\$1\c
.if t .ft P
.if n \&''\c
\\$2
..
.\"
.de M		\" man page reference
\\fI\\$1\\fR\\|(\\$2)\\$3
..
.TH PROJECT 5 "$Date: 2001/07/20 08:19:15 $" "xxRELxx" "xxQS_NAMExx File Formats"
.\"
.SH NAME
project \- xxQS_NAME_EExx project entry file format
.\"
.SH DESCRIPTION
The project object is only available in case of a xxQS_NAME_EExx system. xxQS_NAMExx has
no project object.
.PP
Jobs can be submitted to projects in xxQS_NAME_EExx and a project can be assigned
with a certain level of importance via the functional or the override
policy. This level of importance is then inherited by the jobs executing
under that project.
.PP
A list of currently configured projects can be displayed via the
.M qconf 1
\fB\-sprjl\fP option. The contents of each enlisted project definition
can be shown via the \fB\-sprj\fP switch. The output follows the
.I project
format description. New projects can be created and existing can be
modified via the \fB\-aprj\fP, \fB\-mprj\fP and \fB\-dprj\fP options to
.M qconf 1 .
.\"
.\"
.SH FORMAT
A project definition contains the following parameters:
.IP "\fBname\fP"
The project name.
.IP "\fBoticket\fP"
The amount of override tickets currently assigned to the project.
.IP "\fBfshare\fP"
The current functional share of the project.
.IP "\fBfacl\fP"
A list of user access lists (ACLs - see
.M access_list 5 )
referring to those users being allowed to submit jobs to the project.
.IP "\fBfxacl\fP"
A list of user access lists (ACLs - see
.M access_list 5 )
referring to those users being not allowed to submit jobs to the project.
.\"
.\"
.SH "SEE ALSO"
.M xxqs_name_sxx_intro 1 ,
.M qconf 1 ,
.M access_list 5 .
.\"
.SH "COPYRIGHT"
See
.M xxqs_name_sxx_intro 1
for a full statement of rights and permissions.
