'\" t
.\"___INFO__MARK_BEGIN__
.\" 
.\" 
.\"  The Contents of this file are made available subject to the terms of
.\"  the Sun Industry Standards Source License Version 1.2
.\" 
.\"  Sun Microsystems Inc., March, 2001
.\" 
.\" 
.\"  Sun Industry Standards Source License Version 1.2
.\"  =================================================
.\"  The contents of this file are subject to the Sun Industry Standards
.\"  Source License Version 1.2 (the "License"); You may not use this file
.\"  except in compliance with the License. You may obtain a copy of the
.\"  License at http://www.gridengine.sunsource.net/license.html
.\" 
.\"  Software provided under this License is provided on an "AS IS" basis,
.\"  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
.\"  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
.\"  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
.\"  See the License for the specific provisions governing your rights and
.\"  obligations concerning the Software.
.\" 
.\"  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
.\" 
.\"  Copyright: 2001 by Sun Microsystems, Inc.
.\" 
.\"  All Rights Reserved.
.\" 
.\" 
.\"___INFO__MARK_END__
.\" $RCSfile: sched_conf.5,v $     Last Update: $Date: 2001/07/19 15:55:36 $     Revision: $Revision: 1.2 $
.\"
.\"
.\" Some handy macro definitions [from Tom Christensen's man(1) manual page].
.\"
.de SB		\" small and bold
.if !"\\$1"" \\s-2\\fB\&\\$1\\s0\\fR\\$2 \\$3 \\$4 \\$5
..
.\"
.de T		\" switch to typewriter font
.ft CW		\" probably want CW if you don't have TA font
..
.\"
.de TY		\" put $1 in typewriter font
.if t .T
.if n ``\c
\\$1\c
.if t .ft P
.if n \&''\c
\\$2
..
.\"
.de M		\" man page reference
\\fI\\$1\\fR\\|(\\$2)\\$3
..
.TH SCHED_CONF 5 "$Date: 2001/07/19 15:55:36 $" "xxRELxx" "xxQS_NAMExx File Formats"
.\"
.SH NAME
sched_conf \- xxQS_NAMExx default scheduler configuration file
.\"
.\"
.SH DESCRIPTION
.I sched_conf
defines the configuration file format for xxQS_NAMExx's default 
scheduler provided by
.M xxqs_name_sxx_schedd 8 .
In order to modify the configuration, 
use the graphical user's interface
.M qmon 1
or the
.I -msconf
option of the 
.M qconf 1
command. A default configuration is provided together with the 
xxQS_NAMExx distribution package.
.\"
.\"
.SH FORMAT
The following parameters are recognized by the xxQS_NAMExx scheduler if
present in \fIsched_conf\fP:
.SS "\fBalgorithm\fP"
Allows for the selection of alternative scheduling algorithms.
.PP
Currently
.B default
is the only allowed setting.
.\"
.SS "\fBload_formula\fP"
A simple algebraic expression used to derive a single weighted
load value from all or part of the load parameters reported by
.M xxqs_name_sxx_execd 8
for each host and from all or part of the consumable resources (see
.M complex 5 )
being maintained for each host.
The load formula expression syntax is that of
a summation weighted load values, that is:
.sp 1
.nf
.RS
load_val1[*w1][{+|-}load_val2[*w2][{+|-}...]]
.RE
.fi
.sp 1
\fBNote\fP, no blanks are allowed in the load formula.
.br
The load values and consumable resources (load_val1, ...)
are specified by the name defined in the complex (see
.M complex 5 ).
.br
.B Note:
Administrator defined load values (see the
.B load_sensor
parameter in
.M xxqs_name_sxx_conf 5
for details)
and consumable resources available for all hosts (see
.M complex 5 )
may be used as well as xxQS_NAMExx default load parameters.
.br
The weighting factors (w1, ...) are positive integers. After the expression
is evaluated for each host the results are assigned to the hosts and
are used to sort the hosts corresponding to the weighted load. The sorted
host list is used to sort queues subsequently.
.br
The default load formula is "load_avg".
.SS "\fBjob_load_adjustments\fP"
The load, which is imposed by the xxQS_NAMExx jobs 
running on a system varies in time, and often, e.g. for the CPU load, 
requires some amount of time to be reported in the appropriate 
quantity by the operating system. Consequently, if a job was started 
very recently, the reported load may not provide a sufficient 
representation of the load which is already imposed on that host by 
the job. The reported load will adapt to the real load over time, but 
the period of time, in which the reported load is too low, may 
already lead to an oversubscription of that host. xxQS_NAMExx allows 
the administrator to specify \fBjob_load_adjustments\fP which are used 
in the xxQS_NAMExx scheduler to compensate for this problem.
.br
The \fBjob_load_adjustments\fP are specified as a comma separated list
of arbitrary load parameters or consumable resources and (separated by an
equal sign) an
associated load correction value. Whenever a job is dispatched to a
host by
.M xxqs_name_sxx_schedd 8 ,
the load parameter and consumable value set of that host
is increased by the values
provided in the \fBjob_load_adjustments\fP list. These correction
values are decayed linearly over time until after 
\fBload_adjustment_decay_time\fP from the start the corrections
reach the value 0.
If the \fBjob_load_adjustments\fP
list is assigned the special denominator NONE, no load corrections are
performed.
.br
The adjusted load and consumable values are used to compute the
combined and weighted
load of the hosts with the \fBload_formula\fP (see above) and to compare
the load and consumable values against the load threshold lists
defined in the queue configurations (see
.M queue_conf 5 ).
If your \fBload_formula\fP simply consists of the CPU load average parameter
\fIload_avg\fP and if your jobs are very compute intensive, you might
want to set the \fBjob_load_adjustments\fP list to \fIload_avg=100\fP,
which means that every new job dispatched to a host will require
100 % CPU time and thus the machine's load is instantly raised by 100.
.SS "\fBload_adjustment_decay_time\fP"
The load corrections in the "\fBjob_load_adjustments\fP" list above
are decayed linearly over time from the point of the job start, where
the corresponding load or consumable parameter is
raised by the full correction value,
until after a time period of "\fBload_adjustment_decay_time\fP", where the
correction becomes 0. Proper values for "\fBload_adjustment_decay_time\fP"
greatly depend upon the load or consumable parameters used and the
specific operating
system(s). Therefore, they can only be determined on-site and experimentally.
For the default \fIload_avg\fP load parameter a
"\fBload_adjustment_decay_time\fP" of 7 minutes has proven to yield reasonable
results.
.SS "\fBmaxujobs\fP"
The maximum number of jobs any user may have running in a xxQS_NAMExx
cluster at the same time. If set to 0 (default) the users may run an arbitrary
number of jobs. If the \fBuser_sort\fP scheduling policy is active (see
below) the scheduler allows at the most \fBmaxujobs\fP in 
each priority group
.sp 1
The \fBmaxujobs\fP parameter has no effect in a xxQS_NAME_EExx system. xxQS_NAME_EExx provides
more sophisticated means to control share entitlement.
.SS "\fBmaxgjobs\fP"
Not implemented yet. Provided for later extension.
.SS "\fBschedule_interval\fP"
At the time
.M xxqs_name_sxx_schedd 8
initially registers to
.M xxqs_name_sxx_qmaster 8
\fBschedule_interval\fP is used to set the time interval in which
.M xxqs_name_sxx_qmaster 8
sends scheduling event updates to
.M xxqs_name_sxx_schedd 8 .
A scheduling event is a status change that has occurred within
.M xxqs_name_sxx_qmaster 8
which may trigger or affect scheduler decisions (e.g. a job has
finished and thus the allocated resources are available again).
.br
In the xxQS_NAMExx default scheduler the arrival of
a scheduling event report triggers a scheduler run. The scheduler
waits for event reports otherwise.
.br
\fBSchedule_interval\fP is a time value (see
.M queue_conf 5
for a definition of the syntax of time values).
.SS "\fBuser_sort\fP"
xxQS_NAMExx usually schedules user jobs corresponding to a first-come-first-served
policy. In case a user submits a large amount of jobs in very short time,
this can lead to a rather unfair situation, because all users submitting
afterwards are blocked until most of the first user's jobs are completed.
Therefore, xxQS_NAMExx allows to change this policy to the so called
equal share sort: As soon as a user has a job running his other jobs
are sorted to the end of the pending jobs list. Thus, the first jobs of all
other users have comparable chances to find a queue. \fBNote:\fP The
equal share sort only applies within the same job priority category
(refer to the \fImp\fP option of the
.M qsub 1
and
.M qalter 1
commands for more information).
.PP
The default for \fBuser_sort\fP is \fBFALSE\fP.
.\"
.SS "\fBqueue_sort_method\fP"
If this parameter is set to \fBseqno\fP, xxQS_NAMExx will use the
.B seq_no
parameter as configured in the current queue configurations (see
.M queue_conf 5 )
as first criterion to produce a sorted queue list. The 
.B load_formula
(see above) has only a meaning if two queues have equal
sequence numbers.
If 
.B queue_sort_method
is set to \fBload\fP the load according the 
.B load_formula
is the first criterion and the sequence number is only used if two 
hosts have the same load. 
The sequence number sorting is most 
useful if you want to define a fixed order in which queues are to be filled
(e.g.   the cheapest resource first).
.PP
The default for this parameter is \fBload\fP.
.\"
.SS "\fBsgeee_schedule_interval\fP"
This parameter is only available in a xxQS_NAME_EExx system. xxQS_NAME_Cxx does not support
this parameter.
.PP
The time period between job priority adjustments by the xxQS_NAME_EExx global
dynamic scheduler (GDS). Valid values are specified of type time as
specified in
.M queue_conf 5 .
.\"
.SS "\fBhalftime\fP"
This parameter is only available in a xxQS_NAME_EExx system. xxQS_NAME_Cxx does not support
this parameter.
.PP
When executing under a share based policy, xxQS_NAME_EExx "ages" (i.e. decreases)
usage to implement a sliding window for achieving the share entitlements
as defined by the share tree. The \fBhalftime\fP defines
the time interval in which accumulated usage will have been decayed
to half its original value. Valid values are specified of type time as
specified in
.M queue_conf 5 .
.\"
.SS "\fBusage_weight_list\fP"
This parameter is only available in a xxQS_NAME_EExx system. xxQS_NAME_Cxx does not support
this parameter.
.PP
xxQS_NAME_EExx accounts for the consumption of the resources CPU-time, memory and IO
to determine the usage which is imposed on a system by a job. A single
usage value is computed from these three input parameters by multiplying
the individual values by weights and adding them up. The weights are
defined in the \fBusage_weight_list\fP. The format of the list is
.sp 1
.nf
.RS
cpu=wcpu,mem=wmem,io=wio
.RE
.fi
.sp 1
where wcpu, wmem and wio are the configurable weights. The weights are real
number. The sum of all tree weights should be 1.
.\"
.SS "\fBcompensation_factor\fP"
This parameter is only available in a xxQS_NAME_EExx system. xxQS_NAME_Cxx does not support
this parameter.
.PP
Determines how fast xxQS_NAME_EExx should compensate for past usage below of above
the share entitlement defined in the share tree. Recommended values are
between 2 and 10, where 10 means faster compensation.
.\"
.SS "\fBweight_user\fP"
This parameter is only available in a xxQS_NAME_EExx system. xxQS_NAME_Cxx does not support
this parameter.
.PP
The relative importance of the user shares in the functional policy.
Values are of type real.
.\"
.SS "\fBweight_project\fP"
This parameter is only available in a xxQS_NAME_EExx system. xxQS_NAME_Cxx does not support
this parameter.
.PP
The relative importance of the project shares in the functional policy.
Values are of type real.
.\"
.SS "\fBweight_jobclass\fP"
This parameter is only available in a xxQS_NAME_EExx system. xxQS_NAME_Cxx does not support
this parameter.
.PP
The relative importance of the job class (i.e. queue) shares in the
functional policy. Values are of type real.
.\"
.SS "\fBweight_department\fP"
This parameter is only available in a xxQS_NAME_EExx system. xxQS_NAME_Cxx does not support
this parameter.
.PP
The relative importance of the department shares in the
functional policy. Values are of type real.
.\"
.SS "\fBweight_job\fP"
This parameter is only available in a xxQS_NAME_EExx system. xxQS_NAME_Cxx does not support
this parameter.
.PP
The relative importance of the job shares in the
functional policy. Values are of type real.
.\"
.SS "\fBweight_tickets_functional\fP"
This parameter is only available in a xxQS_NAME_EExx system. xxQS_NAME_Cxx does not support
this parameter.
.PP
The maximum number of functional tickets available for distribution
by xxQS_NAME_EExx. Determines the relative importance of the functional policy.
.\"
.SS "\fBweight_tickets_share\fP"
This parameter is only available in a xxQS_NAME_EExx system. xxQS_NAME_Cxx does not support
this parameter.
.PP
The maximum number of share based tickets available for distribution
by xxQS_NAME_EExx. Determines the relative importance of the share tree policy.
.\"
.SS "\fBweight_deadline\fP"
This parameter is only available in a xxQS_NAME_EExx system. xxQS_NAME_Cxx does not support
this parameter.
.PP
The maximum number of deadline tickets available for distribution
by xxQS_NAME_EExx. Determines the relative importance of the deadline policy.
.\"
.SS "\fBschedd_job_info\fP"
The default scheduler can keep track why jobs could not be scheduled during
the last scheduler run. This parameter enables or disables the observation.
The value \fBtrue\fP enables the monitoring \fBfalse\fP turns it off.
.PP
It is also possible to activate the observation only for certain jobs. This
will be done if the parameter is set to \fBjob_list\fP followed by a comma 
separated list of job ids.
.PP
The user can obtain the collected information with the command qstat -j.
.\"
.\"
.SH FILES
.nf
.ta \w'<xxqs_name_sxx_root>/'u
\fI<xxqs_name_sxx_root>/<cell>/common/sched_configuration\fP
	xxqs_name_sxx_schedd configuration
.fi
.\"
.\"
.SH "SEE ALSO"
.M xxqs_name_sxx_intro 1 ,
.M qalter 1 ,
.M qconf 1 ,
.M qstat 1 ,
.M qsub 1 ,
.M complex 5 ,
.M queue_conf 5 ,
.M xxqs_name_sxx_execd 8 ,
.M xxqs_name_sxx_qmaster 8 ,
.M xxqs_name_sxx_schedd 8 .
.I xxQS_NAMExx Installation and Administration Guide
.\"
.SH "COPYRIGHT"
See
.M xxqs_name_sxx_intro 1
for a full statement of rights and permissions.
