'\" t
.\"___INFO__MARK_BEGIN__
.\"
.\" Copyright: 2004 by Sun Microsystems, Inc.
.\"
.\"___INFO__MARK_END__
.\" $RCSfile: sge_qstat.5,v $     Last Update: $Date: 2004/10/13 11:59:48 $     Revision: $Revision: 1.1 $
.\"
.\"
.\" Some handy macro definitions [from Tom Christensen's man(1) manual page].
.\"
.de SB		\" small and bold
.if !"\\$1"" \\s-2\\fB\&\\$1\\s0\\fR\\$2 \\$3 \\$4 \\$5
..
.\"
.de T		\" switch to typewriter font
.ft CW		\" probably want CW if you don't have TA font
..
.\"
.de TY		\" put $1 in typewriter font
.if t .T
.if n ``\c
\\$1\c
.if t .ft P
.if n \&''\c
\\$2
..
.\"
.de M		\" man page reference
\\fI\\$1\\fR\\|(\\$2)\\$3
..
.TH xxQS_NAME_Sxx_REQUEST 5 "$Date: 2004/10/13 11:59:48 $" "xxRELxx" "xxQS_NAMExx File Formats"
.\"
.SH NAME
sge_qstat \- xxQS_NAMExx default qstat file format
.\"
.\"
.SH DESCRIPTION
.I sge_qstat
defines the commandline switches, which will be used by qstat per default.
If available, the default sge_qstat file is read and processed by 
.M qstat 1 .
.PP
There is a cluster global and a user private sge_qstat file. The user private
file has the highest precedence and is  followed by the cluster global 
sge_qstat file. Commandline switches used with 
.M qstat 1
overwrite all switches contained in user private or cluster global 
sge_qstat file.
.PP
.\"
.\"
.\"
The format of the default files is:
.\"
.\"
.IP "\(bu" 3n
Each line has to contain any
.M qstat 1
option as described in
the xxQS_NAMExx Reference Manual. More than one option per line is
allowed. 
.\"
.\"
.\"
.SH "EXAMPLES"
.PP
The following is a simple example of a default sge_qstat file:
.PP
.nf

=====================================================
-s rs -u $user
=====================================================

.fi
.PP
Having defined a default sge_qstat file like this and using qstat 
as follows:
.PP
.nf
qstat 
.fi
.PP
has the same effect as if qstat was executed with:
.PP
.nf
qsub -p rs -u <current_user>
.fi
.PP
.\"
.\"
.\"
.SH "FILES"
.nf
.ta \w'<xxqs_name_sxx_root>/   'u
\fI<xxqs_name_sxx_root>/<cell>/common/sge_request\fP global defaults file
.ta \w'$HOME/.sge_request   'u
\fI$HOME/.sge_request\fP	user private defaults file
.fi
.\"
.\"
.\"
.SH "SEE ALSO"
.M xxqs_name_sxx_intro 1 ,
.M qstat 1 ,
.I xxQS_NAMExx Installation and Administration Guide
.\"
.SH "COPYRIGHT"
See
.M xxqs_name_sxx_intro 1
for a full statement of rights and permissions.
