'\" t
.\"___INFO__MARK_BEGIN__
.\"
.\" Copyright: 2001 by Sun Microsystems, Inc.
.\"
.\"___INFO__MARK_END__
.\" $RCSfile: sge_conf.5,v $     Last Update: $Date: 2002/03/06 10:11:11 $     Revision: $Revision: 1.11.2.1 $
.\"
.\"
.\" Some handy macro definitions [from Tom Christensen's man(1) manual page].
.\"
.de SB		\" small and bold
.if !"\\$1"" \\s-2\\fB\&\\$1\\s0\\fR\\$2 \\$3 \\$4 \\$5
..
.\"
.de T		\" switch to typewriter font
.ft CW		\" probably want CW if you don't have TA font
..
.\"
.de TY		\" put $1 in typewriter font
.if t .T
.if n ``\c
\\$1\c
.if t .ft P
.if n \&''\c
\\$2
..
.\"
.de M		\" man page reference
\\fI\\$1\\fR\\|(\\$2)\\$3
..
.TH xxQS_NAME_Sxx_CONF 5 "$Date: 2002/03/06 10:11:11 $" "xxRELxx" "xxQS_NAMExx File Formats"
.\"
.SH NAME
xxqs_name_sxx_conf \- xxQS_NAMExx configuration files
.\"
.\"
.SH DESCRIPTION
.I xxqs_name_sxx_conf
defines the global and local xxQS_NAMExx configurations and can be
shown/modified by
.M qconf 1
using the \-sconf/\-mconf options. Only root or the cluster administrator may
modify
.I xxqs_name_sxx_conf.
.PP
At its initial start-up,
.M xxqs_name_sxx_qmaster 8
checks to see if a valid xxQS_NAMExx configuration is available at a
well known location in the xxQS_NAMExx internal directory hierarchy.
If so, it loads that configuration information and proceeds.
If not,
.M xxqs_name_sxx_qmaster 8
writes a generic configuration containing default values to that same
location.
The xxQS_NAMExx execution daemons
.M xxqs_name_sxx_execd 8
upon start-up retrieve their configuration from
.M xxqs_name_sxx_qmaster 8 .
.PP
The actual configuration for both
.M xxqs_name_sxx_qmaster 8
and
.M xxqs_name_sxx_execd 8
is a superposition of a so called \fIglobal\fP configuration and
a \fIlocal\fP configuration being pertinent for the host on which
a master or execution daemon resides.
If a local configuration is available, its entries overwrite the
corresponding entries of the global configuration. \fBNote:\fP The local
configuration does not have to contain all valid configuration entries,
but only those which need to be modified against the global entries.
.\"
.\"
.SH FORMAT
.\"
The paragraphs that follow provide brief descriptions of the individual
parameters that compose the global and local configurations for a
xxQS_NAMExx cluster:
.\"
.SH "\fBqmaster_spool_dir\fP"
The location where the master spool directory resides. Only the
.M xxqs_name_sxx_qmaster 8
and 
.M xxqs_name_sxx_shadowd 8
need to have access to this directory. It needs read/write permission for
root, however. The master spool directory \- in particular the jobs
directory and the message
log file \- may become quite large depending on the size of the
cluster and the number of jobs. Be sure to allocate enough disk space
and regularly clean off the log files, e.g. via a
.M cron 8
job.
.PP
Being a parameter set at installation time changing \fBqmaster_spool_dir\fP
in a running system is not supported.
.PP
The default location for the
master spool directory is <xxqs_name_sxx_root>/<cell>/spool/qmaster.
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBexecd_spool_dir\fP"
The execution daemon spool directory path. Again, a feasible spool
directory requires read/write access permission for root. The entry in
the global configuration for this parameter can be overwritten by
execution host local configurations, i.e. each
.M xxqs_name_sxx_execd 8
may have a private spool directory with a different path, in which case
it needs to provide read/write permission for the root account of the
corresponding execution host only.
.PP
Under \fBexecd_spool_dir\fP a directory named corresponding
to the unqualified hostname of the execution host is opened and
contains all information spooled to disk. Thus, it is possible for the
\fBexecd_spool_dir\fPs of all execution hosts to physically reference the
same directory path
(the root access restrictions mentioned above need to be met, however).
.PP
Being a parameter set at installation time changing the global \fBexecd_spool_dir\fP
in a running system is not supported.
.PP
The default location for the execution daemon spool
directory is <xxqs_name_sxx_root>/<cell>/spool.
.PP
The global configuration entry for this value
may be overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBbinary_path\fP"
The directory path where the xxQS_NAMExx binaries reside. It is used within
xxQS_NAMExx components to locate and startup other xxQS_NAMExx programs.
.PP
The path name given here is searched for binaries as well as any directory
below with a directory name equal to the current operating system
architecture. Therefore, /usr/xxQS_NAME_Sxx/bin will work for all architectures,
if the corresponding binaries are located in subdirectories named aix43,
cray, glinux, hp10, irix6, osf4, solaris, etc.
.PP
Each
.M xxqs_name_sxx_execd 8
may have its private binary path.
Changing the binary path will have immediate effect for 
.M xxqs_name_sxx_execd 8 .
.PP
The default location for the binary path is
<xxqs_name_sxx_root>/bin
.PP
The global configuration entry for this value
may be overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBmailer\fP"
\fBmailer\fP is the absolute pathname to the electronic mail delivery
agent on your system. It must accept the following syntax:
.PP
.RS
mailer -s <subject-of-mail-message> <recipient>
.RE
.PP
Each
.M xxqs_name_sxx_execd 8
may use a private mail agent. Changing \fBmailer\fP will take
immediate effect.
.PP
The default for \fBmailer\fP depends on the operating system of
the host on which the xxQS_NAMExx master installation was run. Common
values are /bin/mail or /usr/bin/Mail.
.PP
The global configuration entry for this value
may be overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBxterm\fP"
.B xterm
is the absolute pathname to the X Window System terminal emulator,
.M xterm 1 .
.PP
Each
.M xxqs_name_sxx_execd 8
may use a private mail agent. Changing \fBxterm\fP will take
immediate effect.
.PP
The default for \fBxterm\fP is /usr/bin/X11/xterm.
.PP
The global configuration entry for this value
may be overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBload_sensor\fP"
A comma separated list of executable shell script paths or programs
to be started by
.M xxqs_name_sxx_execd 8
and to be used in order to retrieve site configurable load information
(e.g. free space on a certain disk partition).
.PP
Each
.M xxqs_name_sxx_execd 8
may use a set of private 
.B load_sensor
programs or scripts. Changing
.B load_sensor
will take effect after two load report intervalls (see
\fBload_report_time\fB). A load sensor will be restarted automatically if
the file modification time of the load sensor executable changes.
.PP
The global configuration entry for this value
may be overwritten by the execution host local configuration.
.PP
In addition to the load sensors configured via
\fBload_sensor\fP,
.M xxqs_name_sxx_exec 8
searches for an executable file named
.I qloadsensor
in the execution host's xxQS_NAMExx binary directory path.
If such a file is found, it is treated like the configurable load sensors
defined in \fBload_sensor\fP. This facility is intended for pre-installing
a default load sensor.
.\"
.\"
.SH "\fBprolog\fP"
The executable path of a shell script that is started before execution
of xxQS_NAMExx jobs with the same environment setting as that for the
xxQS_NAMExx
jobs to be started afterwards. 
An optional prefix "user@" specifies the user under which this procedure
is to be started.
This procedure is intended as a means
for the xxQS_NAMExx administrator to automate the execution of general site
specific tasks like the preparation of temporary file systems with the
need for the same context information as the job.
Each
.M xxqs_name_sxx_execd 8
may use a private prologue script. 
Correspondingly, the execution host local 
configurations is can be overwritten by the queue configuration (see
.M queue_conf 5
). 
Changing \fBprolog\fP will take
immediate effect.
.PP
\fBNote:\fP \fBprolog\fP is executed \fIexactly\fP as the job script.
Therefore, all implications described under the parameters
\fBshell_start_mode\fP and \fBlogin_shells\fP below apply.
.PP
The default for \fBprolog\fP is the special value NONE, which prevents
from execution of a prologue script. 
.PP
The following special
variables being expanded at runtime can be used (besides any other
strings which have to be interpreted by the procedure) to constitute 
a command line:
.IP "\fI$host\fP"
The name of the host on which the prolog or epilog procedures are
started.
.IP "\fI$job_owner\fP"
The user name of the job owner.
.IP "\fI$job_id\fP"
xxQS_NAMExx's unique job identification number.
.IP "\fI$job_name\fP"
The name of the job.
.IP "\fI$processors\fP"
The \fBprocessors\fP string as contained in the queue configuration
(see
.M queue_conf 5 )
of the master queue (the queue in which the prolog and epilog procedures
are started).
.IP "\fI$queue\fP"
The master queue, i.e. the queue in which the prolog and epilog procedures
are started.
.PP
The global configuration entry for this value
may be overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBepilog\fP"
The executable path of a shell script that is started after execution
of xxQS_NAMExx jobs with the same environment setting as that for the
xxQS_NAMExx
jobs that has just completed. An optional prefix "user@" specifies the 
user under which this procedure is to be started.
This procedure is intended as a means
for the xxQS_NAMExx administrator to automate the execution of general site
specific tasks like the cleaning up of temporary file systems with the
need for the same context information as the job.
Each
.M xxqs_name_sxx_execd 8
may use a private epilogue script. 
Correspondingly, the execution host local 
configurations is can be overwritten by the queue configuration (see
.M queue_conf 5
).
Changing \fBepilog\fP will take
immediate effect.
.PP
\fBNote:\fP \fBepilog\fP is executed \fIexactly\fP as the job script.
Therefore, all implications described under the parameters
\fBshell_start_mode\fP and \fBlogin_shells\fP below apply.
.PP
The default for \fBepilog\fP is the special value NONE, which prevents
from execution of a epilogue script.
The  same  special variables as for \fBprolog\fP can be
used to constitute a command line.
.PP
The global configuration entry for this value
may be overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBshell_start_mode\fP"
This parameter defines the mechanisms which are used to actually
invoke the job scripts on the execution hosts. The following
values are recognized:
.IP \fIunix_behavior\fP
If a user starts a job shell script under UNIX interactively by
invoking it just with the script name the operating system's executable
loader uses the information provided in a comment such as `#!/bin/csh' in
the first line of the script to detect which command interpreter to
start to interpret the script. This mechanism is used by xxQS_NAMExx when
starting jobs if \fIunix_behavior\fP is defined as \fBshell_start_mode\fP.
.\"
.IP \fIposix_compliant\fP
POSIX does not consider first script line comments such a `#!/bin/csh'
as being significant. The POSIX standard for batch queuing systems
(P1003.2d) therefore requires a compliant queuing system to ignore
such lines but to use user specified or configured default command
interpreters instead. Thus, if \fBshell_start_mode\fP is set to
\fIposix_compliant\fP xxQS_NAMExx will either use the command interpreter
indicated by the \fB\-S\fP option of the
.M qsub 1
command or the \fBshell\fP parameter of the queue to be used (see
.M queue_conf 5
for details).
.\"
.IP \fIscript_from_stdin\fP
Setting the \fBshell_start_mode\fP parameter either to \fIposix_compliant\fP
or \fIunix_behavior\fP requires you to set the umask in use for
.M xxqs_name_sxx_execd 8
such that every user has read access to the active_jobs directory in the
spool directory of the corresponding execution daemon. In case you have
\fBprolog\fP and \fBepilog\fP scripts configured, they also need to be
readable by any user who may execute jobs.
.br
If this violates your
site's security policies you may want to set \fBshell_start_mode\fP
to \fIscript_from_stdin\fP. This will force xxQS_NAMExx to open the
job script as well as the epilogue and prologue scripts for reading into
STDIN as root (if
.M xxqs_name_sxx_execd 8
was started as root) before changing to the job owner's user account.
The script is then fed into the STDIN stream of the command interpreter
indicated by the \fB\-S\fP option of the
.M qsub 1
command or the \fBshell\fP parameter of the queue to be used (see
.M queue_conf 5
for details).
.br
Thus setting \fBshell_start_mode\fP to \fIscript_from_stdin\fP also
implies \fIposix_compliant\fP behavior. \fBNote\fP, however, that
feeding scripts into the STDIN stream of a command interpreter may
cause trouble if commands like
.M rsh 1
are invoked inside a job script as they also process the STDIN
stream of the command interpreter. These problems can usually be
resolved by redirecting the STDIN channel of those commands to come
from /dev/null (e.g. rsh host date < /dev/null). \fBNote also\fP, that any
command-line options associated with the job are passed to the executing
shell. The shell will only forward them to the job if they are not
recognized as valid shell options.
.PP
Changes to \fBshell_start_mode\fP will take immediate effect.
The default for \fBshell_start_mode\fP is \fIposix_compliant\fP.
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBlogin_shells\fP"
UNIX command interpreters like the Bourne-Shell (see
.M sh 1 )
or the C-Shell (see
.M csh 1 )
can be used by xxQS_NAMExx to start job scripts. The command interpreters
can either be started as login-shells (i.e. all system and user default
resource files like .login or .profile will be executed when the
command interpreter is started and the environment for the job will be
set up as if the user has just logged in) or just for command execution
(i.e. only shell specific resource files like .cshrc will be executed
and a minimal default environment is set up by xxQS_NAMExx \- see
.M qsub 1 ).
The parameter \fBlogin_shells\fP contains a comma separated list of the
executable names of the command interpreters to be started as login-shells.
Shells in this list are only started as login shells if the parameter
\fBshell_start_mode\fP (see above) is set to \fIposix_compliant\fP.
.PP
Changes to \fBlogin_shells\fP will take immediate effect.
The default for \fBlogin_shells\fP is sh,csh,tcsh,ksh.
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBmin_uid\fP"
\fBmin_uid\fP places a lower bound on user IDs that may use the cluster. Users
whose user ID (as returned by
.M getpwnam 3 )
is less than \fBmin_uid\fP will not be allowed to run jobs on the cluster.
.PP
Changes to \fBmin_uid\fP will take immediate effect.
The default for \fBmin_uid\fP is 0.
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBmin_gid\fP"
This parameter sets the lower bound on group IDs that may use the cluster.
Users whose default group ID (as returned by
.M getpwnam 3 )
is less than \fBmin_gid\fP will not be allowed to run jobs on the cluster.
.PP
Changes to \fBmin_gid\fP will take immediate effect.
The default for \fBmin_gid\fP is 0.
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBuser_lists \fP"
The \fBuser_lists\fP parameter contains a comma separated list of so called
user access lists as described in
.M access_list 5 .
Each user contained in at least one of the enlisted access lists has
access to the cluster. If the \fBuser_lists\fP parameter is set to
NONE (the default) any user has access being not explicitly excluded
via the \fBxuser_lists\fP parameter described below.
If a user is contained both in an access list enlisted in \fBxuser_lists\fP
and \fBuser_lists\fP the user is denied access to the cluster.
.PP
Changes to \fBuser_lists\fP will take immediate effect
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBxuser_lists \fP"
The \fBxuser_lists\fP parameter contains a comma separated list of so called
user access lists as described in
.M access_list 5 .
Each user contained in at least one of the enlisted access lists is denied
access to the cluster. If the \fBxuser_lists\fP parameter is set to
NONE (the default) any user has access.
If a user is contained both in an access list enlisted in \fBxuser_lists\fP
and \fBuser_lists\fP (see above) the user is denied access to the cluster.
.PP
Changes to \fBxuser_lists\fP will take immediate effect
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBadministrator_mail\fP"
\fBadministrator_mail\fP specifies a comma separated list of the
electronic mail address(es) of the cluster administrator(s) to whom
internally-generated problem reports are sent. The mail address format
depends on your electronic mail system and how it is configured;
consult your system's configuration guide for more information.
.PP
Changing \fBadministrator_mail\fP takes immediate effect.
The default for \fBadministrator_mail\fP is an empty mail list.
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBprojects\fP"
This parameter is only available for xxQS_NAME_EExx systems. It is not present in
xxQS_NAME_Cxx.
.PP
The \fBprojects\fP list contains all projects which are granted access
to xxQS_NAME_EExx. User belonging to none of these projects cannot use xxQS_NAME_EExx. If
users belong to projects in the \fBprojects\fP list and the
\fBxprojects\fP list (see below), they also cannot use the system.
.PP
Changing \fBprojects\fP takes immediate effect.
The default for \fBprojects\fP is none.
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBxprojects\fP"
This parameter is only available for xxQS_NAME_EExx systems. It is not present in
xxQS_NAME_Cxx.
.PP
The \fBxprojects\fP list contains all projects which are granted access
to xxQS_NAME_EExx. User belonging to one of these projects cannot use xxQS_NAME_EExx. If
users belong to projects in the \fBprojects\fP list (see above) and the
\fBxprojects\fP list, they also cannot use the system.
.PP
Changing \fBxprojects\fP takes immediate effect.
The default for \fBxprojects\fP is none.
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBload_report_time\fP"
System load is reported periodically by the execution daemons to
.M xxqs_name_sxx_qmaster 8 .
The parameter \fBload_report_time\fP defines the time interval between load
reports.
.PP
Each
.M xxqs_name_sxx_execd 8
may use a different load report time. Changing \fBload_report_time\fP will
take immediate effect.
.PP
\fBNote:\fP Be careful
when modifying \fBload_report_time\fP. Reporting load too frequently
might block
.M xxqs_name_sxx_qmaster 8
especially if the number of execution hosts is large. Moreover, since the
system load typically increases and decreases smoothly, frequent load
reports hardly offer any benefit.
.PP
The default for \fBload_report_time\fP is 40 seconds.
.PP
The global configuration entry for this value
may be overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBstat_log_time\fP"
xxQS_NAMExx periodically logs a snapshot of the status of the queues currently
configured in the cluster to disk.
The time interval in seconds between consecutive snapshots is
defined by \fBstat_log_time\fP.
.PP
Changing \fBstat_log_time\fP takes immediate effect.
The default for \fBstat_log_time\fP is 2 hours 30 minutes.
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBmax_unheard\fP"
If
.M xxqs_name_sxx_qmaster 8
could not contact or was not contacted by the execution daemon of a host
for \fBmax_unheard\fP seconds, all queues residing on that particular host
are set to status unknown.
.M xxqs_name_sxx_qmaster 8 ,
at least,
should be contacted by the execution daemons in order to get the load
reports. Thus, \fBmax_unheard\fP should by greater than the
\fBload_report_time\fP (see above).
.PP
Changing \fBmax_unheard\fP takes immediate effect.
The default for \fBmax_unheard\fP is 2 minutes 30 seconds.
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBloglevel\fP"
This parameter specifies the level of detail that xxQS_NAMExx components such
as
.M xxqs_name_sxx_qmaster 8
or
.M xxqs_name_sxx_execd 8
use to produce informative, warning or error messages which are logged
to the \fImessages\fP files in the master and execution daemon
spool directories (see the description of the \fBqmaster_spool_dir\fP
and the \fBexecd_spool_dir\fP parameter above). The following message
levels are available:
.\"
.IP "\fIlog_err\fP"
All error events being recognized are logged.
.\"
.IP "\fIlog_warning\fP"
All error events being recognized and all detected signs of 
potentially erroneous behavior are logged.
.\"
.IP "\fIlog_info\fP"
All error events being recognized, all detected signs of 
potentially erroneous behavior and a variety of informative
messages are logged.
.PP
Changing \fBloglevel\fP will take immediate effect.
.PP
The default for \fBloglevel\fP is \fIlog_info\fP.
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBmax_aj_instances\fP"
This parameter defines the maximum amount of array task to be scheduled to
run simultaneously per array job.  An instance of an array task will be
created within the master daemeon when it gets a start order from the
scheduler. The instance will be destroyed when the array task finishes.
Thus the parameter provides control mainly over the memory consumption of
array jobs in the master and scheduler daemon. It is most useful for very
large clusters and very large array jobs.  The default for this parameter
is 2000. The value 0 will deactivate this limit and will allow the
scheduler to start as many array job tasks as suitable resources are
available in the cluster.
.PP
Changing \fBmax_aj_instances\fP will take immediate effect.
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBmax_aj_tasks\fP"
This parameter defines the maximum number of array job tasks within an array
job.
.M xxqs_name_sxx_qmaster 8
will reject all array job submissions which request
more than
.B max_aj_tasks
array job tasks. The default for this parameter is 75000. The value 0
will deactivate this limit.
.PP
Changing \fBmax_aj_tasks\fP will take immediate effect.
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBmax_u_jobs\fP"
The number of active (not finished) jobs which each xxQS_NAMExx user can
have in the system simultaneously is controlled by this parameter. A value
greater than 0 defines the limit. The default value 0 means "unlimited". If
the
.B max_u_jobs
limit is exceeded by a job submission then the submission command exits
with exit status 25 and an appropriate error message.
.PP
Changing \fBmax_u_jobs\fP will take immediate effect.
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBenforce_project\fP"
This parameter is only available for xxQS_NAME_EExx systems. It is not present in
xxQS_NAME_Cxx.
.PP
If set to \fItrue\fB, users are required to request a project whenever
submitting a job. See the \fB\-P\fP option to
.M qsub 1
for details.
.PP
Changing \fBenforce_project\fP will take immediate effect.
The default for \fBenforce_project\fP is \fIfalse\fP.
.PP
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBenforce_user\fP"
This parameter is only available for xxQS_NAME_EExx systems. It is not present in
xxQS_NAME_Cxx.
.PP
If set to \fItrue\fB, a xxQS_NAME_EExx
.M user 5
must exists to allow for job submission. Jobs are rejected if no corresponding user 
exists. 
.PP
Changing \fBenforce_user\fP will take immediate effect.
The default for \fBenforce_user\fP is \fIfalse\fP.
.PP
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBset_token_cmd\fP"
This parameter is only present if your xxQS_NAMExx system is licensed
to support AFS.
.PP
\fBSet_token_cmd\fP points to a command which sets and extends AFS
tokens for xxQS_NAMExx jobs. In the standard xxQS_NAMExx AFS
distribution, it is supplied as a script which expects two command line
parameters. It reads the token from STDIN, extends the token's
expiration time and sets the token:
.PP
.RS
.nf
<set_token_cmd> <user> <token_extend_after_seconds>
.fi
.RE
.PP
As a shell script this command will call the programs:
.PP
.RS
.nf
- SetToken
- forge
.fi
.RE
.PP
which are provided by your distributor as source code. The script looks as
follows:
.PP
.RS
.nf
--------------------------------
#!/bin/sh
# set_token_cmd
forge -u $1 -t $2 | SetToken
--------------------------------
.fi
.RE
.PP
Since it is necessary for \fIforge\fP to read the secret AFS server
key, a site might wish to replace the \fBset_token_cmd\fP script by a
command, which connects to a self written daemon at the AFS server. The
token must be forged at the AFS server and returned to the local
machine, where \fISetToken\fP is executed.
.PP
Changing \fBset_token_cmd\fP will take immediate effect.
The default for \fBset_token_cmd\fP is none.
.PP
The global configuration entry for this value
may be overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBpag_cmd\fP"
This parameter is only present if your xxQS_NAMExx system is licensed
to support AFS.
.PP
The path to your \fIpagsh\fB is specified via this parameter.
The
.M xxqs_name_sxx_shepherd 8
process and the job run in a \fIpagsh\fP. Please ask your AFS administrator
for details.
.PP
Changing \fBpag_cmd\fP will take immediate effect.
The default for \fBpag_cmd\fP is none.
.PP
The global configuration entry for this value
may be overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBtoken_extend_time\fP"
This parameter is only present if your xxQS_NAMExx system is licensed
to support AFS.
.PP
the time period for which AFS tokens are periodically extended. xxQS_NAMExx
will call the token extension 30 minutes before the tokens expire until
jobs have finished and the corresponding tokens are no longer required.
.PP
Changing \fBtoken_extend_time\fP will take immediate effect.
The default for \fBtoken_extend_time\fP is 24:0:0, i.e. 24 hours.
.PP
The global configuration entry for this value
may be overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBgid_range\fP"
The \fBgid_range\fP
is a comma separated list of range expressions of the form n-m (n as
well as m being positive non-zero integer numbers), where m is an
abbreviation for m-m. These numbers are used in
.M xxqs_name_sxx_execd 8
to identify processes belonging to the same job.
.PP
Each
.M xxqs_name_sxx_execd 8
may use a separate set up group ids for this purpose.
All number in the group id range have to be unused
supplementary group ids on the system, where the
.M xxqs_name_sxx_execd 8
is started.
.PP
Changing \fBgid_range\fP will take immediate effect.
There is no default for \fBgid_range\fP. The administrator will have to
assign a value for \fBgid_range\fP during installation of xxQS_NAME_EExx.
.PP
The global configuration entry for this value
may be overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBqmaster_params\fP"
A list of additional parameters can be passed to the 
xxQS_NAMExx qmaster. The following values are recognized:
.IP "\fIENABLE_FORCED_QDEL\fP"
If this parameter is set, non-administrative users can foce deletion of
their own jobs via the \fI\-f\fP option of
.M qdel 1 .
Without this parameter, forced deletion of jobs is only allowed by the
xxQS_NAMExx manager or operator.
.sp 1
\fBNote:\fP Forced deletion for jobs is executed differently depending
on whether users are xxQS_NAMExx administrators or not. In case of
administrative users, the jobs are removed from the internal database of
xxQS_NAMExx immediately. For regular users, the equivalent of a normal
.M qdel 1
is executed first, and deletion is forced only if the normal cancellation
was unsuccessful.
.sp 1
Changing \fBqmaster_params\fP will take immediate effect.
The default for \fBqmaster_params\fP is none.
.sp 1
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.IP "\fIFORBID_RESCHEDULE\fP"
If this parameter is set, re-queuing of jobs cannot
be initiated by the job script which is under control 
of the user. Without this parameter jobs returning the 
value 99 are rescheduled. This can be used to cause the 
job to be restarted at a different machine, for instance if there
are not enough resources on the current one.
.PP
.IP "\fIDISABLE_AUTO_RESCHEDULING\fP"
If set to "true" or "1", the \fBexecd_param\fP \fIRESCHEDULE_UNKNOWN\fP
(see below) is not taken into account.
.PP
.IP "\fINO_REPRIORITIZATION\fP"
If set to "true" or "1", jobs are not repriorized dynamically. Without 
setting this attribute the \fBpriority\fP parameter in 
.M sched_conf 5 
has no durable effect in a SGEEE system because of dynamic reprioritization
performed by the PTF module inside 
.M sge_execd 8 .
.PP
Changing \fBqmaster_params\fP will take immediate effect.
The default for \fBqmaster_params\fP is none.
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBschedd_params\fP"
This is foreseen for passing additional parameters 
to the xxQS_NAMExx scheduler. The following values are recognized currently:
.\"
.IP "\fIFLUSH_SUBMIT_SEC\fP, \fIFLUSH_FINISH_SEC\fP"
The parameters are provided for tuning the system's scheduling behavior.
By default, a scheduler run is triggered in the scheduler interval which
is defined in the scheduler configuration
.M sched_conf 5 ,
parameter \fBschedule_interval\fP.
.br
The parameters FLUSH_SUBMIT_SEC/FLUSH_FINISH_SEC define the time gaps
between triggering a scheduler run and the submitting/finishing of a job.
.br
The most immediate scheduler reaction can be activated by setting both
values to 0. The default scheduling behavior is enforced by either
removing the parameters or setting them to a value of -1.
.\"
.IP "\fICLASSIC_SGEEE_SCHEDULING\fP"                                         
If set to "true" or "1", use the original SGEEE pending job scheduling       
algorithm. The original SGEEE pending job scheduling algorithm calculates    
the tickets for pending jobs by dividing up the tickets in each            
scheduling policy among all the active and pending jobs. The pending       
job list is then ordered based on the tickets assigned to the pending      
jobs. The default value is "false".                                        
This parameter is only valid in a SGEEE system.                              
.\"                                                                        
.IP "\fIPOLICY_HIERARCHY\fP"                                         
This parameter sets up a dependency chain of
policies. Each policy in the dependency chain is influenced by the
previous policies and influences the following policies. A typical
scenario is to assign precedence for the override policy over the
share-based policy. The override policy determines in such a case how
share-based tickets are assigned among jobs of the same user or project.
Note that all policies contribute to the ticket amount assigned to a
particular job regardless of the policy hierarchy definition. Yet the
tickets calculated in each of the policies can be differend depending on
"\fIPOLICY_HIERARCHY\fP".
.sp 1
The "\fIPOLICY_HIERARCHY\fP" parameter can be a up to 4 letter
combination of the first letters of the 4 policies S(hare-based),
F(unctional), D(eadline) and O(verride). So a value "OFSD" means that the
override policy takes precedence over the functional policy, which
influences the share-based policy and which finaly preceeds the deadline
policy. Less than 4 letters mean that some of the policies do not influence
other policies and also are not influenced by other policies. So a value of
"FS" means that the functional policy influences the share-based policy and
that there is no interference with the other policies.
.sp 1
The special value "NONE" switches off policy hierarchies.
.\"                                                                        
.IP "\fISHARE_OVERRIDE_TICKETS\fP"                                         
If set to "true" or "1", override tickets of any override object instance  
are shared equally among all jobs associated with the object. If set to    
"false" or "0", each job gets the full value of the override tickets       
associated with the object. The default value is "true".                   
This parameter is only valid in a SGEEE system.                              
.\"                                                                        
.IP "\fISHARE_FUNCTIONAL_SHARES\fP"                                        
If set to "true" or "1", functional shares of any functional object instance
are shared among all the jobs associated with the object. If set to "false"
or "0", each job associated with a functional object, gets the full        
functional shares of that object. The default value is "true".            
This parameter is only valid in a SGEEE system.                              
.\"                                                                        
.IP "\fISHARE_DEADLINE_TICKETS\fP"                                         
If set to "true" or "1", the total deadline tickets are shared among all   
deadline jobs. If set to "false" or "0", each deadline job will receive    
the total deadline tickets once the job deadline has been reached. The     
default value is "true".                                                   
This parameter is only valid in a SGEEE system.                              
.\"                                                                        
.IP "\fIMAX_FUNCTIONAL_JOBS_TO_SCHEDULE\fP"                                
The maximum number of pending jobs to schedule in the functional policy.   
The default value is 200.                                                  
This parameter is only valid in a SGEEE system.                              
.\"                                                                        
.IP "\fIMAX_PENDING_TASKS_PER_JOB\fP"                                      
The maximum number of subtasks per pending array job to schedule. This     
parameter exists in order to reduce scheduling overhead. The default value 
is 50.
This parameter is only valid in a SGEEE system.                              
.\"
.IP "\fIPROFILE\fP"
If set, the scheduler logs profiling information summarizing each scheduling 
run.
.\"
.PP
Changing \fBschedd_params\fP will take immediate effect.
The default for \fBschedd_params\fP is none.
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.SH "\fBexecd_params\fP"
This is foreseen for passing additional parameters 
to the xxQS_NAMExx execution daemon. The following values are recognized:
.\"
.IP "\fIACCT_RESERVED_USAGE\fP"
If this parameter is set to true, for reserved usage is used for the
accounting entries \fBcpu\fP, \fBmem\fP and \fBio\fP instead of the
measured usage.
.PP
.IP "\fIKEEP_ACTIVE\fP"
This value should only be set for debugging purposes. If set to true, the
execution daemon will not remove the spool directory maintained by
.M xxqs_name_sxx_shepherd 8
for a job.
.PP
.IP "\fIPTF_MIN_PRIORITY\fP, \fIPTF_MAX_PRIORITY\fP"
The parameters are only available in a xxQS_NAME_EExx system.
.br
The maximum/minumum priority which xxQS_NAME_EExx will assign to a job.
Typically this is a negative/postive value in the range of -20
(maximum) to 19 (minimum) for systems which allow setting of priorties
with the
.M nice 2
system call. Other systems may provide different ranges.
.br
The default priority range (varies from system to system) is installed
either by removing the parameters or by setting a value of -999.
.br
See the "messages" file of the execution daemon for the predefined
default value on your hosts. The values are logged during the startup of
the execution daemon.
.PP
.IP "\fINOTIFY_KILL\fP"
The parameter allows you to change the notification signal for
the signal SIGKILL (see \fI\-notify\fP option of 
.M qsub 1 ).
The parameter either accepts signal names (use the \fI\-l\fP option of
.M kill 1 )
or the special value \fInone\fP. If set to \fInone\fP,
no notification signal will be sent. If it is set to \fITERM\fP, for
instance, or another
signal name then this signal will be sent as notification signal.
.PP
.IP "\fINOTIFY_SUSP\fP"
With this parameter it is possible to modify the notification signal
for the signal SIGSTOP (see \fI\-notify\fP parameter of 
.M qsub 1 ).
The parameter either accepts signal names (use the \fI\-l\fP option of
.M kill 1 )
or the special value \fInone\fP. If set to \fInone\fP,
no notification signal will be sent. If it is set to \fITSTP\fP, for
instance, or another
signal name then this signal will be sent as notification signal.
.PP
.IP "\fIRESCHEDULE_UNKNOWN\fP"
Determines whether jobs on hosts in unknown state are rescheduled and thus
sent to other hosts. Hosts are registered as unknown if
.M xxqs_name_sxx_master 8
cannot establish contact to the
.M xxqs_name_sxx_execd 8
on those hosts (see \fBmax_unheard\fP). Likely reasons are a breakdown of
the host or a breakdown
of the network connection in between, but also
.M xxqs_name_sxx_execd 8
may not be executing on such hosts.
.br
In any case, xxQS_NAMExx can reschedule jobs running on such hosts to
another system. \fIRESCHEDULE_UNKNOWN\fP controls the time which
xxQS_NAMExx will wait before jobs are rescheduled after a host became
unknown. The time format
specification is RESCHEDULE_UNKNOWN=hh:mm:ss. If the special value
RESCHEDULE_UNKNOWN=00:00:00 is set, then jobs will not be rescheduled from
this host.
.br
Rescheduling is only initiated for jobs which have actiated the rerun flag
(see the \fB\-r y\fP option of
.M qsub 1
and the \fBrerun\fP option of
.M queue_conf 5 ).
Parallel jobs are only rescheduled if the host on which their master tasks
executes is in unknown state. Interactive jobs (see
.M qsh 1 ,
.M qrsh 1 ,
.M qtcsh 1 )
are not rescheduled. Migrating checkpointing jobs (and starting from the
last checkpoint) will be supported in
a future release.
.PP
.IP "\fISET_SGE_ENV, SET_COD_ENV, SET_GRD_ENV\fP"
In qsub(1) you can find a list of environment variables which are
exported into the execution environment of each xxQS_NAME_EExx job. Some of 
these variables names begin with the prefix "SGE_". In the predecessor products 
of xxQS_NAME_EExx (Codine, GRD) the prefixes "COD_" and "GRD_" were used for 
those variables. This makes it necessary to update all job scripts relying one 
of those environment variables. The parameters SET_SGE_ENV, SET_COD_ENV and 
SET_GRD_ENV can be used to accomplish a smoother transition from Codine/GRD 
to xxQS_NAME_EExx.

Each of those parameters makes sure that a set of environment variables
mentioned in qsub(1) and beginning with the corresponding prefix will be
exported into the job environmnet. Every parameter can be set to
"true", "1" or "false", "0". Defaults are "SET_SGE_ENV=1, SET_COD_ENV=0 and
SET_GRD_ENV=0".

If all three parameters are set to "false" or "0" jobs might fail as none of 
the corresponding environment variables would be set. Therefore in this case
the environment variables beginning with the prefix "SGE_" are set.
.PP
.IP "\fISHARETREE_RESERVED_USAGE\fP"
If this parameter is set to true, reserved usage is taken for the xxQS_NAME_EExx share
tree consumption instead of measured usage.
.PP
Changing \fBexecd_params\fP will take immediate effect.
The default for \fBexecd_params\fP is none.
.PP
The global configuration entry for this value
may be overwritten by the execution host local configuration.
.\"
.\"
.IP "\fIUSE_QSUB_GID\fP"
If this parameter is set to true, the primary group id being active when a
job was submitted will be set to become the primary group id for job
execution. If the parameter is not set, the primary group id as defined for
the job owner in the execution host
.M passwd 5
file is used.
.br
The feature is only available for jobs submitted via
.M qsub 1 ,
.M qrsh 1 ,
.M qmake 1
and 
.M qtcsh 1 .
Also, it only works for
.M qrsh 1
jobs (and thus also for
.M qtcsh 1
and
.M qmake 1 )
if rsh and rshd components are used which are provided with xxQS_NAMExx
(i.e., the \fBrsh_daemon\fP and \fBrsh_command\fP parameters may
not be changed from the default).
.\"
.\"
.SH "\fBadmin_user\fP"
Administrative user account used by xxQS_NAMExx for all internal file
handling (status spooling, message logging, etc.). Can be used in cases
where the root account does not have the corresponding file access
permissions (e.g. on a shared file system without global root read/write
access).
.PP
Being a parameter set at installation time changing \fBadmin_user\fP in
a running system is not supported. Changing it manually on a shut-down cluster
is possible, but if access to the xxQS_NAMExx spooling area is interrupted, 
this will result in unpredictable behaviour.

The \fBadmin_user\fP parameter has no default value, but instead it is
defined during the master installation procedure.
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBfinished_jobs\fP"
xxQS_NAMExx stores a certain number of \fIjust finished\fP jobs to provide
post mortem status information. The \fBfinished_jobs\fP parameter defines the
number of finshed jobs being stored. If this maximum number is reached, the
eldest finshed job will be discarded for every now job being added to the
finshed job list.
.PP
Changing \fBfinished_jobs\fP will take immediate effect.
The default for \fBfinished_jobs\fP is 0.
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBqlogin_daemon\fP"
This parameter specifies the executable that is to be started on the
server side of a
.M qlogin 1 
request. Usually this is the fully qualified
pathname of the system's telnet daemon. If no value is given, a specialized
xxQS_NAMExx component is used.
.PP
Changing \fBqlogin_daemon\fP will take immediate effect.
The default for \fBqlogin_daemon\fP is none.
.PP
The global configuration entry for this value
may be overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBqlogin_command\fP"
This is the command to be executed on the client side of a 
.M qlogin 1
request.
Usually this is the fully qualified pathname of the systems's telnet
client program. If no value is given, a specialized xxQS_NAMExx
component is used. It is automatically started with the target host and
port number as parameters.
.PP
Changing \fBqlogin_command\fP will take immediate effect.
The default for \fBqlogin_command\fP is none.
.PP
The global configuration entry for this value
may be overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBrlogin_daemon\fP"
This parameter specifies the executable that is to be started on the server
side of a
.M qrsh 1
request
.B without
a command argument to be executed
remotely. Usually this is the fully qualified pathname of the system's
rlogin daemon.  If no value is given, a specialized xxQS_NAMExx component
is used.
.sp 1
Changing
.B rlogin_daemon
will take immediate effect. The default for
.B rlogin_daemon
is none.
.sp 1
The global configuration entry for this value may be overwritten by the
execution host local configuration.
.\"
.\"
.SH "\fBrlogin_command\fP"
This is the command to be executed on the client side of a
.M qrsh 1
request
.B without
a command argument to be executed remotely. Usually this is the
fully qualified pathname of the system's rlogin client program. If no value
is given, a specialized xxQS_NAMExx component is used. The command is
automatically started with the target host and port number as parameters
like required for
.M telnet 1 .
The xxQS_NAMExx rlogin client has been extened
to accept and use the port number argument. You can only use clients, such
as \fIssh\fP, which also understand this syntax.
.sp 1
Changing
.B rlogin_command
will take immediate effect. The default for
.B rlogin_command
is none.
.sp 1
The global configuration entry for this value may be overwritten by the
execution host local configuration.
.\"
.\"
.SH "\fBrsh_daemon\fP"
This parameter specifies the executable that is to be started on the server
side of a
.M qrsh 1
request
.B with
a command argument to be executed remotely.
Usually this is the fully qualified pathname of the system's rsh daemon. If
no value is given, a specialized xxQS_NAMExx component is used.
.sp 1
Changing
.B rsh_daemon
will take immediate effect. The default for
.B rsh_daemon
is none.
.sp 1
The global configuration entry for this value may be overwritten by the
execution host local configuration.
.\"
.\"
.SH "\fBrsh_command\fP"
This is the command to be executed on the client side of a
.M qrsh 1
request
.B with
a command argument to be executed remotely. Usually this is the fully
qualified pathname of the system's rsh client program. If no value is
given, a specialized xxQS_NAMExx component is used. The command is
automatically started with the target host and port number as parameters
like required for
.M telnet 1
plus the command with its arguments to be
executed remotely. The xxQS_NAMExx rsh client has been extened to accept
and use the port number argument. You can only use clients, such as
\fIssh\fP, which also understand this syntax.
.sp 1
Changing
.B rsh_command
will take immediate effect. The default for
.B rsh_command
is none.
.sp 1
The global configuration entry for this value may be overwritten by the
execution host local configuration.
.\"
.\"
.SH "\fBignore_fqdn\fP"
Ignore fully qualified domain name component of hostnames. Should be set 
if all hosts belonging to a xxQS_NAMExx cluster are part of a single DNS 
domain. It is switched on if set to either "true" or "1". Switching it 
on may solve problems with load reports due to different hostname 
resolutions across the cluster.
.sp 1
Being a parameter set at installation time changing
.B ignore_fqdn
in a running system is not supported. The default for
.B ignore_fqdn
is "true".
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.SH "\fBdefault_domain\fP"
Only needed if your xxQS_NAMExx cluster covers hosts belonging to more than
a single DNS domain. In this case it can be used if your hostname resolving 
yields both qualified and unqualified hostnames for the hosts in one of the 
DNS domains. 
The value of
.B default_domain
is appended to the unqualified hostname to define a fully qualified hostname.
The 
.B default_domain
parameter will have no effect if 
.B ignore_fqdn
is set to "true".
.sp 1
Being a parameter set at installation time changing
.B default_domain
in a running system is not supported. The default for
.B default_domain
is "none", in which case it will not be used.
.PP
This value is a global configuration parameter only. It cannot be
overwritten by the execution host local configuration.
.\"
.\"
.\"
.SH "SEE ALSO"
.M xxqs_name_sxx_intro 1 ,
.M csh 1 ,
.M qconf 1 ,
.M qsub 1 ,
.M rsh 1 ,
.M sh 1 ,
.M getpwnam 3 ,
.M queue_conf 5 ,
.M sched_conf 5 ,
.M xxqs_name_sxx_execd 8 ,
.M xxqs_name_sxx_qmaster 8 ,
.M xxqs_name_sxx_shepherd 8 ,
.M cron 8 ,
.I xxQS_NAMExx Installation and Administration Guide.
.\"
.SH "COPYRIGHT"
See
.M xxqs_name_sxx_intro 1
for a full statement of rights and permissions.
