'\" t
.\"___INFO__MARK_BEGIN__
.\"
.\" Copyright: 2001 by Sun Microsystems, Inc.
.\"
.\"___INFO__MARK_END__
.\" 
.\" $RCSfile: usermapping.5,v $     Last Update: $Date: 2001/07/20 08:19:16 $     Revision: $Revision: 1.3 $
.\"
.\"
.\" Some handy macro definitions [from Tom Christensen's man(1) manual page].
.\"
.de SB		\" small and bold
.if !"\\$1"" \\s-2\\fB\&\\$1\\s0\\fR\\$2 \\$3 \\$4 \\$5
..
.\"
.de T		\" switch to typewriter font
.ft CW		\" probably want CW if you don't have TA font
..
.\"
.de TY		\" put $1 in typewriter font
.if t .T
.if n ``\c
\\$1\c
.if t .ft P
.if n \&''\c
\\$2
..
.\"
.de M		\" man page reference
\\fI\\$1\\fR\\|(\\$2)\\$3
..
.TH USERMAPPING 5 "$Date: 2001/07/20 08:19:16 $"
.\"
.SH NAME
usermapping \- user mapping entry file format
.\"
.SH DESCRIPTION
.PP
A usermapping entry is used to define alias names for a cluster 
user. The users name known by the sheduling system is called
cluster user. If the cluster name doesn't match the user account
name on an execution host, the usermapping feature can solve the
problem.
.PP
Each line in the usermapping entry file specifies a user name and
the host(s) where he has an account. 
.PP
A list of currently configured user mapping entries can be displayed 
via the
.M qconf 1
\fB\-sumapl\fP option. The contents of each enlisted user mapping entry 
can be
shown via the \fB\-sumap\fP switch. The output follows the
.I usermapping
format description. New user entries can be created and existing can be
modified via the \fB\-aumap\fP, \fB\-mumap\fP and \fB\-dumap\fP options to
.M qconf 1 .
.\"
.\"
.SH FORMAT
A user mapping entry contains at least tree parameters:
.IP "\fBcluster_user keyword\fP"
The cluster_user keyword defines the cluster user name. The rest of
the textline after the keyword "cluster_user" will be taken as cluster
user value.

.IP "\fBname\fP"
The user name on an execution host.
.IP "\fBhostname\fP"
The name of the host where the user specified in \fBname\fP has an account.
If The first character of the hostname is a "@" sign the name is used to 
reference a 
.M hostgroup 5 .
.\"
.\"

.SH EXAMPLE
This is a typical user mapping entry for a cluster user mapping:

.PP
cluster_user office
.PP
.PP
alice     wonderland, realworld, @office2
.PP

The entry will map the user office which is defined in the cluster system to 
the user alice on the hosts wonderland and realworld. 
The "@" sign is used to reference a host group. So the user office is mapped 
to alice on all hosts specified in the host group office2. 
Please see 
.M hostgroup 5
to obtain for more information about that.
 



.\"

.SH "SEE ALSO"
.M qconf 1 , 
.M hostgroup 5 .
.\"
.SH "COPYRIGHT"
See
.M xxqs_name_sxx_intro 1
for a full statement of rights and permissions.
