'\" t
.\"___INFO__MARK_BEGIN__
.\"
.\" Copyright: 2004 by Sun Microsystems, Inc.
.\"
.\"___INFO__MARK_END__
.\"
.\" $RCSfile: qacct.1,v $     Last Update: $Date: 2009/02/12 14:32:28 $     Revision: $Revision: 1.17 $
.\"
.\"
.\" Some handy macro definitions [from Tom Christensen's man(1) manual page].
.\"
.de SB		\" small and bold
.if !"\\$1"" \\s-2\\fB\&\\$1\\s0\\fR\\$2 \\$3 \\$4 \\$5
..
.\"
.de T		\" switch to typewriter font
.ft CW		\" probably want CW if you don't have TA font
..
.\"
.de TY		\" put $1 in typewriter font
.if t .T
.if n ``\c
\\$1\c
.if t .ft P
.if n \&''\c
\\$2
..
.\"
.de M		\" man page reference
\\fI\\$1\\fR\\|(\\$2)\\$3
..
.TH QACCT 1 "$Date: 2009/02/12 14:32:28 $" "xxRELxx" "xxQS_NAMExx User Commands"
.SH NAME
qacct \- report and account for xxQS_NAMExx usage
.SH SYNOPSIS
.B qacct
[
.B \-ar [ar_id] 
] [
.B \-A Account
] [
.B \-b BeginTime
] [
.B \-d Days
] [
.B \-e EndTime
] [
.B \-g [GroupId|GroupName]
] [
.B \-h [HostName]
] [
.B \-help
] [
.B \-j [job_id|job_name|pattern]
] [
.B \-l attr=val,...
] [
.B \-o [Owner]
] [
.B \-pe [PEname]
] [
.B \-q [wc_queue]
] [
.B \-slots [SlotNumber]
] [
.B \-t task_id_range_list
] [
.B \-P [Project]
] [
.B \-D [Department]
] [
.B \-f
.I AcctFileName
]
.\"
.\"
.SH DESCRIPTION
The
.I qacct
utility scans the accounting data file (see
.M accounting 5 )
and produces a summary
of information for wall-clock time, cpu-time, and system time
for the categories of hostname, queue-name, group-name,
owner-name, job-name, job-ID and for the queues meeting the resource
requirements as specified with the \fB\-l\fP switch.
Combinations of each category are permitted. Alternatively, all
or specific jobs can be listed with the \fB\-j\fP switch.
For example the
search criteria could include summarizing for a queue and an
owner, but not for two queues in the same request.
.\"
.\"
.SH OPTIONS
.IP "\fB\-ar\fP [\fBar_id\fP]"
The ID of the advance reservation for which usage is summarized.
If \fBar_id\fP is not given, accounting data is
listed for each advance reservation separately.
.\"
.IP "\fB\-A Account\fP"
The account for jobs to be summarized. 
.\"
.IP "\fB\-b BeginTime\fP"
The earliest start time for jobs to be summarized, in the format
[[CC]YY]MMDDhhmm[.SS]. See also \fB\-d\fP option. If CC is not
specified, a YY of < 70 means 20YY.
.\"
.IP "\fB\-d Days\fP"
The number of days to summarize and print accounting information on. If
used together with the \fB\-b BeginTime\fP option (see above), jobs
started within \fBBeginTime\fP to \fBBeginTime\fP + \fBDays\fP are
counted. If used together with the \fB\-e EndTime\fP (see below)
option, count starts at \fBEndTime\fP - \fBDays\fP.
.\"
.IP "\fB\-e EndTime\fP"
The latest start time for jobs to be summarized, in the format
[[CC]YY]MMDDhhmm[.SS]. See also \fB\-d\fP option. If CC is not
specified, a YY of < 70 means 20YY.
.\"
.IP "[\fB\-f\fP \fBAcctFileName\fP]"
The accounting file to be used. If omitted, the system
default accounting file is processed.
.\"
.IP "\fB\-g\fP [\fBGroupId\fP|\fBGroupName\fP]"
The numeric system group id or the group alphanumeric name of the
job owners to be included
in the accounting. If \fBGroupId\fP/\fBGroupName\fP is omitted, all
groups are accounted.
.\"
.IP "\fB\-h\fP [\fBHostName\fP]"
The case-insensitive name of the host upon which accounting
information is requested. If the name is omitted, totals for each host are
listed separately.
.\"
.IP "\fB\-help\fP"
Display help information for the
.I qacct
command.
.\"
.IP "\fB\-j\fP [\fBjob_id|job_name|pattern\fP]"
The name, a expression for matching names, or ID of the job during execution 
for which accounting information is printed. If neither a name nor an ID 
is given all jobs are enlisted.
.br
This option changes the output format of
\fIqacct\fP. If activated, CPU times are no longer accumulated but the
"raw" accounting information is printed in a formatted form instead.
See
.M accounting 5
for an explanation of the displayed information.
.\"
.IP "\fB\-l attr=val,...\fP"
A resource requirement specification which must be met by the queues
in which the jobs being accounted were executing. The resource request 
is very similar to the one described in
.M qsub 1 .
.\"
.IP "\fB\-o\fP [\fBOwner\fP]"
The name of the owner of the jobs for which accounting statistics
are assembled. If the optional \fBOwner\fP argument is omitted,
a listing of the accounting statistics of all job owners being
present in the accounting file is produced.
.\"
.IP "\fB\-pe\fP [\fBPEname\fP]"
The name of the parallel environment for which usage is summarized.
If \fBPEname\fP is not given, accounting data is
listed for each parallel environment separately.
.\"
.IP "\fB\-q\fP [\fBwc_queue_name\fP]"
A expression for queues for which usage is summarized. All
queue instances matching the expression will be listed. If
no expression is specified, a cluster queue summary will be 
given.
.\"
.IP "\fB\-slots\fP [\fBSlotNumber\fP]"
The number of queue slots for which usage is summarized.
If \fBSlotNumber\fP is not given, accounting data is
listed for each number of queue slots separately.
.\"
.IP "\fB\-t task_id_range_list\fP
Only available together with the \fB\-j\fP option described above.
.sp 1
The \fB\-t\fP switch specifies the array job task range, for which
accounting information should be printed. Syntax and semantics of
\fBtask_id_range_list\fP are identical to that one described under the
\fB\-t\fP option to
.M qsub 1 .
Please see there also for further information on array jobs.
.\"
.IP "\fB\-P\fP [\fBProject\fP]"
The name of the project for which usage is summarized.
If \fBProject\fP is not given, accounting data is
listed for each owning project separately.
.\"
.IP "\fB\-D\fP [\fBDepartment\fP]"
The name of the department for which usage is summarized.
If \fBDepartment\fP is not given, accounting data is
listed for each owning department separately.
.\"
.\"
.SH "ENVIRONMENTAL VARIABLES"
.\" 
.IP "\fBxxQS_NAME_Sxx_ROOT\fP" 1.5i
Specifies the location of the xxQS_NAMExx standard configuration
files.
.\"
.IP "\fBxxQS_NAME_Sxx_CELL\fP" 1.5i
If set, specifies the default xxQS_NAMExx cell. To address a xxQS_NAMExx
cell
.I qacct
uses (in the order of precedence):
.sp 1
.RS
.RS
The name of the cell specified in the environment 
variable xxQS_NAME_Sxx_CELL, if it is set.
.sp 1
The name of the default cell, i.e. \fBdefault\fP.
.sp 1
.RE
.RE
.\"
.IP "\fBxxQS_NAME_Sxx_DEBUG_LEVEL\fP" 1.5i
If set, specifies that debug information
should be written to stderr. In addition the level of
detail in which debug information is generated is defined.
.\"
.IP "\fBxxQS_NAME_Sxx_QMASTER_PORT\fP" 1.5i
If set, specifies the tcp port on which
.M xxqs_name_sxx_qmaster 8
is expected to listen for communication requests.
Most installations will use a services map entry for the
service "sge_qmaster" instead to define that port.
.\"
.IP "\fBxxQS_NAME_Sxx_EXECD_PORT\fP" 1.5i
If set, specifies the tcp port on which
.M xxqs_name_sxx_execd 8
is expected to listen for communication requests.
Most installations will use a services map entry for the
service "sge_execd" instead to define that port.
.\"
.\"
.SH FILES
.nf
.ta \w'<xxqs_name_sxx_root>/     'u
\fI<xxqs_name_sxx_root>/<cell>/common/accounting\fP
	xxQS_NAMExx default accounting file
\fI<xxqs_nam_sexx_root>/<cell>/common/act_qmaster\fP
	xxQS_NAMExx master host file
.fi
.\"
.\"
.SH "SEE ALSO"
.M xxqs_name_sxx_intro 1 ,
.M qsub 1 ,
.M accounting 5 ,
.M xxqs_name_sxx_qmaster 8 ,
.\"
.\"
.SH "COPYRIGHT"
See
.M xxqs_name_sxx_intro 1
for a full statement of rights and permissions.
