'\" t
.\"___INFO__MARK_BEGIN__
.\"
.\" Copyright: 2001 by Sun Microsystems, Inc.
.\"
.\"___INFO__MARK_END__
.\"
.\" $RCSfile: qdel.1,v $     Last Update: $Date: 2003/07/30 12:21:48 $     Revision: $Revision: 1.6 $
.\"
.\"
.\" Some handy macro definitions [from Tom Christensen's man(1) manual page].
.\"
.de SB		\" small and bold
.if !"\\$1"" \\s-2\\fB\&\\$1\\s0\\fR\\$2 \\$3 \\$4 \\$5
..
.\"
.de T		\" switch to typewriter font
.ft CW		\" probably want CW if you don't have TA font
..
.\"
.de TY		\" put $1 in typewriter font
.if t .T
.if n ``\c
\\$1\c
.if t .ft P
.if n \&''\c
\\$2
..
.\"
.de M		\" man page reference
\\fI\\$1\\fR\\|(\\$2)\\$3
..
.TH QDEL 1 "$Date: 2003/07/30 12:21:48 $" "xxRELxx" "xxQS_NAMExx User Commands"
.SH NAME
qdel \- delete xxQS_NAMExx jobs from queues
.SH SYNTAX
.B qdel
[
.B \-f
] [
.B \-help
] [
.B \-verify
] [
.B job/task_id_list
]
.\"
.PP
.B qdel
[
.B \-f
] [
.B \-help
] [
.B \-verify
] 
.B -u user_list | -uall
.\" 
.SH DESCRIPTION
.I Qdel
provides a means for a user/operator/manager to delete
one or more jobs. 
.I Qdel
deletes jobs in the order in which their job 
identifiers are presented. 
.\"
.\"
.SH OPTIONS
.\"
.IP "\fB\-f\fP"
Force action for running jobs. The job(s) are deleted from the list of
jobs registered at
.M xxqs_name_sxx_qmaster 8
even if the
.M xxqs_name_sxx_execd 8
controlling the job(s) does not respond to the delete request sent by
.M xxqs_name_sxx_qmaster 8 .
.PP
Users which are neither xxQS_NAMExx managers nor operators can only use the
.B \-f
option (for their own jobs) if the cluster configuration entry
.B qmaster_params
contains the flag ENABLE_FORCED_QDEL (see
.M xxqs_name_sxx_conf 5 ).
However, behavior for administrative and
non-administrative users differs. Jobs are deleted from the xxQS_NAMExx
database immediately in case of administrators. Otherwise, a regular
deletion is attempted first and a forced cancellation is only executed if
the regular deletion was unsuccessful.
.\"
.IP "\fB\-help\fP"
Prints a listing of all options.
.\"
.IP "\fB\-u username,... | -uall\fP"
Deletes only those jobs which were submitted by
users specified in the list of usernames.
For managers it is possible to use the \fB\qdel -uall\fP command
to delete all jobs of all users.
.sp 1
If you use the \fB\-u\fP or \fB\-uall\fP switch it is be permitted to
specify a additional \fI\job/task_id_list\fP.  
.\"
.IP "\fB\-verify\fP"
performs no modifications but just prints what would be done if
\fB\-verify\fB was not present.
.\"
.IP "\fBjob/task_id_list\fP"
Specified by the following form:
.sp 1
.ta 0.5i
    \fIjob_id[.task_range][ job_id[.task_range] ...]\fP
.ta 0.0i
.sp 1
If present, the \fItask_range\fP restricts the effect of the \fIqdel\fP
operation to the array job task range specified as suffix to the job id
(see the \fB\-t\fP option to
.M qsub 1
for further details on array jobs).
.sp 1
The task range specifier has the
form n[-m[:s]]. The range may be a single number, a  simple
range  of the form n-m or a range with a step size.
.sp 1
Instead of job/task_id_list it is possible to
use the keyword 'all' to modify all jobs of the
current user. 
.\"
.\"
.SH "ENVIRONMENTAL VARIABLES"
.\" 
.IP "\fBxxQS_NAME_Sxx_ROOT\fP" 1.5i
Specifies the location of the xxQS_NAMExx standard configuration
files.
.\"
.IP "\fBxxQS_NAME_Sxx_CELL\fP" 1.5i
If set, specifies the default xxQS_NAMExx cell. To address a xxQS_NAMExx
cell
.I qdel
uses (in the order of precedence):
.sp 1
.RS
.RS
The name of the cell specified in the environment 
variable xxQS_NAME_Sxx_CELL, if it is set.
.sp 1
The name of the default cell, i.e. \fBdefault\fP.
.sp 1
.RE
.RE
.\"
.IP "\fBxxQS_NAME_Sxx_DEBUG_LEVEL\fP" 1.5i
If set, specifies that debug information
should be written to stderr. In addition the level of
detail in which debug information is generated is defined.
.\"
.IP "\fBCOMMD_PORT\fP" 1.5i
If set, specifies the tcp port on which
.M xxqs_name_sxx_commd 8
is expected to listen for communication requests.
Most installations will use a services map entry instead
to define that port.
.\"
.\"
.SH FILES
.nf
.ta \w'<xxqs_name_sxx_root>/     'u
\fI<xxqs_name_sxx_root>/<cell>/common/act_qmaster\fP
	xxQS_NAMExx master host file
.fi
.\"
.\"
.SH "SEE ALSO"
.M xxqs_name_sxx_intro 1 ,
.M qstat 1 ,
.M qsub 1 ,
.M xxqs_name_sxx_qmaster 8 ,
.M xxqs_name_sxx_execd 8 .
.\"
.\"
.SH "COPYRIGHT"
See
.M xxqs_name_sxx_intro 1
for a full statement of rights and permissions.
