'\" t
.\"___INFO__MARK_BEGIN__
.\"
.\" Copyright: 2004-2007 by Sun Microsystems, Inc.
.\"
.\"___INFO__MARK_END__
.\"
.\" $RCSfile: qstat.1,v $     Last Update: $Date: 2009/11/05 13:18:36 $     Revision: $Revision: 1.41 $
.\"
.\"
.\" Some handy macro definitions [from Tom Christensen's man(1) manual page].
.\"
.de SB		\" small and bold
.if !"\\$1"" \\s-2\\fB\&\\$1\\s0\\fR\\$2 \\$3 \\$4 \\$5
..
.\"
.de T		\" switch to typewriter font
.ft CW		\" probably want CW if you don't have TA font
..
.\"
.de TY		\" put $1 in typewriter font
.if t .T
.if n ``\c
\\$1\c
.if t .ft P
.if n \&''\c
\\$2
..
.\"
.de M		\" man page reference
\\fI\\$1\\fR\\|(\\$2)\\$3
..
.TH QSTAT 1 "$Date: 2009/11/05 13:18:36 $" "xxRELxx" "xxQS_NAMExx User Commands"
.SH NAME
qstat \- show the status of xxQS_NAMExx jobs and queues
.\"
.\"
.SH SYNTAX
.B qstat
[
.B -ext
] [
.B -cb
] [
.B -f
] [ \fB\-F\fP [\fBresource_name,...\fP]
] [
.B -g {c|d|t}[+]
] [
.B -help
] [
.B -j [job_list]
] [
.B -l resource=val,...
] [
.B -ne
] [
.B -pe pe_name,...
] [
.B -pri 
] [
.B -q wc_queue_list
] [
.B -qs {a|c|d|o|s|u|A|C|D|E|S}
] [
.B -r
] [
.B -s {r|p|s|z|hu|ho|hs|hd|hj|ha|h|a}[+]
] [
.B -t
] [
.B -U user,...
] [
.B -u user,...
] [
.B -urg
] [
.B -xml
]
.\"
.SH DESCRIPTION
.I qstat
shows the current status of the available xxQS_NAMExx queues and the
jobs associated with the queues. Selection options allow you
to get information about specific jobs, queues or users.
If multiple selections are done a queue is only displayed if all
selection criteria for a queue instance are met.
Without any option
.I qstat
will display only a list of jobs with no queue status
information.
.PP
The administrator and the user may define files (see
.M sge_qstat 5 ),
which can contain any of the options described below. A cluster-wide sge_qstat
file may be  placed under
$xxQS_NAME_Sxx_ROOT/$xxQS_NAME_Sxx_CELL/common/sge_qstat
The user private  file is searched at the location
$HOME/.sge_qstat.
The home directory request file has the highest precedence over
the cluster global file.
Command line can be used to override the flags contained in the files.
.\"
.SH OPTIONS
.IP "\fB\-cb\fP"
In combination with \fB\-cb\fP the output of this command will additionally
contain the information of a requested binding and
the changes that have been applied to the topology string (real
binding) for the host where this job is running. This additional 
information will appear in combination with the parameters 
\fB\-r\fP and \fB\-j\fP.
.sp
Please note that this command line switch will be removed with
the next major release.
.\"
.IP "\fB\-explain a|A|c|E\fP"
\'c' displays the reason for the c(onfiguration ambiguous) state of a queue
instance. 'a' shows the reason for the alarm state. Suspend alarm state
reasons will be displayed by 'A'. 'E' displays the reason for a queue
instance error state.
.sp
The output format for the alarm reasons is one line per reason containing
the resource value and threshold. For details about the resource value please
refer to the description of the \fBFull Format\fP in section \fBOUTPUT FORMATS\fP below.
.IP "\fB\-ext\fP"
Displays additional information for each job related to the job ticket policy scheme 
(see OUTPUT FORMATS below).
.\"
.IP "\fB\-f\fP"
Specifies a "full" format display of information.
The \fB\-f\fP option causes summary
information on all queues to be displayed along with the
queued job list.
.\"
.IP "\fB\-F\fP [ \fBresource_name,...\fP ]"
Like in the case of \fB\-f\fP information is displayed on all jobs as well as 
queues. In addition,
.I qstat
will present a detailed listing of the current 
resource availability per queue with respect to all resources (if the option 
argument is omitted) or with respect to those resources contained in the 
resource_name list. Please refer to the description of the
\fBFull Format\fP in 
section \fBOUTPUT FORMATS\fP below for further detail.
.\"
.IP "\fB\-g {c|d|t}[+]\fP"
The \fB\-g\fP option allows for controlling grouping of displayed
objects.
.sp
With \fB\-g c\fP a cluster queue summary is displayed. Find  more information
in the section \fBOUTPUT FORMATS\fP. 
.sp
With \fB\-g d\fP array jobs are displayed verbosely in a one 
line per job task fashion. By default, array jobs are grouped and all 
tasks with the same status (for pending tasks only) are displayed in a 
single line. The array job task id range field in the output (see section
\fBOUTPUT FORMATS\fP) specifies the corresponding set of tasks.
.sp
With \fB\-g t\fP parallel jobs are displayed verbosely in a one line 
per parallel job task fashion. By  default, parallel job tasks are
displayed in a single line. Also with \fB\-g t\fP option the function of each 
parallel task is displayed rather than the jobs slot amount (see section
\fBOUTPUT FORMATS\fP).
.sp 1
.\"
.IP "\fB\-help\fP"
Prints a listing of all options.
.\"
.IP "\fB\-j [job_list]\fP"
Prints either for all pending jobs or the jobs contained in job_list 
various information. The job_list can contain job_ids, job_names, or 
wildcard expression
.M sge_types 1 . 
.sp
For jobs in E(rror) state the error reason is displayed. For jobs that
could not be dispatched during in the last scheduling interval the 
obstacles are shown, if 'schedd_job_info' in 
.M sched_conf 5 
is configured accordingly.
.sp
For running jobs available information on resource utilization is shown
about consumed cpu time in seconds, integral memory usage in Gbytes 
seconds, amount of data transferred in io operations, current virtual 
memory utilization in Mbytes, and maximum virtual memory utilization in 
Mbytes. This information is not available if resource utilization 
retrieval is not supported for the OS platform where the job is hosted.
.sp
In combination with \fB\-cp\fP the output of this command will additionally
contain the information of a requested binding (see \fB\-binding\fP of
.M qsub 1 ) 
and the changes that have been applied to the topology string (real
binding) for the host where this job is running.
.sp
The topology string will contain capital letters for all those cores
that were not bound to the displayed job. Bound cores will be shown
lowercase (E.g "SCCcCSCCcC" means that core 2 on the two available
sockets where bound to this job). 
.sp
Please refer to the file
<xxqs_name_sxx_root>/doc/load_parameters.asc for detailed information on the
standard set of load values.
.\"
.IP "\fB\-l resource\fP[\fB=value\fP],..."
Defines the resources required by the jobs or granted by the 
queues on which information is requested. Matching is performed 
on queues based on non-mutable resource availability information 
only. That means load values are always ignored except the 
so-called static load values (i.e. "arch", "num_proc", "mem_total", "swap_total" and 
"virtual_total"). Consumable utilization is also ignored.
The pending jobs are restricted to jobs that might run in 
one of the above queues. In a similar fashion also the queue-job
matching bases only on non-mutable resource availability 
information.
If there are multiple -l resource requests they will be concatenated by
a logical AND: a queue needs to match all resources to be displayed.
.\"
.IP "\fB\-ne\fP"
In combination with \fB\-f\fP the option suppresses the display of empty 
queues. This means all queues where actually no jobs are running are not
displayed.
.\"
.IP "\fB\-pe pe_name,...\fP"
Displays status information with respect to queues which are attached to 
at least one of the parallel environments enlisted in the comma separated 
option argument. Status information for jobs is displayed either for those 
which execute in one of the selected queues or which are pending and 
might get scheduled to those queues in principle.
\"
.IP "\fB\-pri\fP"
Displays additional information for each job related to the job priorities in 
general.
(see OUTPUT FORMATS below).
.\"
.IP "\fB\-q wc_queue_list\fP"
Specifies a wildcard expression queue list to which job
information is to be displayed. Find the definition of \fBwc_queue_list\fP
in
.M sge_types 1 .
.\"
.IP "\fB\-qs {a|c|d|o|s|u|A|C|D|E|S}\fP"
Allows for the filtering of queue instances according to state.
.\"
.IP "\fB\-r\fP"
Prints extended information about the resource requirements
of the displayed jobs. 
.sp
In combination with \fB\-cb\fP the output of this command will contain
additional information concerning the requested binding for a job.
(see \fB\-binding\fP of
.M qsub 1 ).
.sp
Please refer to the \fBOUTPUT FORMATS\fP
sub-section \fBExpanded Format\fP below for detailed information.
.\"
.IP "\fB\-s {p|r|s|z|hu|ho|hs|hd|hj|ha|h|a}[+]\fP"

Prints only jobs in the specified state, any combination of states is
possible. \fB\-s prs\fP corresponds to the regular
.I qstat
output without \fB\-s\fP
at all. To show recently finished jobs, use \fB\-s z\fP.
To display jobs in user/operator/system/array-dependency hold,
use the \fB\-s hu/ho/hs/hd\fP 
option. The 
\fB\-s ha\fP option shows jobs which where
submitted with the 
.I qsub 
\fB\-a\fP command. 
.I qstat 
\fB\-s hj\fP 
displays all jobs which are not eligible for execution unless the job
has entries in the job dependency list.
.I qstat 
\fB\-s h\fP
is an abbreviation for
.I qstat 
\fB\-s huhohshdhjha\fP
and 
.I qstat 
\fB\-s a\fP is an abbreviation for
.I qstat 
\fB\-s psr\fP
(see \fB\-a\fP, \fB\-hold_jid\fP 
and \fB\-hold_jid_ad\fP options to
.M qsub 1 ).
.\"
.IP "\fB\-t\fP"
Prints extended information about the controlled sub-tasks
of the displayed parallel jobs. Please refer to the \fBOUTPUT FORMATS\fP
sub-section \fBReduced Format\fP below for detailed information. Sub-tasks
of parallel jobs should not be confused with array job tasks (see \fB\-g\fP
option above and \fB\-t\fP option to
.M qsub 1 ).
.\"
.IP "\fB\-U user,...\fP"
Displays status information with respect to queues to which the specified 
users have access. Status information for jobs is displayed either for those 
which execute in one of the selected queues or which are pending and 
might get scheduled to those queues in principle.
.\"
.IP "\fB\-u user,...\fP"
Display information only on those jobs and queues
being associated with the users from the given user list.
Queue status information is displayed if the \fB\-f\fP or \fB\-F\fP
options are specified additionally and if the user runs
jobs in those queues. 
.sp
The string
\fB\ $user\fP
is a placeholder for the current username. An asterisk "*" can be used 
as username wildcard to request any users' jobs be displayed. The default
value for this switch is \fB\-u $user\fP.
\"
.IP "\fB\-urg\fP"
Displays additional information for each job related to the job urgency policy scheme
(see OUTPUT FORMATS below).
.\"
.IP "\fB\-xml\fP"
This option can be used with all other options and changes the output to XML. The used
schemas are referenced in the XML output. The output is printed to stdout.
For more detailed information, the schemas for the qstat command can be found
in $SGE_ROOT/util/resources/schemas/qstat.
.sp
If the \fB\-xml\fP parameter is combined with \fB\-cb\fP then the XML output will
contain additional tags containing information about job to core binding.
You can also find schema files with the suffix "_cb" in the directory 
$SGE_ROOT/util/resources/schemas/qstat that describe that changes.
.br
.\"
.\"
.SH "OUTPUT FORMATS"
Depending on the presence or absence of the \fB-explain\fP, \fB\-f\fP, \fB\-F\fP, or \fB\-qs\fP and
\fB\-r\fP and \fB\-t\fP option three output formats need to be differentiated.
.PP
The \fB\-ext\fP and \fB\-urg\fP options may be used 
to display additional information for each job.
.\"
.SS "\fBCluster Queue Format (with \-g c)\fP"
Following the header line a section for each cluster queue
is provided. When queue instances selection are applied (\-l \-pe, \-q, \-U)
the cluster format contains only cluster queues of the corresponding queue
instances.
.IP "\(bu" 3n
the cluster queue name.
.IP "\(bu" 3n
an average of the normalized load average of all queue hosts. In order 
to reflect each hosts different significance the number of configured 
slots is used as a weighting factor when determining cluster queue load. 
Please note that only hosts with a np_load_value are considered for this 
value. When queue selection is applied only data about selected queues 
is considered in this formula. If the load value is not available at 
any of the hosts '-NA-' is printed instead of the value from the complex 
attribute definition.
.IP "\(bu" 3n
the number of currently used slots. 
.IP "\(bu" 3n
the number of slots reserved in advance. 
.IP "\(bu" 3n
the number of currently available slots.
.IP "\(bu" 3n
the total number of slots.
.IP "\(bu" 3n
the number of slots which is in at least one of the states  'aoACDS' and in
none of the states 'cdsuE'
.IP "\(bu" 3n
the number of slots which are in one of these states or in any  combination 
of them: 'cdsuE'
.IP "\(bu" 3n
the \fB\-g c\fP option can be used in combination with \fB\-ext\fP. In this
case, additional columns are added to the output. Each column contains
the slot count for one of the available queue states.
.SS "\fBReduced Format (without \-f, \-F, and \-qs)\fP"
Following the header line a line is printed for each job
consisting of
.IP "\(bu" 3n
the job ID.
.IP "\(bu" 3n
the priority of the job determining its position in the pending jobs list.
The priority value is determined 
dynamically based on ticket and urgency policy set-up (see also
.M sge_priority 5 
).
.IP "\(bu" 3n
the name of the job.
.IP "\(bu" 3n
the user name of the job owner.
.IP "\(bu" 3n
the status of the job \- one of d(eletion), E(rror), h(old), r(unning),
R(estarted), s(uspended), S(uspended), t(ransfering), T(hreshold) or w(aiting).
.sp 1
The state d(eletion) indicates that a 
.M qdel 1 
has been used to initiate job deletion. 
The states t(ransfering) and r(unning) indicate that a job is about to
be executed or is already executing, whereas the states s(uspended),
S(uspended) and T(hreshold) show that an already running jobs has been
suspended. The s(uspended) state is caused by suspending the job via the
.M qmod 1
command, the S(uspended) state indicates that the queue containing the job
is suspended and therefore the job is also suspended and the T(hreshold)
state shows that at least one suspend threshold of the corresponding queue
was exceeded (see
.M queue_conf 5 )
and that the job has been suspended as a consequence. The state R(estarted)
indicates that the job was restarted. This can be caused by a job migration or
because of one of the reasons described in the -r section of the
.M qsub 1
command. 
.sp 1
The states w(aiting) and h(old) only appear for pending jobs. The h(old)
state indicates that a job currently is not eligible for execution due to
a hold state assigned to it via
.M qhold 1 ,
.M qalter 1
or the
.M qsub 1
\fB\-h\fP option or that the job is waiting for completion of the jobs
to which job dependencies have been assigned to the job via the
\fB\-hold_jid\fP or \fB\-hold_jid-ad\fP options of
.M qsub 1
or
.M qalter 1 .
.sp 1
The state E(rror) appears for pending jobs that couldn't be started due to 
job properties. The reason for the job error is shown by the 
.M qstat 1 
\fB\-j job_list\fP
option.
.IP "\(bu" 3n
the submission or start time and date of the job.
.IP "\(bu" 3n
the queue the job is assigned to (for running or suspended
jobs only).
.IP "\(bu" 3n
the number of job slots or the function of parallel job tasks 
if \fB\-g t\fP is specified.
.sp 
Without \fB\-g t\fP option the total number of slots occupied resp. requested by the job 
is displayed. For pending parallel jobs with a PE slot range request,
the assumed future slot allocation is displayed.
With \fB\-g t\fP option the function of the running jobs (MASTER or SLAVE \- the 
latter for parallel jobs only) is displayed.
.IP "\(bu" 3n
the array job task id. Will be empty for non-array jobs. See the
\fB\-t\fP option to
.M qsub 1
and the \fB\-g\fP above for additional information.
.\"
.PP
If the \fB\-t\fP option is supplied, each status line always contains
parallel job task information as if \fB\-g t\fP were specified and
each line contains the following parallel job subtask information:
.IP "\(bu" 3n
the parallel task ID (do not confuse parallel tasks with array job tasks),
.IP "\(bu" 3n
the status of the parallel task \- one of 
r(unning), R(estarted), s(uspended), S(uspended), T(hreshold), w(aiting),
h(old), or x(exited).
.IP "\(bu" 3n
the cpu, memory, and I/O usage,
.IP "\(bu" 3n
the exit status of the parallel task,
.IP "\(bu" 3n
and the failure code and message for the parallel task.
.SS "\fBFull Format (with \-f and \-F)\fP"
Following the header line a section for each queue separated
by a horizontal line is provided. For each queue the information
printed consists of
.IP "\(bu" 3n
the queue name,
.IP "\(bu" 3n
the queue type \- one of B(atch), I(nteractive), C(heckpointing),
P(arallel), T(ransfer) or combinations thereof or N(one),
.IP "\(bu" 3n
the number of used and available job slots,
.IP "\(bu" 3n
the load average of the queue host,
.IP "\(bu" 3n
the architecture of the queue host and
.IP "\(bu" 3n
the state of the queue \- one of
u(nknown) if the corresponding
.M xxqs_name_sxx_execd 8
cannot be contacted, a(larm), A(larm), C(alendar suspended), s(uspended),
S(ubordinate), d(isabled), D(isabled), E(rror) or 
combinations thereof.
.PP
If the state is a(larm) at least on of the load thresholds defined in the 
\fIload_thresholds\fP list of the queue configuration (see
.M queue_conf 5 )
is 
currently exceeded, which prevents from scheduling further jobs to that 
queue.
.PP
As opposed to this, the state A(larm) indicates that at least one of the
suspend thresholds of the queue (see
.M queue_conf 5 )
is currently exceeded. This will result in jobs running in that queue being
successively suspended until no threshold is violated.
.PP
The states s(uspended) and d(isabled) can be assigned to queues and
released via the
.M qmod 1
command. Suspending a queue will cause all jobs executing in that queue to
be suspended.
.PP
The states D(isabled) and C(alendar suspended) indicate that the queue 
has been disabled or suspended automatically via the calendar facility of 
xxQS_NAMExx (see
.M calendar_conf 5 ),
while the S(ubordinate) state 
indicates, that the queue has been suspend via subordination to another 
queue (see
.M queue_conf 5
for details). When suspending a queue 
(regardless of the cause) all jobs executing in that queue are suspended 
too.
.PP
If an E(rror) state is displayed for a queue,
.M xxqs_name_sxx_execd 8
on that host was unable to locate the
.M xxqs_name_sxx_shepherd 8
executable
on that host in order to start a job. Please check the
error logfile of that
.M xxqs_name_sxx_execd 8
for leads on how to resolve the problem. Please enable the
queue afterwards via the \fB-c\fP option of the
.M qmod 1
command manually.
.PP
If the c(onfiguration ambiguous) state is displayed for a queue
instance this indicates that the configuration specified for this
queue instance in
.M sge_conf 5
is ambiguous. This state is cleared when
the configuration becomes unambiguous again. This state prevents further jobs
from being scheduled to that queue instance. Detailed reasons why
a queue instance entered the c(onfiguration ambiguous) state can
be found in the
.M sge_qmaster 8
messages file and are shown by the
qstat -explain switch. For queue instances in this state the cluster
queue's default settings are used for the ambiguous attribute.
.PP
If an o(rphaned) state is displayed for a queue instance, it
indicates that the queue instance is no longer demanded by the current
cluster queue's configuration or the host group configuration.
The queue instance is kept because jobs which not yet finished
jobs are still associated with it, and it will vanish from qstat output
when these jobs have finished. To quicken vanishing of an orphaned
queue instance associated job(s) can be deleted using 
.M qdel 1 .
A queue instance in (o)rphaned state can be revived by changing
the cluster queue configuration accordingly to cover that queue
instance. This state prevents from scheduling further jobs to that
queue instance.
.PP
If the \fB\-F\fP option was used, resource availability information is printed 
following the queue status line. For each resource (as selected in an option 
argument to \fB\-F\fP or for all resources if the option argument was
omitted) a single line is displayed with the following format:
.IP "\(bu" 3n
a one letter specifier indicating whether the current resource availability 
value was dominated by either
.br
`\fBg\fP' - a cluster global,
.br
`\fBh\fP' - a host total or
.br
`\fBq\fP' - a queue related resource consumption.
.IP "\(bu" 3n
a second one letter specifier indicating the source for the current resource 
availability value, being one of
.br
`\fBl\fP' - a load value reported for the
resource,
.br
`\fBL\fP' - a load value for the resource after administrator
defined load scaling has been applied,
.br
`\fBc\fP' - availability derived from
the consumable resources facility (see
.M complexes 5 ),
.br
`\fBf\fP' - a fixed 
availability definition derived from a non-consumable complex attribute or 
a fixed resource limit.
.IP "\(bu" 3n
after a colon the name of the resource on which information is displayed.
.IP "\(bu" 3n
after an equal sign the current resource availability value.
.PP
The displayed availability values and the sources from which they derive are 
always the minimum values of all possible combinations. Hence, for example,
a line of the form "qf:h_vmem=4G" indicates that a queue currently has a 
maximum availability in virtual memory of 4 Gigabyte, where this value is a 
fixed value (e.g. a resource limit in the queue configuration) and it is queue 
dominated, i.e. the host in total may have more virtual memory available than 
this, but the queue doesn't allow for more. Contrarily a line "hl:h_vmem=4G" 
would also indicate an upper bound of 4 Gigabyte virtual memory 
availability, but the limit would be derived from a load value currently 
reported for the host. So while the queue might allow for jobs with higher 
virtual memory requirements, the host on which this particular queue resides 
currently only has 4 Gigabyte available.
.PP
If the \fB\-explain\fP option was used with the character 'a' or 'A', 
information about resources is displayed, that
violate load or suspend thresholds.
.br
The same format as with the \fB-F\fP option is used with following extensions:
.IP "\(bu" 3n
the line starts with the keyword `alarm'
.br
.IP "\(bu" 3n
appended to the resource value is the type and value of the appropriate threshold
.PP
After the queue status line (in case of \fB\-f\fP) or the resource
availability information (in case of \fB\-F\fP) a single line is printed
for each job running currently in this queue. Each job status
line contains
.IP "\(bu" 3n
the job ID,
.IP "\(bu" 3n
the priority of the job determining its position in the pending jobs list.
The priority value is determined 
dynamically based on ticket and urgency policy set-up (see also
.M sge_priority 5 
).
.IP "\(bu" 3n
the job name,
.IP "\(bu" 3n
the job owner name,
.IP "\(bu" 3n
the status of the job \- one of t(ransfering),
r(unning), R(estarted), s(uspended), S(uspended) or T(hreshold) (see the
\fBReduced Format\fP section for detailed information),
.IP "\(bu" 3n
the submission or start time and date of the job.
.IP "\(bu" 3n
the number of job slots or the function of parallel job tasks 
if \fB\-g t\fP is specified.
.sp 
Without \fB\-g t\fP option the number of slots occupied per queue resp. requested by the job 
is displayed. For pending parallel jobs with a PE slot range request,
the assumed future slot allocation is displayed.
With \fB\-g t\fP option the function of the running jobs (MASTER or SLAVE \- the 
latter for parallel jobs only) is displayed.
.PP
If the \fB\-t\fP option is supplied, each job status line also contains
.IP "\(bu" 3n
the task ID,
.IP "\(bu" 3n
the status of the task \- one of 
r(unning), R(estarted), s(uspended), S(uspended), T(hreshold), w(aiting),
h(old), or x(exited) (see the
\fBReduced Format\fP section for detailed information),
.IP "\(bu" 3n
the cpu, memory, and I/O usage,
.IP "\(bu" 3n
the exit status of the task,
.IP "\(bu" 3n
and the failure code and message for the task.
.PP
Following the list of queue sections a \fIPENDING JOBS\fP list may
be printed in case jobs are waiting for being assigned to a queue.
A status line for each waiting job is displayed being similar to
the one for the running jobs. The differences are that the status
for the jobs is w(aiting) or h(old), that the submit time and date
is shown instead of the start time and that no function
is displayed for the jobs.
.PP
In very rare cases, e.g. if
.M xxqs_name_sxx_qmaster 8
starts up from an inconsistent state in the job or queue spool
files or if the \fBclean queue\fP (\fB\-cq\fP) option of
.M qconf 1
is used,
.I qstat
cannot assign jobs to either the running or pending jobs section
of the output. In this case as job status inconsistency (e.g. a
job has a running status but is not assigned to a queue) has been
detected. Such jobs are printed in an \fIERROR JOBS\fP section at the
very end of the output. The ERROR JOBS section should disappear
upon restart of
.M xxqs_name_sxx_qmaster 8 .
Please contact your xxQS_NAMExx support representative if you feel
uncertain about the cause or effects of such jobs.
.\"
.SS "\fBExpanded Format (with \-r)\fP"
If the \fB\-r\fP option was specified together with \fIqstat\fP,
the following information for each displayed job is printed (a single line
for each of the following job characteristics):
.IP "\(bu" 3n
The job and master queue name.
.IP "\(bu" 3n
The hard and soft resource requirements of the job as specified
with the
.M qsub 1
\fB\-l\fP option. The per resource 
addend when determining the jobs urgency contribution value is 
printed (see also 
.M sge_priority 5 ).
.IP "\(bu" 3n
The requested parallel environment including the
desired queue slot range (see \fB\-pe\fP option of
.M qsub 1 ).
.IP "\(bu" 3n
The requested checkpointing environment of the job (see the
.M qsub 1
\fB\-ckpt\fP option).
.IP "\(bu" 3n
In case of running jobs, the granted
parallel environment with the granted number of queue slots.
.IP "\(bu" 3n
If \fB\-cb\fP was specified the requested job binding
parameters.
.\"
.SS "\fBEnhanced Output (with \-ext)\fP"
For each job the following additional items are displayed:
.\"
.IP "\fBntckts\fP"
The total number of tickets in normalized fashion.
.\"
.IP "\fBproject\fP"
The project to which the job is assigned as specified in the
.M qsub 1
\fB\-P\fP option.
.\"
.IP "\fBdepartment\fP"
The department, to which the user belongs (use the \fB\-sul\fP and
\fB\-su\fP options of
.M qconf 1
to display the current department definitions).
.\"
.IP "\fBcpu\fP"
The current accumulated CPU usage of the job in seconds.
.\"
.IP "\fBmem\fP"
The current accumulated memory usage of the job in Gbytes seconds.
.\"
.IP "\fBio\fP"
The current accumulated IO usage of the job.
.\"
.IP "\fBtckts\fP"
The total number of tickets assigned to the job currently
.\"
.IP "\fBovrts\fP"
The override tickets as assigned by the \fB\-ot\fP option of
.M qalter 1 .
.\"
.IP "\fBotckt\fP"
The override portion of the total number of tickets assigned to the
job currently
.\"
.IP "\fBftckt\fP"
The functional portion of the total number of tickets assigned to the
job currently
.\"
.IP "\fBstckt\fP"
The share portion of the total number of tickets assigned to the
job currently
.\"
.IP "\fBshare\fP"
The share of the total system to which the job is entitled currently.
.\"
.SS "\fBEnhanced Output (with \-urg)\fP"
For each job the following additional urgency policy related items are 
displayed (see also
.M sge_priority 5 ):
.\"
.IP "\fBnurg\fP"
The jobs total urgency value in normalized fashion.
.\"
.IP "\fBurg\fP"
The jobs total urgency value.
.\"
.IP "\fBrrcontr\fP"
The urgency value contribution that reflects the urgency
that is related to the jobs overall resource requirement.
.\"
.IP "\fBwtcontr\fP"
The urgency value contribution that reflects the urgency related to
the jobs waiting time.
.\"
.IP "\fBdlcontr\fP"
The urgency value contribution that reflects the urgency related to
the jobs deadline initiation time.
.\"
.IP "\fBdeadline\fP"
The deadline initiation time of the job as specified with the
.M qsub 1
\fB\-dl\fP option.
.\"
.SS "\fBEnhanced Output (with \-pri)\fP"
For each job, the following additional job priority related items are 
displayed (see also
.M sge_priority 5 ):
.\"
.IP "\fBnurg\fP"
The job's total urgency value in normalized fashion.
.\"
.IP "\fBnpprior\fP"
The job's \fB\-p\fP priority in normalized fashion.
.\"
.IP "\fBntckts\fP"
The job's ticket amount in normalized fashion.
.\"
.IP "\fBppri\fP"
The job's \fB\-p\fP priority as specified by the user.
.\"
.\"
.SH "ENVIRONMENTAL VARIABLES"
.\" 
.IP "\fBxxQS_NAME_Sxx_ROOT\fP" 1.5i
Specifies the location of the xxQS_NAMExx standard configuration
files.
.\"
.IP "\fBxxQS_NAME_Sxx_CELL\fP" 1.5i
If set, specifies the default xxQS_NAMExx cell. To address a xxQS_NAMExx
cell
.I qstat
uses (in the order of precedence):
.sp 1
.RS
.RS
The name of the cell specified in the environment 
variable xxQS_NAME_Sxx_CELL, if it is set.
.sp 1
The name of the default cell, i.e. \fBdefault\fP.
.sp 1
.RE
.RE
.\"
.IP "\fBxxQS_NAME_Sxx_DEBUG_LEVEL\fP" 1.5i
If set, specifies that debug information
should be written to stderr. In addition the level of
detail in which debug information is generated is defined.
.\"
.IP "\fBxxQS_NAME_Sxx_QMASTER_PORT\fP" 1.5i
If set, specifies the tcp port on which
.M xxqs_name_sxx_qmaster 8
is expected to listen for communication requests.
Most installations will use a services map entry for the
service "sge_qmaster" instead to define that port.
.\"
.IP "\fBSGE_LONG_QNAMES\fP" 1.5i
Qstat does display queue names up to 30 characters. If that is
to much or not enough, one can set a custom length with this
variable. The minimum display length is 10 characters. If one does
not know the best display length, one can set SGE_LONG_QNAMES to
-1 and qstat will figure out the best length.
.\"
.\"
.SH FILES
.nf
.ta \w'<xxqs_name_sxx_root>/     'u
\fI<xxqs_name_sxx_root>/<cell>/common/act_qmaster\fP
	xxQS_NAMExx master host file
.ta \w'<xxqs_name_sxx_root>/     'u
\fI<xxqs_name_sxx_root>/<cell>/common/xxqs_name_sxx_qstat\fP
	cluster qstat default options
\fI$HOME/.xxqs_name_sxx_qstat\fR	
	user qstat default options
.fi
.\"
.\"
.SH "SEE ALSO"
.M xxqs_name_sxx_intro 1 ,
.M qalter 1 ,
.M qconf 1 ,
.M qhold 1 ,
.M qhost 1 ,
.M qmod 1 ,
.M qsub 1 ,
.M queue_conf 5 ,
.M xxqs_name_sxx_execd 8 ,
.M xxqs_name_sxx_qmaster 8 ,
.M xxqs_name_sxx_shepherd 8 .
.\"
.\"
.SH "COPYRIGHT"
See
.M xxqs_name_sxx_intro 1
for a full statement of rights and permissions.
