'\" t
.\"___INFO__MARK_BEGIN__
.\"
.\" Copyright: 2004-2007 by Sun Microsystems, Inc.
.\"
.\"___INFO__MARK_END__
.\"
.\" $RCSfile: sge_types.1,v $     Last Update: $Date: 2007/07/19 08:17:15 $     Revision: $Revision: 1.13.2.5 $
.\"
.\"
.\" Some handy macro definitions [from Tom Christensen's man(1) manual page].
.\"
.de SB		\" small and bold
.if !"\\$1"" \\s-2\\fB\&\\$1\\s0\\fR\\$2 \\$3 \\$4 \\$5
..
.\"
.de T		\" switch to typewriter font
.ft CW		\" probably want CW if you don't have TA font
..
.\"
.de TY		\" put $1 in typewriter font
.if t .T
.if n ``\c
\\$1\c
.if t .ft P
.if n \&''\c
\\$2
..
.\"
.de M		\" man page reference
\\fI\\$1\\fR\\|(\\$2)\\$3
..
.TH xxQS_NAME_Sxx_TYPES 1 "$Date: 2007/07/19 08:17:15 $" "xxRELxx" "xxQS_NAMExx User Commands"
.\"
.SH NAME
sge_types - xxQS_NAMExx type descriptions 
.\"
.SH DESCRIPTION
.\"
The xxQS_NAMExx
user interface consists of several programs and files. Some command-line 
switches and several file attributes are types. The syntax for these
types is explained in this page.
.PP
.\"
.\" expression        => a regular boolean expression
.\" pattern           => a pattern definition
.\" qdomain           => wc_qdomain without expression
.\" qinstance         => wc_qinstance without expression
.\" range             := n[-m[:s]][,n[-m[:s]],...]
.\" wc_host           := wildcard expression matching a host
.\" wc_hostgroup      := wildcard expression matching a hostgroup
.\" wc_job            := job-id|job-name|pattern
.\" wc_job_range      := wc_job[ -t range]
.\" wc_job_list       := wc_job[,wc_job,...]
.\" wc_job_range_list := wc_job_range[,wc_job_range,...]
.\" wc_qdomain        := wc_cqueue@wc_hostgroup
.\" wc_qinstance      := wc_cqueue@wc_host
.\" wc_queue          := wc_cqueue|wc_qdomain|wc_qinstance
.\" wc_queue_list     := wc_queue[,wc_queue,...]
.\" wc_user           := user_name|pattern
.\" wc_user_list      := wc_user[,wc_user,...]
.\" wc_project        := project|pattern
.\" wc_pe_name        := pe_name|pattern
.\"
.SH "OBJECT TYPES"
These types are used for defining xxQS_NAMExx configuration:
.\"
.SS "\fBcalendar_name\fP"
A calendar name is the name of a xxQS_NAMExx calendar described in
.M calendar_conf 5 . 
.PP
\fIcalendar_name\fP := \fIobject_name\fP
.fi
.\"
.SS "\fBckpt_name\fP"
A "ckpt_name" is the name of a xxQS_NAMExx checkpointing interface described in
.M checkpoint 5 . 
.PP
\fIckpt_name\fP := \fIobject_name\fP
.fi
.\"
.SS "\fBcomplex_name\fP"
A complex name is the name of a xxQS_NAMExx resource attribute described in 
.M complex 5 . 
.PP
\fIcomplex_name\fP := \fIobject_name\fP
.fi
.\"
.SS "\fBhost_identifier\fP"
A host identifier can be either a host name or a host group name. 
.PP
\fIhost_identifier\fP := \fIhost_name\fP | \fIhostgroup_name\fP
.fi
.\"
.SS "\fBhostgroup_name\fP"
A host group name is the name of a xxQS_NAMExx host group described in
.M hostgroup 5 .
Note, to allow host group names easily be differed from host names 
a "@" prefix is used.
.PP
\fIhostgroup_name\fP := @\fIobject_name\fP
.PP
.fi
.\"
.SS "\fBhost_name\fP"
A host name is the official name of a host node. Host names with a domain 
specification such as "gridmaster.sun.com" are called fully-qualified host names, 
whereas host names like "gridmaster" are called short host names. Note, there 
are the install time parameters default_domain and ignore_fqdn (see 
.M bootstrap 5 )
which affect how xxQS_NAMExx deals with host names in general. 
.fi
.\"
.SS "\fBmemory_specifier\fP"
Memory specifiers are positive decimal, hexadecimal or octal
integer  constants  which  may  be  followed by a multiplier
letter. Valid multiplier letters are k, K, m, M,  g  and  G,
where  k  means  multiply  the  value by 1000, K multiply by
1024, m multiply by 1000*1000, M multiply  by  1024*1024,  g
multiply by 1000*1000*1000 and G multiply by 1024*1024*1024.
If no multiplier is present, the value is  just  counted  in
bytes.
.\"
.SS "\fBpe_name\fP"
A "pe_name" is the name of a xxQS_NAMExx parallel environment described in
.M sge_pe 5 . 
.PP
\fIpe_name\fP := \fIobject_name\fP
.fi
.\"
.SS "\fBproject_name\fP"
A project name is the name of a xxQS_NAMExx project described in
.M project 5 . 
.PP
\fIproject_name\fP := \fIobject_name\fP
.fi
.\"
.SS "\fBqueue_name\fP"
A queue name is the name of a xxQS_NAMExx queue described in
.M queue_conf 5 .
.PP
\fIqueue_name \fP := \fIobject_name\fP
.fi
.\"
.SS "\fBtime_specifier\fP"
A time specifier either consists of a positive decimal, hexadecimal or 
octal integer constant, in which case the value is interpreted to be in 
seconds, or is built by 3 decimal integer numbers separated by colon 
signs where the first number counts the hours, the second the minutes 
and the third the seconds. If a number is zero it can be left 
out but the separating colon must remain (e.g. 1:0:1 = 1::1 means 1 
hours and 1 second).
.\"
.SS "\fBuser_name\fP"
A user name can be the name of a 
.M login 1 
user or of the xxQS_NAMExx user object described in
.M user 5 . 
.PP
\fIuser_name\fP := \fIobject_name\fP
.fi
.\"
.SS "\fBuserset_name\fP"
A user set name is the name of an xxQS_NAMExx access list or department described in
.M access_list 5 . 
.PP
\fIuserset_name\fP := \fIobject_name\fP
.fi
.\"
.SS "\fBobject_name\fP"
An object name is a sequence of up to 512 ASCII string characters except 
"\\n", "\\t", "\\r", " ", "/", ":", "\'", "\\", "[", "]", "{", "}", 
"|", "(", ")", "@", "%", "," or the " character itself.
.fi
.SH "MATCHING TYPES"
These types are used for matching xxQS_NAMExx configuration:
.\"
.\"
.SS "\fBexpression\fP"
A wildcard expression is a regular boolean expression that consists of
one or more \fIpattern\fPs joined by boolean operators. 
When a wildcard expression is used, the following definition applies:
.PP
.\"
.nf
.ta \w'XXXXXXXX'u
expression	= ["!"] ["("] valExp [")"] [ AND_OR expression ]*
valExp	= pattern | expression
AND_OR	= "&" | "|"
.fi
.PP
where:
.PP
.\"
.nf
.ta \w'XXXXXXXXXX'u
"!"	not operator -- negate the following pattern or expression 
"&"	and operator -- logically and with the following expression
"|"	or operator -- logically or with the following expression
"("	open bracket -- begin an inner expression.
")"	close bracket -- end an inner expression. 
"pattern"	see the \fIpattern\fP definition that's follow
.fi
.PP
.\"
The expression itself should be put inside quotes ('"') to ensure that
clients receive the complete expression.
.PP
.\"
.ta
e.g.
.RS
.nf
.ta \w'XXXXXXXXXXXXXXXXXX'u
"(lx*|sol*)&*64*" any string beginning with either "lx" or
                  "sol" and containing "64"
"rh_3*&!rh_3.1"   any string beginning with "rh_3", except
                  "rh_3.1"
.fi
.\"
.SS "\fBpattern\fP"
When patterns are used the following definitions apply:
.PP
.nf
.ta \w'XXXXXXXX'u
"*"	matches any character and any number of characters 
	(between 0 and inv).
"?"	matches any character. It must be a character other that the empty
	string
"."	is the character ".". It has no other meaning
"\\"	escape character. "\\\\" = "\\", "\\*" = "*", "\\?" = "?"
"[...]"	specifies an array or a range of allowed 
	characters for one character at a specific position.
        Character ranges may be specified using the a-z notation.
        The caret symbol (^) is \fBnot\fP interpreted as a logical
        not; it is interpreted literally.

For more details please see 
.M fnmatch 5
.\"

.fi
.PP
The pattern itself should be put inside quotes ('"') to ensure that
clients receive the complete pattern.
.PP
.SS "\fBrange\fP"
The task range specifier has the form 
.sp 1
n[-m[:s]][,n[-m[:s]], ...] 
or 
n[-m[:s]][ n[-m[:s]] ...] 
.sp 1
and thus consists of a comma or blank separated
list of range specifiers n[-m[:s]]. The ranges are concatenated to the
complete task id range. Each range may be a single number, a simple
range of the form n-m or a range with a step size.
.PP
.SS "\fBwc_host\fP"
A wildcard host specification (\fIwc_host\fP) is a 
wildcard expression which might match one or more hosts used in the cluster.
The first character of that string never begins with an at-character ('@'), even
if the expression begins with a wildcard character.
.PP
.\"
.nf
.ta
e.g.
.RS
.ta \w'XXXXXXXXXXXXX'u
*	all hosts
a*	all host beginning with an 'a'	
.fi
.\"
.SS "\fBwc_hostgroup\fP"
A wildcard hostgroup specification (\fIwc_hostgroup\fP) is a 
wildcard expression which might match one or more hostgroups.
The first character of that string is always an at-character ('@').
.PP
More information concerning hostgroups can be found in
.M hostgroup 5
.PP
.nf
.ta
e.g.
.RS
.ta \w'XXXXXXXXXXXXX'u
@*	all hostgroups in the cluster
@solaris	the @solaris hostgroup
.fi
.\"
.SS "\fBwc_job\fP"
The wildcard job specification is a placeholder for job ids, job names 
include job name pattern. A job id always references one
job, while the names and pattern might reference multiple jobs.
.sp 1
wc_job := job-id | job-name | pattern
.PP
.SS "\fBwc_job_range\fP"
The wildcard job range specification allows to reference specific array
tasks for one or multiple jobs. The job is referenced via wc_job and in
addition gets a range specifier for the array tasks.
.sp 1
wc_job_range := wc_job [ -t range]
.PP
.SS "\fBwc_job_list\fP"
The wildcard job list specification allows to reference multiple jobs 
with one command.
.PP
wc_job_list := wc_job [ , wc_job , ...]
.PP
.SS "\fBwc_job_range_list\fP"
The wildcard job range list (\fIwc_job_range_list\fP) is specified by 
one of the following forms:
.sp 1
.ta 0.5i
    \fIwc_job[ -t range][{, }wc_job[ -t range]{, }...]\fP
.ta 0.0i
.sp 1
If present, the \fItask_range\fP restricts the effect of the \fIqmod\fP
operation to the array job task range specified as suffix to the job id
(see the \fB\-t\fP option to
.M qsub 1
for further details on array jobs).
.PP
.SS "\fBwc_qdomain\fP"
\fIwc_qdomain\fP := \fIwc_cqueue\fP "@" \fIwc_hostgroup\fP
.PP
A wildcard expression queue domain specification (\fIwc_qdomain\fP) starts with a wildcard
expression cluster queue name (\fIwc_cqueue\fP) followed by an at-character '@' 
and a wildcard expression hostgroup specification (\fIwc_hostgroup\fP).
.PP
\fIwc_qdomain\fP are used to address a group of queue instances.
All queue instances residing on a hosts which is part of matching hostgroups
will be addressed. Please note, that \fIwc_hostgroup\fP always begins with
an at-character.
.PP
.nf
.ta
e.g.
.RS
.ta \w'XXXXXXXXXXXXX'u
*@@*	all queue instances whose underlying
	host is part of at least one hostgroup
a*@@e*	all queue instances beginning with an 'a' whose underlying
	host is part of at least one hostgroup beginning with 'e'
*@@solaris	all queue instances on hosts part of
	the @solaris hostgroup
.fi
.\"
.SS "\fBwc_cqueue\fP"
A wildcard expression cluster queue specification (\fIwc_cqueue\fP) is a 
wildcard expression which might match one or more cluster queues used in the cluster.
That string never contains an at-character ('@'), even if the expression begins with a 
wildcard character.
.PP
.\"
.nf
.ta
e.g.
.RS
.ta \w'XXXXXXXXXXXXX'u
*	all cluster queues
a*	all cluster queues beginning with an 'a'
a*&!adam	all cluster queues beginning with an 'a',but not adam
.fi
.\"
.SS "\fBwc_qinstance\fP"
\fIwc_qinstance\fP := \fIwc_cqueue\fP "@" \fIwc_host\fP
.PP
A wildcard expression queue instance specification (\fIwc_qinstance\fP) starts 
with a wildcard expression cluster queue name (\fIwc_cqueue\fP) followed by an 
at-character '@' and a wildcard expression hostname (\fIwc_host\fP).
.PP
\fIwc_qinstance\fP expressions are used to address a group
of queue instances whose underlying hostname matches the given expression.
Please note that the first character of \fIwc_host\fP does not match
the at-character '@'. 
.PP
.nf
.ta
e.g.
.RS
.ta \w'XXXXXXXXXXXXX'u
*@*	all queue instances in the cluster
*@b*	all queue instances whose 
	hostname begins with a 'b'
*@b*|c*	all queue instances whose 
	hostname begins with a 'b' or 'c'
.fi
.\"
.SS "\fBwc_queue\fP"
\fIwc_queue\fP := \fIwc_cqueue\fP | \fIwc_qdomain\fP | \fIwc_qinstance\fP 
.PP
A wildcard queue expression (\fIwc_queue\fP) might either be a wildcard expression 
cluster queue specification (\fIwc_cqueue\fP) or a wildcard expression queue domain
specification (\fIwc_qdomain\fP) or a wildcard expression queue instance specification
(\fIwc_qinstance\fP).
.PP
.nf
.ta 
e.g.
.RS
.ta \w'XXXXXXXXXXXXXXXXX'u
big_*1	cluster queues which begin with 
	"big_" and end with "1" 
big_*&!*1	cluster queues which begin with 
	"big_" ,but does not end with "1" 
*@fangorn	all qinstances residing on host 
	fangorn
.fi
.\"
.SS "\fBwc_queue_list\fP"
\fIwc_queue_list\fP := \fIwc_queue\fP ["," \fIwc_queue\fP "," ...]
.PP
Comma separated list of wc_queue elements.
.PP
e.g. 
.RS
big, medium_*@@sol*, *@fangorn.sun.com
.PP
.SS "\fBwc_user\fP"
A wildcard user name pattern is either a wildcard user name specification
or a full user name.
.PP
wc_user := user_name | pattern
.PP
.SS "\fbwc_user_list\fP"
A list of user names.
.PP
wc_user_list := wc_user [ , wc_user , ...]
.PP
.SS "\fBwc_project\fP"
A wildcard project name pattern is either a wildcard project name specification
or a full project name.
.PP
wc_project := project | pattern
.PP
.SS "\fBwc_pe_name\fP"
A wildcard parallel environment name pattern is either a wildcard PE name specification
or a full PE name.
.PP
wc_pe_name := pe_name | pattern
.PP
.\"
.SH SEE ALSO
.M qacct 1 ,
.M qconf 1 ,
.M qquota 1
.\"
.SH COPYRIGHT
Copyright: 2004-2007 by Sun Microsystems, Inc.
