'\" t
.\"___INFO__MARK_BEGIN__
.\"
.\" Copyright: 2001 by Sun Microsystems, Inc.
.\"
.\"___INFO__MARK_END__
.\"
.\" $RCSfile: submit.1,v $     Last Update: $Date: 2002/03/06 11:22:22 $     Revision: $Revision: 1.12 $
.\"
.\"
.\" Some handy macro definitions [from Tom Christensen's man(1) manual page].
.\"
.de SB		\" small and bold
.if !"\\$1"" \\s-2\\fB\&\\$1\\s0\\fR\\$2 \\$3 \\$4 \\$5
..
.\"
.de T		\" switch to typewriter font
.ft CW		\" probably want CW if you don't have TA font
..
.\"
.de TY		\" put $1 in typewriter font
.if t .T
.if n ``\c
\\$1\c
.if t .ft P
.if n \&''\c
\\$2
..
.\"
.de M		\" man page reference
\\fI\\$1\\fR\\|(\\$2)\\$3
..
.TH SUBMIT 1 "$Date: 2002/03/06 11:22:22 $" "xxRELxx" "xxQS_NAMExx User Commands"
.SH NAME
.IP "qsub   \-" 1i
submit a batch job to xxQS_NAMExx.
.IP "qsh    \-" 1i
submit an interactive X-windows session to xxQS_NAMExx.
.IP "qlogin \-" 1i
submit an interactive login session to xxQS_NAMExx.
.IP "qrsh   \-" 1i
submit an interactive rsh session to xxQS_NAMExx.
.IP "qalter \-" 1i
modify a pending batch job of xxQS_NAMExx.
.IP "qresub \-" 1i
submit a copy of an existing xxQS_NAMExx job.
.\"
.\"
.SH SYNTAX
.B qsub
[
.B options
] [
.B scriptfile | --
[
.B script_args
]]
.PP
.B qsh
[
.B options
] [
.B -- xterm_args
]
.PP
.B qlogin
[
.B options
]
.PP
.B qrsh
[
.B options
] [
.B command
[
.B command_args
]]
.PP
.B qalter
[
.B options
]
.B job/task_id_list
[
.B --
[
.B script_args
]]
.PP
.B qalter
[
.B options
]
.B -u user_list | -uall
[
.B --
[
.B script_args
]]   
.PP
.B qresub
[
.B options
]
.B job_id_list
.\"
.\"
.SH DESCRIPTION
.I Qsub
submits batch jobs to the xxQS_NAMExx queuing system. 
xxQS_NAMExx supports single and multiple node jobs.
\fBscriptfile\fP contains the commands to be
run by the job using a shell (for example,
.M sh 1
or
.M csh 1 ).
Arguments to the job script are given by \fBscript_args\fP.
xxQS_NAMExx flags may be entered as arguments to
.I qsub
or as embedded flags in the \fBscriptfile\fP if the first two
characters of a script line either match '#$' or are equal to the prefix
string defined with the \fB-C\fP option described below.
.PP
.I Qsh
submits an interactive X-windows session to xxQS_NAMExx. An
.M xterm 1
is brought up from the executing machine with the display directed either to
the X-server indicated by the DISPLAY environment variable or as specified 
with the \fI\-display qsh\fP option. Interactive jobs are not spooled if no
resource is 
available to execute them. They are either dispatched to a suitable machine 
for execution immediately or the user submitting the job is notified by
.I qsh 
that appropriate resources to execute the job are not available.
\fBxterm_args\fP are passed to the
.M xterm 1
executable.
.PP
.I Qlogin
is similar to
.I qsh
in that it submits an interactive job
to the queueing system. It does not open an
.M xterm 1
window on the
X display, but uses the current terminal for user I/O. Usually,
.I qlogin
establishes a
.M telnet 1
connection with the remote host, using
standard client- and server-side commands. These commands can
be configured with the \fBqlogin_daemon\fP (server-side,
xxQS_NAMExx
.I telnetd
if not set, otherwise something
like /usr/sbin/in.telnetd) and \fBqlogin_command\fP (client-side,
xxQS_NAMExx
.I telnet
if not set, otherwise
something like /usr/bin/telnet) parameters in the global and
local configuration settings of
.M xxqs_name_sxx_conf 5 .
The client side command is automatically
parameterized with the remote host name and port number to
connect to (i.e. resulting in an invocation like
/usr/bin/telnet my_exec_host 2442).
.I Qlogin
is invoked exactly like
.I qsh
and its jobs can only run on INTERACTIVE queues.
.I Qlogin
jobs can only be used if the
.M xxqs_name_sxx_execd 8
is running under the root account.
.PP
.I Qrsh
is similar to 
.I qlogin
in that it submits an interactive job to the queuing system. 
It uses the current terminal for user I/O. 
Usually,
.I qrsh 
establishes a 
.M rsh 1
connection with the remote host. If no command is given to \fIqrsh\fP, a 
.M rlogin 1
session is established.
The server-side commands used can be configured 
with the \fBrsh_daemon\fP and \fBrlogin_daemon\fP
parameters in the global and local configuration settings of 
.M xxqs_name_sxx_conf 5 .
A xxQS_NAMExx
.I rshd
or
.I rlogind
is used, if the parameters are not set or
otherwise something like /usr/sbin/in.rshd or /usr/sbin/in.rlogind.
On the client-side, the \fBrsh_command\fP and \fBrlogin_command\fP parameters
can be set in the global and local configuration settings of 
.M xxqs_name_sxx_conf 5 . 
If they are not set, special xxQS_NAMExx
.M rsh 1
and
.M rlogin 1
binaries delivered with xxQS_NAMExx are used.
Use the cluster configuration parameters to integrate mechanisms like
.I ssh
or the
.M rsh 1
and
.M rlogin 1
facilities supplied with the operating system.
.PP
.I Qrsh
jobs can only run in INTERACTIVE queues unless the option \fB-now no\fP is
used (see below).
They can only be used, if the 
.M xxqs_name_sxx_execd 8
is running under the root account.
.PP
.I Qrsh
provides an additional feature useful for the integration with
interactive tools providing a specific command shell. If the environment
variable
.B QRSH_WRAPPER
is set when
.I qrsh
is invoked, the command interpreter pointed to by
.B QRSH_WRAPPER
will be executed to run
.I qrsh
commands instead of the users login shell or any shell specified in the
.I qrsh
command-line.
.PP
.I Qalter
can be used to change the attributes of pending jobs. Once a job is 
executing, changes are no longer possible. For job arrays, for which a part
of the tasks can be pending and another part can be running (see the 
\fB\-t\fP option below), modifications with
.I qalter
only affect the pending tasks.
.I Qalter
can change most of the 
characteristics of a job (see the corresponding statements in the OPTIONS 
section below), including those which were defined as embedded flags in the 
script file (see above).
.PP
.I Qresub
allows to create jobs as copies from existing pending or running
jobs. The copied jobs will have exactly the same attributes as the ones
from which they are copied, but a new job ID. The only modification to the
copied jobs supported by qresub is to assign a hold state with the \fB\-h\fP
option. This can be used to first copy a job and then change its attributes
via \fIqalter\fP.
.PP
For \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, and \fIqlogin\fP
the administrator and the user may define
default request files (see
.M xxqs_name_sxx_request 5 )
which can contain any of the
options described below.
If an option in a default request file is understood by
.I qsub
and
.I qlogin
but not by
.I qsh
the option is silently ignored if
.I qsh
is invoked. Thus you can 
maintain shared default request files for both
.I qsub
and \fIqsh\fP.
.PP
A cluster wide default request file
may be placed under $xxQS_NAME_Sxx_ROOT/$xxQS_NAME_Sxx_CELL/common/xxqs_name_sxx_request.
User private default request files are processed under the
locations $HOME/.xxqs_name_sxx_request and $cwd/.xxqs_name_sxx_request. The working
directory local default request file has the highest precedence,
then the home directory located file and then the cluster global
file.
The option arguments, the embedded script flags and the options
in the default request files are
processed in the following order:
.PP
.RS
.nf
left to right in the script line,
left to right in the default request files,
from top to bottom of the script file (\fIqsub\fP only),
from top to bottom of default request files,
from left to right of the command line.
.fi
.RE
.PP
In other words, the command line can be used to override
the embedded flags and the default request settings.
The embedded flags, however, will override the default
settings.
.PP
\fBNote\fP, that the
.I -clear
option can be used to discard any previous settings at any
time in a default request file, in the embedded script flags, or
in a
command-line option. It is, however, not available with \fIqalter\fP.
.PP
The
options described below can be requested either hard or soft.
By default, all requests are considered hard until the \fB\-soft\fP option (see
below) is encountered. The hard/soft status remains in effect
until its counterpart is encountered again.
If all the hard requests for a job cannot 
be met, the job will not be scheduled.
Jobs which cannot be run at the present time
remain spooled.
.\"
.\"
.SH OPTIONS
.IP "\fB\-@ optionfile\fP"
Forces
\fIqsub\fP, \fIqrsh\fP, \fIqsh\fP, or \fIqlogin\fP
to use the
options contained in \fBoptionfile\fP. The indicated 
file may contain all valid
options. Comment lines are starting with a 
"#" sign.
.\"
.IP "\fB\-a date_time\fP"
Available for \fIqsub\fP and \fIqalter\fP only.
.sp 1
Defines or redefines
the time and date at which a job is eligible for execution. \fBDate_time\fP
conforms to [[CC]]YY]MMDDhhmm.[ss], where:
.sp 1
.nf
.ta \w'CC  'u
CC	denotes the century in 2 digits.
YY	denotes the year in 2 digits.
MM	denotes the month in 2 digits.
DD	denotes the day in 2 digits.
hh	denotes the hour in 2 digits.
mm	denotes the minute in 2 digits.
ss	denotes the seconds in 2 digits (default 00).
.fi
.sp 1
If any of the optional date fields is omitted, the corresponding value of
the current date is assumed.
.br
Usage of this option may cause unexpected results if the clocks of the
hosts in the xxQS_NAMExx pool are out of sync. Also, the proper behavior of
this option very much depends on the correct setting of the
appropriate timezone, e.g. in the TZ environment variable (see
.M date 1
for details), when the xxQS_NAMExx daemons
.M xxqs_name_sxx_qmaster 8
and
.M xxqs_name_sxx_execd 8
are invoked.
.sp 1
.I Qalter
allows changing this option even while the job executes. The modified
parameter will only be in effect after a restart or migration of the job,
however.
.\"
.IP "\fB\-ac variable[=value],...\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP and
\fIqalter\fP only.
.sp 1
Adds the given name/value pair(s) to the job's context. \fBValue\fP may be
omitted. xxQS_NAMExx appends the given argument to the list of context
variables for the job.
Multiple \fB\-ac\fP, \fB\-dc\fP, and \fB\-sc\fP options may be given.
The order is important here.
.sp 1
.I Qalter
allows changing this option even while the job executes.
.\"
.IP "\fB\-A account_string\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP and
\fIqalter\fP only.
.sp 1
Identifies the account to which the resource consumption of the job
should be charged. The \fBaccount_string\fP
may be any arbitrary ASCII alphanumeric string
but may contain no blank or separator characters. The
underbar '_' is considered a non-separator. In the absence of this
parameter xxQS_NAMExx 
will place the default account string "xxqs_name_sxx" in the accounting record
of the job.
.sp 1
.I Qalter
allows changing this option even while the job executes.
.\"
.IP "\fB\-c occasion_specifier\fP"
Available for \fIqsub\fP and \fIqalter\fP only.
.sp 1
Defines or redefines whether the job should be checkpointed, and if so,
under what circumstances. The specification of the checkpointing occasions
with this option overwrites the definitions of the \fIwhen\fP parameter in
the checkpointing environment (see
.M checkpoint 5 )
referenced by the \fIqsub \-ckpt\fP switch.
Possible values for \fBoccasion_specifier\fP are
.sp 1
.nf
.ta \w'<interval>  'u
n	no checkpoint is performed.
s	checkpoint when batch server is shut down.
m	checkpoint at minimum CPU interval.
x	checkpoint when job gets suspended.
<interval>	checkpoint in the specified time interval.
.fi
.sp 1
The minimum CPU interval is defined in the queue configuration (see
.M queue_conf 5
for details).
<interval> has to be specified in the format hh:mm:ss.
The maximum of <interval> and the queue's minimum CPU
interval is used if <interval> is specified. This is done to ensure
that a machine is not overloaded by checkpoints being generated too
frequently.
.\"
.IP "\fB\-ckpt ckpt_name\fP"
Available for \fIqsub\fP and \fIqalter\fP only.
.sp 1
Selects the checkpointing environment (see
.M checkpoint 5 )
to be used for 
a checkpointing the job. Also declares the job to be a checkpointing job. 
.\"
.IP "\fB\-clear\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, and \fIqlogin\fP
only.
.sp 1
Causes all elements of the job to be reset to the initial default status
prior to applying any modifications (if any) appearing in this specific
command.
.\"
.IP "\fB\-cwd\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP and
\fIqalter\fP only.
.sp 1
Execute the job from the current working directory.
This switch will activate xxQS_NAMExx's path aliasing facility, if the
corresponding
configuration files are present (see
.M xxqs_name_sxx_aliases 5 ).
.sp 1
In case of \fIqalter\fP, the previous definition of the current working
directory will be overwritten, if \fIqalter\fP is executed from a
different directory than the preceding \fIqsub\fP or \fIqalter\fP.
.sp 1
.I Qalter
allows changing this option even while the job executes. The modified
parameter will only be in effect after a restart or migration of the job,
however.
.\"
.IP "\fB\-C prefix_string\fP"
Available for \fIqsub\fP only.
.sp 1
.I Prefix_string
defines the prefix that declares a directive to
.I qsub
in the
job's scriptfile. The prefix is not a job attribute, but
affects the behavior of \fIqsub\fP. If the -C option is presented
with the value of the directive prefix as a null string,
.I qsub
will not scan the scriptfile
.br
The directive prefix consists of two ASCII characters which
when appearing in the first two bytes of a script line
indicate that what follows is a xxQS_NAMExx command
(default is "#$").
.br
The user should be aware that changing the first delimiter character can
produce unforeseen side effects. If the script file contains anything
other than a "#" character in the first byte position of the line, the shell
processor for the job will reject the line and may exit the job
prematurely.
.br
If the -C option is present in the script file, it is ignored.
.\"
.IP "\fB\-dc variable,...\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP and
\fIqalter\fP only.
.sp 1
Removes the given variable(s) from the job's context. 
Multiple \fB\-ac\fP, \fB\-dc\fP, and \fB\-sc\fP options may be given.
The order is important here.
.sp 1
.I Qalter
allows changing this option even while the job executes.
.\"
.IP "\fB\-display display_specifier\fP"
Available for \fIqsh\fP only.
.sp 1
Directs
.M xterm 1
to use
.B display_specifier
in order to contact the X server.
.\"
.IP "\fB\-dl date_time\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP and
\fIqalter\fP only.
This option is only supported in case of a 
xxQS_NAME_EExx system. It is not available for xxQS_NAME_Cxx systems.
.br
Specifies the deadline initiation time in [[CC]YY]DDhhmm[.SS] format (see
\fB\-a\fP option above). The deadline initiation time is the time at
which a deadline job has to reach top priority to be able to complete
within a given deadline. Before the deadline initiation time the
priority of a deadline job will be raised steadily until it reaches the
maximum as configured by the xxQS_NAMExx administrator.
.br
This option is applicable for users allowed to submit deadline jobs only.
.\"
.IP "\fB\-e [hostname:]path,...\fP"
Available for \fIqsub\fP and \fIqalter\fP only.
.sp 1
Defines or redefines
the path used for the standard error stream of the job. If
the \fBpath\fP constitutes an absolute path name, the
error-path attribute of the job is set to its value including
the \fBhostname\fP. If the path name is relative, xxQS_NAMExx
expands \fBpath\fP either with the current working directory
path in case the \fB\-cwd\fP (see above) switch is also
specified or with the home directory path otherwise. If 
\fBhostname\fP is present, the standard error stream will be
placed under the corresponding location if the job runs on
the specified host.
.sp 1
By default the file name for standard
error has the form \fIjob_name.\fPe\fIjob_id\fP and
\fIjob_name.\fPe\fIjob_id\fP.\fBtask_id\fP for job array tasks (see
\fB\-t\fP option below).
.sp 1
If \fBpath\fP is a directory, the standard error stream of the
job will be put in this directory under the default file name.
If the pathname contains certain pseudo environment variables,
their value will be expanded at runtime of the job and will be used
to constitute the standard error stream path name. The following
pseudo environment variables are supported currently:
.sp 1
.nf
.ta \w'$JOB_NAME   'u
$HOME	home directory on execution machine
$USER	user ID of job owner
$JOB_ID	current job ID
$JOB_NAME	current job name (see \fB\-N\fP option)
$HOSTNAME	name of the execution host
$TASK_ID	job array task index number
.fi
.sp 1
Alternatively to $HOME the tilde sign "~" can be used as common in
.M csh 1
or
.M ksh 1 .
Note, that the "~" sign also works in combination with user names,
so that "~<user>" expands to the home directory of <user>. Using
another user ID than that of the job owner
requires corresponding permissions, of course.
.sp 1
.I Qalter
allows changing this option even while the job executes. The modified
parameter will only be in effect after a restart or migration of the job,
however.
.\"
.IP "\fB\-hard\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP and
\fIqalter\fP only.
.sp 1
Signifies that all resource requirements following in the
command line will be hard requirements and must be satisfied
in full before a job can be scheduled.
.br
As xxQS_NAMExx scans the command line and script file for xxQS_NAMExx
options and parameters it builds a list of resources required
by a job. All such resource requests are considered as
absolutely essential for the job to commence. If the
\fB\-soft\fP option (see below) is encountered during the scan
then all following resources are designated as "soft
requirements" for execution, or "nice-to-have, but not
essential". If the \fB\-hard\fP flag is encountered at a later
stage of the scan, all resource requests following it once
again become "essential". The \fB\-hard\fP and \fB\-soft\fP
options in effect act as "toggles" during the scan.
.\"
.IP "\fB\-h | \-h {u|s|o|n|U|O|S}...\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP, \fIqalter\fP
and \fIqresub\fP.
.sp 1
List of holds to place on the job.
.sp 1
.nf
.ta \w'|u|  'u
`u'	denotes a user hold.
`s'	denotes a system hold.
`o'	denotes a operator hold.
`n'	denotes no hold.
.fi
.sp 1
As long as any hold other than `n' is assigned to the job
the job is not eligible for execution. Holds can be released
via
.I qalter
and
.M qrls 1 .
In case of
.I qalter
this is supported by the following additional option specifiers for 
the
.B \-h
switch:
.sp 1
.nf
.ta \w'|U|  'u
`U'	removes a user hold.
`S'	removes a system hold.
`O'	removes a operator hold.
.fi
.sp 1
xxQS_NAMExx managers can assign and remove all hold types, xxQS_NAMExx 
operators can assign and remove user and operator holds and users can 
only assign or remove user holds.
.sp 1
In the case of
.I qsub
only user holds can be placed on a job and thus only the first
form of the option with the \fB\-h\fP switch alone is allowed.
As opposed to this,
.I qalter
requires the second form described above.
.sp 1
An alternate means to assign hold is provided by the
.M qhold 1
facility.
.sp 1
If the job is a job array (see the \fB\-t\fP option below), all tasks
specified via \fB\-t\fP are affected by the \fB\-h\fP operation
simultaneously.
.\"
.sp 1
.I Qalter
allows changing this option even while the job executes. The modified
parameter will only be in effect after a restart or migration of the job,
however.
.IP "\fB\-help\fP"
Prints  a listing of all options.
.\"
.IP "\fB\-hold_jid [job_id|job_name],...\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP and
\fIqalter\fP only.
.sp 1
Defines or redefines the job dependency list of the submitted job. A 
reference by job name is only accepted if the referenced job is owend
by the same user as the refering job. The submitted job is not eligible 
for execution unless all jobs referenced in the coma separated job id 
and/or job name list have completed successfully.
.sp 1
.I Qalter
allows changing this option even while the job executes. The modified
parameter will only be in effect after a restart or migration of the job,
however.
.\"
.IP "\fB\-inherit\fP"
Available only for \fIqrsh\fP and
.M qmake 1 .
.sp 1
.I qrsh 
allows to start a task in an already scheduled parallel job.
The option \fB\-inherit\fP tells 
.I qrsh
to read a job id from the environment variable JOB_ID and start the 
specified command as a task in this job. Please note that in this case,
the hostname of the host where the command shall be executed, must precede 
the command to execute; the syntax changes to
.sp 1
.B qrsh \-inherit
[
.B other options
] 
.B hostname command 
[ 
.B command_args 
]
.sp 1
Note also, that in combination with \fB\-inherit\fP, most other command
line options will be ignored.
Only the options \fB\-verbose\fP, \fB\-v\fP and \fB\-V\fP 
will be interpreted. 
As a replacement to option \fB\-cwd\fP please use \fB\-v PWD\fP.
.sp 1
Usually a task should have the same environment (including the current 
working directory) as the corresponding job, so specifying the option
\fB\-V\fP should be suitable for most applications.
.sp 1
\fINote:\fP If in your system the commd port is not configured as service, but via environment
variable COMMD_PORT, make sure that this variable is set in the enviroment when
calling
.I qrsh
or
.I qmake
with option \fB\-inherit\fP. If you call
.I qrsh
or
.I qmake
with
option \fB\-inherit\fP from within a job script, export COMMD_PORT with the 
submit option or special comment "-v COMMD_PORT".
.\"
.IP "\fB\-j y|n\fP"
Available for \fIqsub\fP and \fIqalter\fP only.
.sp 1
Specifies whether or not the standard error stream of the job
is merged into the standard output stream.
.br
If both the \fB\-j y\fP and the \fB\-e\fP options are present,
xxQS_NAMExx sets, but ignores the error-path attribute.
.sp 1
.I Qalter
allows changing this option even while the job executes. The modified
parameter will only be in effect after a restart or migration of the job,
however.
.\"
.IP "\fB\-l resource=value\fP,..."
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP and
\fIqalter\fP only.
.sp 1
Launch the job in a xxQS_NAMExx queue meeting the given resource request list.
In case of
.I qalter
the previous definition is replaced by the specified one.
.br
.M complex 5
describes how a list of available resources and their
associated valid value specifiers can be obtained.
.br
There may be multiple \fB\-l\fP switches in a single
command. You may request multiple \fB\-l\fP options to be
soft or hard both in the same command line. In case of a
serial job multiple \fB\-l\fP switches refine the definition
for the sought queue.
.sp 1
.I Qalter
allows changing this option even while the job executes. The modified
parameter will only be in effect after a restart or migration of the job,
however.
.\"
.IP "\fB\-m b|e|a|s|n,...\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP and
\fIqalter\fP only.
.sp 1
Defines or redefines under which circumstances mail is to be sent
to the job owner or to the users defined with the
\fB\-M\fP option described below. The option arguments
have the following meaning:
.sp 1
.nf
.ta \w'|b|  'u
`b'     Mail is sent at the beginning of the job.
`e'     Mail is sent at the end of the job.
`a'     Mail is sent when the job is aborted or 
        rescheduled.
`s'     Mail is sent when the job is suspended.
`n'     No mail is sent.
.fi
.sp 1
Currently no mail is sent when a job is suspended.
.sp 1
For
.I qsh
and
.I qlogin
mail at the beginning or end of the job is suppressed
when it is encountered in a default request file.
.sp 1
.I Qalter
allows changing the b, e, and a option arguments even while the job
executes. The modification of the b option argument will only be in
effect after a restart or migration of the job, however.
.\"
.IP "\fB\-M user[@host],...\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP and
\fIqalter\fP only.
.sp 1
Defines or redefines the list of users to which the server that executes
the job has to send mail, if the server sends mail about the job.
Default is the job owner at the originating host.
.sp 1
.I Qalter
allows changing this option even while the job executes.
.\"
.IP "\fB\-masterq queue,...\fP"
Available for \fIqsub\fP, \fIqrsh\fP, \fIqsh\fP, \fIqlogin\fP and \fIqalter\fP.
Only meaningful for parallel jobs, i.e. together with the -pe option.
.sp 1
Defines or redefines a list of queues which may be used to become the so
called
.I master queue
of this parallel job. The
.I master queue
is defined as
the queue where the parallel job is started. The other queues to which the
parallel job spawns tasks are called \fIslave queues\fP.
A parallel job only has one \fImaster queue\fP.
.sp 1
This parameter has all the properties of a resource request and will be
merged with requirements derived from the \fB\-l\fP option described above.
.sp 1
.I Qalter
allows changing this option even while the job executes. The
modified parameter will only be in effect after a restart or migration of
the job, however.
.\"
.IP "\fB\-notify\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP and
\fIqalter\fP only.
.sp 1
This flag,
when set causes xxQS_NAMExx to send "warning" signals
to a running job prior to sending the signals themselves. If
a SIGSTOP is pending the job will receive a SIGUSR1 several
seconds before the SIGSTOP. If a SIGKILL is pending the job
will receive a SIGUSR2 several seconds before the SIGKILL.
The amount of time delay is controlled by the \fBnotify\fP
parameter in each queue configuration (see
.M queue_conf 5 ).
.sp 1
Note, that the Linux operating system "misuses" the user signals SIGUSR1
and SIGUSR2 in its current Posix thread implementation. You might not want
to use the \fB\-notify\fP option if you are running threaded applications
in your jobs under Linux.
.sp 1
.I Qalter
allows changing this option even while the job executes.
.\"
.IP "\fB\-now y[es]|n[o]\fP"                        
Available for \fIqsub\fP, \fIqsh\fP, \fIqlogin\fP and \fIqrsh\fP.
.sp 1
\fB\-now y\fP
tries to start the job immediately or 
not at all. The command returns 0 on success, or 1 on failure (also if
the job could not be scheduled immediately).
\fB\-now y\fP is default for \fIqsh\fP, \fIqlogin\fP and \fIqrsh\fP
.br
With option \fB\-now n\fP the job will be put into the pending queue, if it
cannot be executed immediately. \fB\-now n\fP is default for \fIqsub\fP.
.\"
.IP "\fB\-N name\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP and
\fIqalter\fP only.
.sp 1
The name of the job. The name can be any printable set
of characters, starting with an alphabetic character.
.br
If the \fB\-N\fP option is not present xxQS_NAMExx assigns
the name of the job script to the job after 
any directory pathname has been removed from the
script-name. If the script is read from standard
input the job name defaults to STDIN.
.br
In case of
.I qsh
or
.I qlogin
and if the \fB\-N\fP option is absent the string `INTERACT' is 
assigned to the job.
.sp 1
.I Qalter
allows changing this option even while the job executes.
.\"
.IP "\fB\-noshell\fP"
Available only for \fIqrsh\fP with a commandline.
.sp 1
Do not start the commandline given to \fIqrsh\fP in a users login shell
but execute it without the wrapping shell.
.sp 1
The option can be used to speed up execution as some overhead like the  
shell startup and sourcing the shell resource files is avoided.
.sp 1
The option can only be used, if no shell specific commandline parsing is
required. If the commandline contains shell syntax like environment
variable substitution or (back) quoting, a shell must be started.
In this case either do not use the \fB\-noshell\fP option or include
the shell call in the commandline.
.sp 1
Example:
.br 
qrsh echo '$HOSTNAME'
.br 
Alternative call with the -noshell option
.br 
qrsh -noshell /bin/tcsh -f -c 'echo $HOSTNAME'
.\"
.IP "\fB\-nostdin\fP"
Available only for \fIqrsh\fP.
.sp 1
Suppress the input stream STDIN - \fIqrsh\fP will pass the option -n to 
the
.M rsh 1
command. This is especially usefull, if multiple tasks
are executed in parallel using \fIqrsh\fP, e.g. in a
.M make 1
process - it would be undefined, which process would get the input.
.\"
.IP "\fB\-o [hostname:]path,...\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP and
\fIqalter\fP only.
.sp 1
The path used for the standard output stream of the job. The
\fBpath\fP is handled as described in the \fB\-e\fP option for
the standard error stream.
.sp 1
By default the file name for standard
output has the form \fIjob_name.\fPo\fIjob_id\fP and
\fIjob_name.\fPo\fIjob_id\fP.\fBtask_id\fP for job array tasks (see
\fB\-t\fP option below).
.sp 1
.I Qalter
allows changing this option even while the job executes. The modified
parameter will only be in effect after a restart or migration of the job,
however.
.\"
.IP "\fB\-ot override_tickets\fP"
Available for \fIqalter\fP only.
This option is only supported in case of a xxQS_NAME_EExx system. It is not available  
for xxQS_NAME_Cxx systems.
.br
Changes the number of override tickets for the specified job.
Requires manager/operator privileges.
.\"
.IP "\fB\-P project_name\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP and
\fIqalter\fP only.
This option is only
supported in case of a xxQS_NAME_EExx system. It is not available for xxQS_NAME_Cxx systems.
.br
Specifies the project to which this job is assigned. The administrator
needs to give permission to individual users to submit jobs to a
specific project. (see \fB\-aprj\fP option to
.M qconf 1 ).
.\"
.IP "\fB\-p priority\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP and
\fIqalter\fP only.
.sp 1
Defines or redefines the priority of the job relative to other jobs.
Priority is an integer in the range -1023 to 1024.
The default priority value for the jobs is 0.
.sp 1
In a xxQS_NAME_Cxx system, users may only decrease the priority of their jobs.
xxQS_NAME_Cxx managers and administrators may also increase the priority
associated with jobs. If a pending job has higher priority, it is
earlier eligible for being dispatched by the xxQS_NAME_Cxx scheduler. The job
priority has no effect on running jobs in xxQS_NAME_Cxx.
.sp 1
In xxQS_NAME_EExx, the job priority influences the Share Tree Policy and the Functional
Policy. It has no effect on the Deadline and Override Policies (see
.M share_tree 5 ,
.M sched_conf 5
and the
.I xxQS_NAME_EExx Installation and Administration Guide
for further information on the resource management policies supported by xxQS_NAME_EExx).
.sp 1
In case of the Share Tree Policy, users can distribute the tickets, to
which they are currently entitled, among their jobs using different
priorities assigned via \fB\-p\fP. If all jobs have the same priority
value, the tickets are distributed evenly. Jobs receive tickets
relative to the different priorities otherwise. Priorities are treated like
an additional level in the share tree in the latter case.
.sp 1
In connection with the Functional Policy, the priority can be used to
weight jobs within the functional job category.
Again tickets are distributed relative to any
uneven priority distribution treated as a virtual share distribution level
underneath the functional job category.
.sp 1
If both, the Share Tree and the Functional Policy are active, the job
priorities will have an effect in both policies and the tickets
independently derived in each of them are added up to the total number of
tickets for each job.
.\"
.IP "\fB\-pe parallel_environment \fBn\fP[\fB-\fP[\fBm\fP]]|[\fB-\fP]\fBm\fP,...\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP and
\fIqalter\fP only.
.sp 1
Parallel programming environment (PE) to instantiate. The
range descriptor behind the PE name specifies the number of
parallel processes to be run. xxQS_NAMExx will allocate the
appropriate resources as available. The
.M xxqs_name_sxx_pe 5
manual page contains information about the definition of PEs
and about how to obtain a list of currently valid PEs.
.br
You can specify the PE name  by using the wildcard character "*", thus
the request "pvm*" will match any parallel environment with a name
starting with the string "pvm".
.br
The range specification is a list of range expressions of the
form n-m (n as well as m being positive non-zero integer
numbers), where m is an abbreviation for m-m, -m is a short
form for 1-m and n- is an abbreviation for n-infinity. The
range specification is processed as follows: The largest
number of queues requested is checked first. If enough queues
meeting the specified attribute list are available, all are
allocated. The next smaller number of queues is checked next
and so forth.
.br
If additional \fB\-l\fP options are present, they restrict the
set of eligible queues for the parallel job.
.sp 1
.I Qalter
allows changing this option even while the job executes. The modified
parameter will only be in effect after a restart or migration of the job,
however.
.\"
.IP "\fB\-q queue,...\fP"
Available for \fIqsub\fP, \fIqrsh\fP, \fIqsh\fP, \fIqlogin\fP and \fIqalter\fP.
.sp 1
Defines or redefines a list of queues which may be used to execute this
job. This parameter has all the properties of a resource request and
will be merged with requirements derived from the \fB\-l\fP option
described above.
.sp 1
.I Qalter
allows changing this option even while the job executes. The modified
parameter will only be in effect after a restart or migration of the job,
however.
.\"
.IP "\fB\-r y|n\fP"
Available for \fIqsub\fP and \fIqalter\fP only.
.sp 1
Identifies the ability of a job to be rerun or not.
If the value of \fB\-r\fP is 'y', rerun the job if the job was aborted
without leaving a consistent exit state 
(this is typically the case if the node on which the job is running
crashes).
If \fB\-r\fP is 'n', do not rerun the job under any circumstances.
.br
Interactive jobs submitted with
.I qsh
or
.I qlogin
are not re-runable.
.sp 1
.I Qalter
allows changing this option even while the job executes.
.\"
.IP "\fB\-sc variable[=value],...\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP and
\fIqalter\fP only.
.sp 1
Sets the given name/value pairs as the job's context. \fBValue\fP may be
omitted. xxQS_NAMExx replaces the job's previously defined context with
the one given as the argument.
Multiple \fB\-ac\fP, \fB\-dc\fP, and \fB\-sc\fP options may be given.
The order is important here.
.br
Contexts are a way to dynamically attach and remove meta-information
to and from a job. The context variables are \fBnot\fP passed to the job's
execution context in its environment.
.sp 1
.I Qalter
allows changing this option even while the job executes.
.\"
.IP "\fB\-soft\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP and
\fIqalter\fP only.
.sp 1
Signifies that all resource requirements following in the
command line will be soft requirements and
are to be filled on an "as available" basis.
.br
As xxQS_NAMExx scans the command line and script file for xxQS_NAMExx
options and parameters it builds a list of resources required
by a job. All such resource requests are considered as
absolutely essential for the job to commence. If the
\fB\-soft\fP option is encountered during the scan
then all following resources are designated as "soft
requirements" for execution, or "nice-to-have, but not
essential". If the \fB\-hard\fP flag (see above) is encountered at a later
stage of the scan, all resource requests following it once
again become "essential". The \fB\-hard\fP and \fB\-soft\fP
options in effect act as "toggles" during the scan.
.\"
.IP "\fB\-S [host:]pathname,...\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqlogin\fP and \fIqalter\fP.
.sp 1
Specifies the interpreting shell for the job. Only one \fBpathname\fP
component without a \fBhost\fP specifier is valid and only one path name
for a given host is allowed. Shell paths with host
assignments define the interpreting shell for the job if the host is the
execution host. The shell path without host specification is used if the
execution host matches none of the hosts in the list.
.sp 1
Furthermore, the pathname can be constructed with pseudo environment
variables as described for the \fB\-e\fP option above.
.sp 1
In the case of
.I qsh
the specified shell path is used to execute the 
corresponding command interpreter in the
.M xterm 1
(via its \fI\-e\fP option) 
started on behalf of the interactive job. 
.sp 1
.I Qalter
allows changing this option even while the job executes. The modified
parameter will only be in effect after a restart or migration of the job,
however.
.\"
.IP "\fB\-t n[-m[:s]]\fP"
Available for \fIqsub\fP and \fIqalter\fP only.
.sp 1
Submits a so called \fIJob Array\fP, i.e. an array of identical tasks being
only differentiated by an index number and being treated by xxQS_NAMExx
almost like a series of jobs. The option argument to \fB\-t\fP specifies
the number of job array tasks and the index number which will be associated
with the tasks. The index numbers will be exported to the job tasks via the
environment variable \fBxxQS_NAME_Sxx_TASK_ID\fP.
.sp 1
The task id range specified in the option argument
may be a single number, a simple range of the form
n-m or a range with a step size. Hence, the task id range specified by
2-10:2 would result in the task id indexes 2, 4, 6, 8, and 10,
i.e. in a total of 5 tasks identical tasks with the environment variable
xxQS_NAME_Sxx_TASK_ID containing one of the 5 index numbers each.
.sp 1
All job array tasks inherit the same resource requests and attribute
definitions as specified in the \fIqsub\fP or \fIqalter\fP command line,
except for the \fB\-t\fP option. The tasks are scheduled independently and,
provided enough resources, concurrently very much like separate jobs.
However, a job array or a sub-array thereof can be accessed as a total by
commands like
.M qmod 1
or
.M qdel 1 .
See the corresponding manual pages for further detail.
.sp 1
Job arrays are commonly used to execute the same type of operation on
varying input data sets correlated with the task index number. The number
of tasks in a job array is unlimited.
.sp 1
STDOUT and STDERR of job array tasks will be written into different files
with the default location
.sp 1
.nf
<jobname>.['e'|'o']<job_id>'.'<task_id>
.fi
.sp 1
In order to change this default, the \fB\-e\fP and \fB\-o\fP options (see
above) can be used together with the pseudo environment variables $HOME,
$USER, $JOB_ID, $JOB_NAME, $HOSTNAME, and $xxQS_NAME_Sxx_TASK_ID.
.sp 1
Note, that you can use the output redirection to divert the output of all
tasks into the same file, but the result of this is undefined.
.\"
.IP "\fB\-u username,... | -uall\fP"
Available for \fIqalter\fP only. Changes are only made on those
jobs which were submitted by users specified in the list
of usernames.
For managers it is possible to use the \fB\qalter -uall\fP command
to modify all jobs of all users.
.sp 1
If you use the \fB\-u\fP or \fB\-uall\fP switch it is not permitted to
specify an additional \fI\job/task_id_list\fP.
.\"
.IP "\fB\-v variable[=value],...\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP, \fIqalter\fP
and \fIqresub\fP.
.sp 1
Defines or redefines the environment variables to
be exported to the execution context of the job.
If the \fB\-v\fP option is present xxQS_NAMExx will add
the environment variables defined as arguments to the switch and,
optionally, values of specified variables, to the execution context of
the job.
.sp 1
.I Qalter
allows changing this option even while the job executes. The modified
parameter will only be in effect after a restart or migration of the job,
however.
.\"
.IP "\fB\-verbose\fP"
Available only for \fIqrsh\fP and
.M qmake 1 .
.sp 1
Unlike \fIqsh\fP and \fIqlogin\fP, \fIqrsh\fP does not output any 
informational messages while establishing the session compliant
with the standard
.M rsh 1
and
.M rlogin 1
system calls.
If the option \fB-verbose\fP is set, \fIqrsh\fP behaves as verbose as 
the \fIqsh\fP and \fIqlogin\fP commands and outputs informations about 
the process of establishing the
.M rsh 1
or
.M rlogin 1
session.
.\"
.IP "\fB\-verify\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP, \fIqalter\fP
and \fIqresub\fP.
.sp 1
Does not submit a job but prints information on the job as being 
represented by the current command\-line and all pertinent external 
influences.
.\"
.IP "\fB\-V\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP, \fIqalter\fP
and \fIqresub\fP.
.sp 1
Specifies that all environment variables active within the
.I qsub
utility be exported to the context of the job.
.\"
.IP "\fB\-w e\fP|\fBw\fP|\fBn\fP|\fBv\fP"
Available for \fIqsub\fP, \fIqsh\fP, \fIqrsh\fP, \fIqlogin\fP, \fIqalter\fP
and \fIqresub\fP.
.sp 1
Specifies a validation level applied to the job to be submitted
(\fIqsub\fP, \fIqlogin\fP,
and \fIqsh\fP) or the specified queued job (\fIqalter\fP).
The information displayed 
indicates whether the job possibly can be scheduled assuming an empty 
system with no other jobs. Resource requests exceeding the configured 
maximal thresholds or requesting unavailable resource attributes are  
possible causes for jobs to fail this validation.
.sp 1
The specifiers e, w, n and v define the following validation modes:
.sp 1
.nf
.ta \w'|b|  'u
`e'	error - jobs with invalid requests will be
	rejected; the default for \fIqrsh\fP, \fIqsh\fP
	and \fIqlogin\fP.
`w'	warning - only a warning will be displayed
	for invalid requests.
`n'	none - switches off validation; the default for
	\fIqsub\fP and \fIqalter\fP.
`v'	verify - does not submit the job but prints
	extensive validation report.
.fi
.sp 1
Note, that the necessary checks are performance consuming and hence the 
checking is switched off by default.
.sp 1
Note also, that the reasons for job requirements being invalid with respect to 
resource availability of queues are displayed in the "\fB-w v\fP" case using 
the format as described for the
.M qstat 1
\fB\-F\fP option (see description of 
\fBFull Format\fP in section \fBOUTPUT FORMATS\fP of the
.M qstat 1
manual page.
.\"
.IP "\fBjob/task_id_list\fP"
Specified by the following form:
.sp 1
.ta 0.5i
    \fIjob_id[.task_range][,job_id[.task_range],...]\fP
.ta 0.0i
.sp 1
If present, the \fItask_range\fP restricts the effect of the 
operation to the job array task range specified as suffix to the job id
(see the \fB\-t\fP option to
.M qsub 1
for further details on job arrays).
.sp 1
The task range specifier has the
form n[-m[:s]]. The range may be a single number, a  simple
range  of the form n-m or a range with a step size.
.sp 1
Instead of job/task_id_list it is possible to
use the keyword 'all' to modify all jobs of the
current user.
.\"       
.IP "\fBscriptfile\fP"
Available for \fIqsub\fP only.
.sp 1
The job's scriptfile.
If not present or if the operand is the 
single-character string '-',
.I qsub
reads the script from standard input.
.\"
.IP "\fBscript_args\fP"
Available for \fIqsub\fP and \fIqalter\fP only.
.sp 1
Arguments to the job. Not valid if the script is entered from standard
input.
.sp 1
.I Qalter
allows changing this option even while the job executes. The modified
parameter will only be in effect after a restart or migration of the job,
however.
.\"
.IP "\fBxterm_args\fP"
Available for \fIqsh\fP only.
.sp 1
Arguments to the
.M xterm 1
executable, as defined in the configuration.
For details, refer to
.M xxqs_name_sxx_conf 5 ).
.\"
.\"
.SH "ENVIRONMENTAL VARIABLES"
.\" 
.IP "\fBxxQS_NAME_Sxx_ROOT\fP" 1.5i
Specifies the location of the xxQS_NAMExx standard configuration
files.
.\"
.IP "\fBxxQS_NAME_Sxx_CELL\fP" 1.5i
If set, specifies the default xxQS_NAMExx cell. To address a xxQS_NAMExx
cell \fIqsub\fP, \fIqsh\fP, \fIqlogin\fP or \fIqalter\fP use (in the order of precedence):
.sp 1
.RS
.RS
The name of the cell specified in the environment 
variable xxQS_NAME_Sxx_CELL, if it is set.
.sp 1
The name of the default cell, i.e. \fBdefault\fP.
.sp 1
.RE
.RE
.\"
.IP "\fBxxQS_NAME_Sxx_DEBUG_LEVEL\fP" 1.5i
If set, specifies that debug information
should be written to stderr. In addition the level of
detail in which debug information is generated is defined.
.\"
.IP "\fBCOMMD_PORT\fP" 1.5i
If set, specifies the tcp port on which
.M xxqs_name_sxx_commd 8
is expected to listen for communication requests.
Most installations will use a services map entry instead
to define that port.
.\"
.IP "\fBCOMMD_HOST\fP" 1.5i
If set, specifies the host on which the particular
.M xxqs_name_sxx_commd 8
to be used for xxQS_NAMExx communication of the
\fIqsub\fP, \fIqsh\fP, \fIqlogin\fP or \fIqalter\fP
client resides.
Per default the local host is used.
.\"
.PP
In addition to those environment variables specified to be
exported to the job via the \fB\-v\fP or the \fB\-V\fP option
(see above)
\fIqsub\fP, \fIqsh\fP, and \fIqlogin\fP
add the following variables with the indicated values to the variable
list:
.sp 1
.IP "\fBxxQS_NAME_Sxx_O_HOME\fP" 1.5i
the home directory of the submitting client.
.IP "\fBxxQS_NAME_Sxx_O_HOST\fP" 1.5i
the name of the host on which
the submitting client
is running.
.IP "\fBxxQS_NAME_Sxx_O_LOGNAME\fP" 1.5i
the LOGNAME of the submitting client.
.IP "\fBxxQS_NAME_Sxx_O_MAIL\fP" 1.5i
the MAIL of the submitting client. This is 
the mail directory of the submitting client.
.IP "\fBxxQS_NAME_Sxx_O_PATH\fP" 1.5i
the executable search path of the submitting client.
.IP "\fBxxQS_NAME_Sxx_O_SHELL\fP" 1.5i
the SHELL of the submitting client.
.IP "\fBxxQS_NAME_Sxx_O_TZ\fP" 1.5i
the time zone of the submitting client.
.IP "\fBxxQS_NAME_Sxx_O_WORKDIR\fP" 1.5i
the absolute path of the current working directory of the
submitting client.
.PP
Furthermore, xxQS_NAMExx sets additional variables into the
job's environment, as listed below.
.IP "ARC" 1.5i
The xxQS_NAMExx architecture name of the node on which the job is
running. The name is compiled-in into the
.M xxqs_name_sxx_execd 8
binary.
.IP xxQS_NAME_Sxx_CKPT_ENV 1.5i
Specifies the checkpointing environment (as selected with the \fB\-ckpt\fP
option) under which a checkpointing job executes. Only set for checkpointing
jobs.
.IP "xxQS_NAME_Sxx_CKPT_DIR" 1.5i
Only set for checkpointing jobs. Contains path \fIckpt_dir\fP
(see
.M checkpoint 5
) of the checkpoint interface.
.IP xxQS_NAME_Sxx_STDERR_PATH 1.5i
the pathname of the file to which the standard error stream of the job is
diverted. Commonly used for enhancing the output with error messages
from prolog, epilog, parallel environment start/stop or checkpointing
scripts.
.IP xxQS_NAME_Sxx_STDOUT_PATH 1.5i
the pathname of the file to which the standard output stream of the job is
diverted. Commonly used for enhancing the output with messages from
prolog, epilog, parallel environment start/stop or checkpointing scripts.
.IP xxQS_NAME_Sxx_JOB_SPOOL_DIR 1.5i
The directory used by
.M xxqs_name_sxx_shepherd 8
to store job related data during job
execution. This directory is owned by root or by a xxQS_NAMExx administrative
account and commonly is not open for read or write access to regular users.
.IP xxQS_NAME_Sxx_TASK_ID 1.5i
The index number of the current job array task (see \fB\-t\fP option
above). This is an unique number in each job array and can be used to
reference different input data records, for example. This environment
variable is not set for non-array jobs.
.IP "ENVIRONMENT" 1.5i
The ENVIRONMENT variable is set to BATCH to identify that the job is being
executed under xxQS_NAMExx control.
.IP "HOME" 1.5i
The user's home directory path from the
.M passwd 5
file.
.IP "HOSTNAME" 1.5i
The hostname of the node on which the job is running.
.IP "JOB_ID" 1.5i
A unique identifier assigned by the
.M xxqs_name_sxx_qmaster 8
when the job was
submitted. The job ID is a decimal integer in the range 1 to 99999.
.IP "JOB_NAME" 1.5i
The job name, either `INTERACT' for interactive jobs or
built from the \fIqsub\fP
script filename, a period, and the digits of the job ID.
This default may be overwritten by the
.I -N.
option.
.IP "LAST_HOST" 1.5i
The name of the preceding host in case of migration of a checkpointing
job.
.IP "LOGNAME" 1.5i
The user's login name from the
.M passwd 5
file.
.IP "NHOSTS" 1.5i
The number of hosts in use by a parallel job.
.IP "NQUEUES" 1.5i
The number of queues allocated for the job (always 1 for serial jobs).
.IP "NSLOTS" 1.5i
The number of queue slots in use by a parallel job.
.IP "PATH" 1.5i
A default shell search path of:
.br
.ta 5i
/usr/local/bin:/usr/ucb:/bin:/usr/bin
.IP "PE" 1.5i
The parallel environment under which the job executes (for parallel
jobs only).
.IP "PE_HOSTFILE" 1.5i
The path of a file containing the definition of the virtual parallel
machine assigned to a parallel job by xxQS_NAMExx. See the description of
the
.B $pe_hostfile
parameter in
.M xxqs_name_sxx_pe 5
for details on the format of this file. The environment variable
is only available for parallel jobs.
.IP "QUEUE" 1.5i
The name of the queue in which the job is running.
.IP "REQUEST" 1.5i
Available for batch jobs only.
.sp 1
The request name of a job as specified with the
\fB\-N\fP switch (see above) or taken as the name of the job
script file.
.IP "RESTARTED" 1.5i
This variable is set to 1 if a job was restarted either after a system
crash or after a migration in case of a checkpointing job. The variable has
the value 0 otherwise.
.IP "SHELL" 1.5i
The user's login shell from the
.M passwd 5
file. \fBNote:\fP This is not necessarily the shell in use for the job.
.IP "TMPDIR" 1.5i
The absolute path to the job's temporary working directory.
.IP "TMP" 1.5i
The same as TMPDIR; provided for compatibility with NQS.
.IP "TZ" 1.5i
The time zone variable imported from
.M xxqs_name_sxx_execd 8
if set.
.IP "USER" 1.5i
The user's login name from the
.M passwd 5
file.
.\"
.\"
.SH RESTRICTIONS
.PP
There is no controlling terminal for batch jobs under xxQS_NAMExx and
any tests or actions on a controlling terminal 
will fail. If these operations are in
your .login or .cshrc file, they will possibly
cause your job to abort.
.PP
Insert the following test before any commands
that are not pertinent to batch jobs in your .login:
.PP
.nf
.RS
if ( $?JOB_NAME) then
.RS
echo "xxQS_NAMExx spooled job"
exit 0
.RE
endif
.RE
.fi
.PP
Don't forget to set your shell's search path in your
shell start-up before this code.
.\"
.\"
.SH EXIT STATUS
The following exit values are returned:
.IP "0" 0.5i
Operation was executed successfully.
.IP "25" 0.5i
It was not possible to register a new job according to the configured
.I max_u_jobs
or
.I max_jobs
limit. Additional information may be found in
.M sge_conf 5
.
.IP ">0" 0.5i
Error occured.
.\"
.\"
.SH EXAMPLES
The following is the simplest form of a xxQS_NAMExx script file.
.nf

=====================================================


#!/bin/csh
   a.out


=====================================================
.fi
.sp 1
The next example is a more complex xxQS_NAMExx script.
.nf

=====================================================

#!/bin/csh                           
                        
# Which account to be charged cpu time 
#$ -A santa_claus

# date-time to run, format [[CC]yy]MMDDhhmm[.SS]
#$ -a 12241200                   

# to run I want 6 or more parallel processes
# under the PE pvm. the processes require
# 128M of memory
#$ -pe pvm 6- -l mem=128

# If I run on dec_x put stderr in /tmp/foo, if I
# run on sun_y, put stderr in /usr/me/foo
#$ -e dec_x:/tmp/foo,sun_y:/usr/me/foo

# Send mail to these users
#$ -M santa@heaven,claus@heaven

# Mail at beginning/end/on suspension
#$ -m bes

# Export these environmental variables
#$ -v PVM_ROOT,FOOBAR=BAR

# The job is located in the current 
# working directory.
#$ -cwd

a.out

==========================================================

.fi
.\"
.\"
.SH FILES
.nf
.ta \w'$REQUEST.hostsJID[.TASKID]  'u
\fI$REQUEST.oJID[.TASKID]\fR	STDOUT of job #JID
\fI$REQUEST.eJID[.TASKID]\fR	STDERR of job
\fI$REQUEST.poJID[.TASKID]\fR	STDOUT of par. env. of job
\fI$REQUEST.peJID[.TASKID]\fR	STDERR of par. env. of job
\fI$REQUEST.hostsJID[.TASKID]\fR	hosts file of par. env. of job
.PP
.ta \w'<xxqs_name_sxx_root>/.xxqs_name_sxx_aliases   'u
\fI$cwd/.xxqs_name_sxx_aliases\fR	cwd path aliases
\fI$cwd/.xxqs_name_sxx_request\fR	cwd default request
\fI$HOME/.xxqs_name_sxx_aliases\fR	user path aliases
\fI$HOME/.xxqs_name_sxx_request\fR	user default request
\fI<xxqs_name_sxx_root>/<cell>/common/.xxqs_name_sxx_aliases\fP
	cluster path aliases
\fI<xxqs_name_sxx_root>/<cell>/common/.xxqs_name_sxx_request\fP
	cluster default request
\fI<xxqs_name_sxx_root>/<cell>/common/act_qmaster\fP
	xxQS_NAMExx master host file
.fi
.\"
.\"
.SH "SEE ALSO"
.M xxqs_name_sxx_intro 1 ,
.M qconf 1 ,
.M qdel 1 ,
.M qhold 1 ,
.M qmod 1 ,
.M qrls 1 ,
.M qstat 1 ,
.M accounting 5 ,
.M xxqs_name_sxx_aliases 5 ,
.M xxqs_name_sxx_conf 5 ,
.M xxqs_name_sxx_request 5 ,
.M xxqs_name_sxx_pe 5 ,
.M complex 5 .
.\"
.\"
.SH "COPYRIGHT"
If configured correspondingly,
.I qrsh
and
.I qlogin
contain portions of the
\fIrsh\fP, \fIrshd\fP, \ftelnet\fP and \fItelnetd\fP
code copyrighted by The Regents of the University of California.
Therefore, the following note applies with respect to \fIqrsh\fP and
\fIqlogin\fP: This
product includes software developed by the University of California,
Berkeley and its contributors.
.sp 1
See
.M xxqs_name_sxx_intro 1
as well as the information provided in <xxqs_name_sxx_root>/3rd_party/qrsh
and <xxqs_name_sxx_root>/3rd_party/qlogin
for a statement of further rights and permissions.
